
== 1. Oral Phase (0 to 3 years))

=== 2. Projection (Freud, 1894; Willick, 1993))
- —You attribute your own stuff to
another person. (another person.)

=== 3. Introjection (Freu...)
— —You form an
image of another person. (1970; Volkan, 1976)—You form an, image of another person.)

=== 4. Hallucination (Garma,...)
— —You see or hear what
you are trying not to think about—
wishes, comments, fantasies, or
criticisms—with no reality testing. (you are trying not to think about—, wishes, comments, fantasies, or, criticisms—with no reality testing.)

== 5. Anal Phase (1.5 to 5 years))

=== 6. Projective Identification(Kernberg,
1975))
- —Three common ways this term ()

=== 7. Projecting so much of yourself
onto someone else that you
massively distort him or her.
Stimulating i...)
— . (onto someone else that you, massively distort him or her., Stimulating in someone else your, unpleasant affects (“misery loves, company”).)

=== 8. Stimulating in someone else your
u...)
—  (the person who had made you feel, so bad.)

=== 9. Projective Blaming(Spruiell, 1989))
- —
You unfairly blame somebody else for
your problem. (your problem.)

=== 10. Denial (A.Freud, 1936; Moo...)
— —Assumes you’ve
perceived reality (reality sense is
functional): (perceived reality (reality sense is, functional):)

=== 11. Denial per se: Disavowal of a
reality in spite of overwhelming
evidence of its existence.
Denial in deed: Behavior that
symbolically sa...)
—  (evidence of its existence., Denial in deed: Behavior that, symbolically says, “That nasty, reality isn’t true!”)

=== 12. Denial in fantasy: Maintaining
erroneous beliefs so...)
—  (have to see the reality.)

=== 13. Denial by words: Using special
words to convince yours...)
—  (falsity of a reality.)

=== 14. Dedifferentiation (Self-Object Fusion))
  ()

=== 15. (Mahler, 1968))
- —You become whatever
someone else wants you to be. (someone else wants you to be.)

=== 16. Splitting(Kern...)
— —You see
certain people as purely hostile
(McDevitt, 1985), and others as purely
loving. Or, you now hate the devil you
loved. ((McDevitt, 1985), and others as purely, loving. Or, you now hate the devil you, loved.)

=== 17. Animism(Freud, 1913; Mahler, 1968))
- —
You give human qualities to nonhuman
entities. (entities.)

=== 18. Deanimation (Mahler, 1968))
- —The
person you see isn’t human, so you
don’t have to worry. (don’t have to worry.)

=== 19. Reaction-Formation (A.Freud, 1936;
Gor...)
— —You feel opposite (e.g.,
so nice you can’t tell you’re angry). (so nice you can’t tell you’re angry).)

=== 20. Undoing and Rituals—You go against
your conscience (superego))
- . Or you do ()

=== 21. what you feel guilty about and atone by
punishing yourself in another symbo...)
—  ()

=== 22. . Isolation (of Affect))
- (C.Brenner, 1982a) ()

=== 23. —yYou are unaware of the sensation of
affects.)
  ()

=== 24. Externalization(Glover, 1955))
- —You
think “Society” will criticize you, but
actually you feel guilty. (actually you feel guilty.)

=== 25. . Turning on the Self(Freud, 1917;)
  ()

=== 26. A.Freud, 1936))
- —You’re angry at
someone, but attack/kill yourself
instead. (instead.)

=== 27. Negativism (Levy & Inderbitzin, 1989))
- —You refuse to cooperate, and treat
other people condescendingly. (other people condescendingly.)

=== 28. Compartmentalization(Freud, 1926))
- —
You inhibit yourself from making
connections. (connections.)

=== 29. Hostile aggression(Symonds, 1946;
McDevitt, 1985))
- —You get into fights to
hide unpleasant feelings. (hide unpleasant feelings.)

=== 30. First Genital Phase (2 to 6 years))
  ()

=== 31. Displacement(...)
— —You feel one way
toward a person, but shift it to another
person or situation. (toward a person, but shift it to another, person or situation.)

=== 32. Symbolization(Freud, 1900a; A...)
— —You give irrational
meaning to some aspect of mental
functioning. (meaning to some aspect of mental, functioning.)

=== 33. Condensation (Freud, 1900a; Arlow &
Bre...)
— —You weld together
disparate ideas that are contiguous. (disparate ideas that are contiguous.)

=== 34. Illusion Formation or Daydreaming
(Ra...)
— —You consciously
visualize a scene that is upsetting or (visualize a scene that is upsetting or)

=== 35. pleasant, and know it’s a fantasy.)
  ()

=== 36. Prevarication (Karpman, 1949))
- —You
lie on purpose, for a reason. ()

=== 37. Confabulation(Spiegel, 1985; Target,
1998))
- —You lie without knowing it, to
relieve lowered self-esteem. (relieve lowered self-esteem.)

=== 38. Repression(Freud, 1923; Arlow &
Brenner, 1964))
- —You forget thoughts
without wanting to. (without wanting to.)

=== 39. Negative Hallucination(Wimer, 1989))
- —You don’t see something upsetting
that’s right in front of you. (that’s right in front of you.)

=== 40. Libidinal Regression [Psychosexual
Regressio...)
— — You
are afraid of sex and assertiveness, so
you become dependant (oral) or
stubborn (anal) instead. (are afraid of sex and assertiveness, so, you become dependant (oral) or, stubborn (anal) instead.)

=== 41. Ego Regression—Three ways this term
is used:)
  ()

=== 42. a. Interference with a fun...)
—  (working, so you can’t feel, something unpleasant.)

=== 43. b. Reversio...)
—  (defense mechanisms that arose in, an early stage of development.)

=== 44. c. Inefficient defensive operations:
Your defenses fail to shut off)
  ()

=== 45. affect, and the failure relieves guilt
by punishing you.)
  ()

=== 46. Temporal Regression—You focus on
earlier times to not think about ...)
—  (conflict.)

=== 47. Topographic Regression (Arlow &
Brenner, 1964))
- —You dream to avoid
painful reality. (painful reality.)

=== 48. Suppression (Werman, 1985))
- —You
purposely try to forget. ()

=== 49. Identification with a Fantasy—You act
like your favorite hero or heroine.)
  ()

=== 50. Identification with Parents’
Unconscious or Con...)
— —You do as your parents forbid,
act out their corrupt wishes, and get
punished. (Wishes/Fantasies (Johnson & Szurek,, 1952)—You do as your parents forbid,, act out their corrupt wishes, and get, punished.)

=== 51. Identification with the Ideal Image or
...)
— —You think and
act like someone you think is great. (act like someone you think is great.)

=== 52. Identification with th...)
— —You act
abusive to a person because someone
has acted abusive to you. This protects
you from feeling angry. (abusive to a person because someone, has acted abusive to you. This protects, you from feeling angry.)

=== 53. Identification with the)
  ()

=== 54. ...)
— —You act like
someone else by either allowing or
seeking victimization. You do this as a
rescue wish or to fight off your own
anger or guilt. (someone else by either allowing or, seeking victimization. You do this as a, rescue wish or to fight off your own, anger or guilt.)

=== 55. 37. Identificatio...)
— —You act like a lost loved
one. If you keep souvenirs and never
grieve, you’ve got “established
pathological mourning” (Volkan,
1987a). (one. If you keep souvenirs and never, grieve, you’ve got “established, pathological mourning” (Volkan,, 1987a).)

=== 56. 38. Identification with the Introject
(Sandler, 1960))
- —You make an introject
part of your superego. (part of your superego.)

=== 57. 39. Seduction of the A...)
— —You seduce
someone sexually or sycophantically to
relieve fear. (someone sexually or sycophantically to, relieve fear.)

=== 58. Latency Phase (6 to 11 years))
  ()

=== 59. 40. Sublimation (A.Freud, 1936))
- —You
engage in an activity that symbolically
represents a fantasy. (represents a fantasy.)

=== 60. 41. Provocation (...)
— —You
get other people to have sex with or
punish you, or both. (get other people to have sex with or, punish you, or both.)

=== 61. 42. Rationalization (Symonds, 1946))
- —You
make excuses to relieve tension, usually
after denying some reality. (after denying some reality.)

=== 62. Rumination— You “overanalyze”...)
—  (“spin your wheels” trying to solve, problems.)

=== 63. Counterphobic Behavior (Blos, 1962,
1979))
- —You do exactly what scares you. ()

=== 64. Intellectualization (A.Freud, 1936))
- —
You get cranked up about a peculiar
theory of behavior. (theory of behavior.)

=== 65. Socialization and Dista...)
— —You use your social
ability to distract yourself from painful
thoughts. (ability to distract yourself from painful, thoughts.)

=== 66. In...)
— —You attach symbolic
meaning to an ego function (e.g.,
“Washing dishes is women’s work”
irrationally equates a certain type of
work with gender). (meaning to an ego function (e.g.,, “Washing dishes is women’s work”, irrationally equates a certain type of, work with gender).)

=== 67. ...)
— —Your instinctualized ego
function clashes with guilt, so you shut
off the function (e.g., you can’t read
because reading is equated with
forbidden sexual activity [Anthony,
1961)). (function clashes with guilt, so you shut, off the function (e.g., you can’t read, because reading is equated with, forbidden sexual activity [Anthony,, 1961)).)

=== 68. Idealization:(Kernberg, 1975; Kohut,
1971))
- —You overvalue someone because
of: (of:)

=== 69. a. narcissism (Freud, 1914a))
- : to relieve shame over your inadequacy ()

=== 70. b. narcissism (Kohut, 1971))
- : you fuse
the person with your overestimated
self-image (“selfobject’’) (self-image (“selfobject’’))

=== 71. c. love: to not experience
disappointments)
  ()

=== 72. d. transference (Freud, 1914b))
- :
they’re like a wonderful parent,
when you were little. (when you were little.)

=== 73. Devaluation—You look down on
someone to preserve your own self-
esteem.)
  (esteem.)

=== 74. Adolescence and Later-Second
Genital Phase (13 to 20 years plus))
  ()

=== 75. Humor (Zwerling,...)
— —You use kidding around to avoid
painful feelings. If you get extremely
wound up, you’re hypomanic (Lewin,
1950; Almansi, 1961). (painful feelings. If you get extremely, wound up, you’re hypomanic (Lewin,, 1950; Almansi, 1961).)

=== 76. ...)
— —You stop
using abstract thinking (which you
have); you blame a “chemical
imbalance” or look for a virus to avoid
thinking relationships make you upset. (have); you blame a “chemical, imbalance” or look for a virus to avoid, thinking relationships make you upset.)

=== 77. Disidentification (Greenson, 1968))
- —
You endeavor not to be like one of your
parents. (parents.)

=== 78. Group formation (Freud...)
— —You
surround yourself to guard against
sexual impulses. (surround yourself to guard against, sexual impulses.)

=== 79. Asceticism (A.Freud, 1936))
- —You avoid
contact with humans. Ipsisexual Object
Choice— (Choice—)

=== 80. Ipsisexual Object Choice—Your same-
sex “buddy” allays fear of ...)
—  (stimulation.)

=== 81. One affect versus Another (Ackerman
& Jahoda, 1948))
- —You focus on one
emotion to avoid another. (emotion to avoid another.)

=== 82. Hyperabstraction—You abuse theories.
If you also ...)
—  (you’re probably psychotic.)

=== 83. Reticence—You stop speaking to avoid
being found out.)
  ()

=== 84. Garrulousness— You’ re talking too
much, but aren’t circumstanti...)
—  (tangential.)

=== 85. Avoidance—You stay away from
situations due to the conflicts they
...)
—  (generate.)

=== 86. Passivity—You automatically adopt a
compliant or submiss...)
—  (face of aggression.)

=== 87. Grandiosity/Omnipotence (Freud,
1913; Kohut, 1971; Ker...)
— —You are God’s gift to
earth, have special powers. (1913; Kohut, 1971; Kernberg, 1975;, Lachmann & Stolorow, 1976;, Blackman, 1987)—You are God’s gift to, earth, have special powers.)

=== 88. Passive to Active—“You can’t fire me;
I quit!” You control yo...)
—  (victimization.)

=== 89. Somatizatio...)
— —You focus on your
body to avoid conflicts with oral, sexual,
or hostile impulses. (body to avoid conflicts with oral, sexual,, or hostile impulses.)

=== 90. Normalization (Alpert & Bernstein,
...)
— —You convince yourself you are
normal despite obvious
psychopathology. (normal despite obvious, psychopathology.)

=== 91. Dramatization—You inject emotion
into your speech to relieve ...)
—  (being noticed.)

=== 92. Impulsivity (Lustman, 1966))
- —You use
sex, eating, or hostility to relieve tension
or an unpleasant affect. (or an unpleasant affect.)

=== 93. Substance Abuse (Wurmser, 1974))
- —
You use a concoction to quell
unpleasurable affects. (unpleasurable affects.)

=== 94. Clinging (Schilder, 1939))
- —Clutching
onto a person who rejects you. Whining ()

=== 95. Whining—Complaining, you don’t see
the infantile quality of y...)
—  (taken care of.)

=== 96. Pseudoindependence—You become the
Lone Ranger, not allowing anyone...)
—  (help you.)

=== 97. Pathological...)
— —Actually projection and identification
with the victim: you deny oral urges,
project them onto the needy, then
vicariously feel nurtured. (with the victim: you deny oral urges,, project them onto the needy, then, vicariously feel nurtured.)

=== 98. Gaslighting (Calef & Weinshel, 1...)
— —You cause people to be
mentally disturbed or to believe they
are. (mentally disturbed or to believe they, are.)

=== 99. Minimization—You are conscious of a
painful reality but give that re...)
—  (weight.)

=== 100. Exaggeration (Sperling, 1963))
- —You
make too much of a deal over
something. (something.)

=== 101. Generalization (Loeb, 1982))
- —To not
hate someone, you see him as part of an
evil group. (evil group.)

=== 102. Reconstruction of Reality (Freeman,
1962))
- —YYou reinvent a situation after
denying the reality. (denying the reality.)

Process finished with exit code 0
