Julie Andrews was born on October 1, 1935, in a village called - Walton-on-Thames , — in England.

She grew up ina talented family. When she
_ was a little girl, her aunt would help put on show:

at a nearby playhouse. Julie’s mother would play —

piano, and her father built sets.

Julie gave her very first performance at one
of these shows. And she helped a fellow dancer
whose hat had fallen over her eyes. Even at age _
three, Julie knew the show must go on! F


When Julie was four years old, World War ge

began. At that point, Julie was living with her

mother and stepfather in London, where bombs
often fell.

To stay safe, Julie and her brother sometimes
had to go to the countryside and live with
strangers. While there, they loved learning
to ride horses.

Other times, her family hid in the London
Underground train stations with their neighbors.
Her stepfather would play guitar to take people’s

_ minds off the danger.


Meanwhile, Julie was learning to dance and sing.
She went to a special school, where she learned
ballet and tap dance. At age nine, she started taking
singing lessons.

Julie’s mother was a wonderful piano player, and her stepfather was a well-known
singer. They started to invite Julie onstage to sing with them.Julie enjoyed the
spotlight.

Not long after the war finally ended, Julie was
asked to perform for some British soldiers. She
didn’t know that Queen Elizabeth would also be

in the audience! The queen told Julie that she sang
beautifully.


Julie became known for her sweet, high
voice. She spent her teenage years traveling
around England, singing and dancing in
shows. She loved the stage, but she missed
her family when she was away.

Whenever she was homesick, Julie would
go to her dressing room and read. Books
helped her feel less lonely.



When Julie was sixteen years old, she went to
see a musical on the West End of London, where
some of the best plays in the world are performed.

Julie was amazed. The music! The costumes!
The sets! She never thought she would have the
chance to be in a show like that.

But she would—and soon! Just two years
later, Julie was cast as the star in Cinderella on
the West End. There were fancy costumes, a big
moving set, and real ponies on the stage. Julie
and the show got great reviews.

Thanks to the success of Cinderella,
Julie got her next big break—a role in a
Broadway musical, called The Boy Friend. ~~
Julie was going to New York!




Julie was sad to leave, but she couldn’t say no
to Broadway. Her whole family gathered at the
airport to see her off.

While rehearsing in New York, Julie struggled
at first. Sometimes she felt she was doing a good
job, and other times she didn’t. The director told
her to play the role as honestly as she could. On
opening night, the audience gave the show a
standing ovation.


The cast and crew waited overnight at a
nearby restaurant to read the reviews in the
next morning’s newspaper. The critics loved
the show—and Julie. It was official. Julie
Andrews was a Broadway star!


Later that year, a songwriting
duo named Lerner and Loewe were
finishing their newest musical. They

didn’t think Julie would be available
to star in it because most Broadway §

actors had two-year contracts. But
Julie had only wanted a one-year |
contract for her first show so that 7
she could visit her family sooner.

After a quick trip to England, Julie went back
to New York to star in My Fair Lady.

Julie played a flower seller named Eliza
Doolittle who learns to speak like a fancy lady.
Just like Eliza, Julie had to learn to speak in a new
accent. It was very difficult.

Her hard work paid off. My Fair Lady became
the longest-running Broadway musical at the

time, and the cast recording was the number-one
album of 1956.


Julie continued to act and sing in hit
musicals. One day, Walt Disney visited her
backstage after a show. He wanted her to star
in his next movie. Julie had performed on
Broadway, at the famous Carnegie Hall,
and on television—but never in movies.

By then, Julie had gotten married. Not long after
giving birth to her first daughter, Julie and her family
flew to Hollywood, California, so Julie could star in
Walt Disney’s Mary Poppins. Julie won the Academy
Award for Best Actress for her performance as the
magical nanny—and fans everywhere learned the
word “supercalifragilisticexpialidocious.”



In 1965, just one year after Mary Poppins was
released, Julie starred in The Sound of Music. In this
movie musical, Julie played a nun in training named
Maria who falls in love while looking after seven
children in the Austrian mountains. It became one
of her most famous roles, thanks to such songs as
“My Favorite Things” and “Do-Re-Mi.”

Julie spent the next twenty years starring in
movies. She also welcomed four more children
into her life.

One day, Julie’s stepdaughter, Jenny, asked her
to write a story for her. That was when Julie came
up with the idea for her first children’s book. She
would go on to write and publish many more.


Thirty-five years after leaving New York to
make Mary Poppins, Julie finally decided to return
to Broadway. She brought her role from the movie
musical Victor/Victoria to the stage.

Julie worked as hard as ever on this show, and
it was a big success.

Over the years, Julie sometimes found that
her voice got very tired, especially after singing in
a Broadway show for many months in a row. She
had to take long rests, do special exercises, and
occasionally have surgery to help keep her voice
healthy. But at one point, something went wrong.

After her most recent surgery, she found that she
couldn’t sing at all.


Julie was sad—she loved to sing! But although
fifty years had passed since she had read alone
in her dressing room, she knew books could still
bring comfort in a difficult time. With the help
of her daughter Emma, Julie wrote and published

many more children’s books and books about her
own life.

Julie stayed busy. She helped others, spent
time with her family, and kept starring in films.
She played a queen in the Princess Diaries movies
and another queen in the Shrek movies. But she
said it was the greatest honor of her life when
the real queen—Queen Elizabeth II—gave her
a special award honoring her work.


Julie Andrews followed her dreams, going
from her small village to London, New York,
Hollywood, and all over the world. She worked
hard to create unforgettable characters on the
screen, in books, and onstage.

Her many fans will always be
inspired by her talents, and they
will always love Julie Andrews.

== Oprah Winfrey
When Oprah got a little older, she lived
with her mother and younger half siblings in
Milwaukee. They didn’t have much money, and
life there was hard.

One Christmas, some nuns came to her house
and gave her and her family food and toys. The
nuns made Oprah feel special. She decided she
would help others like that someday, too.

Oprah’s high grades helped her become one
of the first Black students to attend a school in
the wealthy part of town. But Oprah soon started
misbehaving. So in high school, Oprah went to
live with her father, Vernon, and her stepmother,
Zelma, in Nashville, Tennessee.


Life was different there. Vernon was strict and
made sure Oprah did well in school. She followed

her dad’s rules, worked hard, and made many
friends.

At seventeen, Oprah won the Miss Fire
Prevention beauty pageant. When she picked up
her prize at a Nashville radio station, a DJ heard
her speak. He knew her voice was special, and he
hired Oprah to read the news as an after-school

job. She loved reading out loud, and now she was
being paid to do it!

-
Oprah was an excellent news anchor, but she
didn’t hide her feelings. Sometimes when a story
was sad, she would cry. Her boss didn’t like that.

But a new boss realized Oprah’s emotions were
a good thing—she could connect with others. He
made her cohost of a talk show called People Are
Talking. Audiences loved Oprah!


Just a few years later, Oprah moved to Illinois
and became the host of her own talk show called
AM Chicago. Again, Oprah was a hit!

One fan was a producer named Quincy Jones.
He asked her to act in his movie The Color
Purple. As a child, Oprah had admired beautiful
Black performers like Sidney Poitier and Diahann
Carroll, so this was a dream! She played the
role of Sofia so well she was nominated for an
Academy Award.

In 1986, The Oprah Winfrey Show, as AM
Chicago was now called, was shown across
America! That same year, Oprah started Harpo
Productions (Harpo is Oprah spelled backward)

and became the first Black woman to own a
TV studio.

Oprah worked hard to make her show great.
She talked with regular people and famous
people. She had fun road trips and awesome rock
concerts. She also shared secrets about herself.
Her show was so popular because Oprah made
everybody feel special.

»”))


----- Text from 10.png -----
Oprah was famous, just as she had dreamed.
But not everyone was nice to her. Sometimes
people made up stories about her past or said
unkind things about how she looked.

Thankfully, Oprah has people she can trust,
including her best friend, Gayle, and her partner,
Stedman Graham.

Oprah’s fans trust her opinion on just about
everything. Oprah loves reading, so she started a
book club. Many of the books she recommends
become bestsellers because so many people want
to read what she’s reading.


Some fans even wanted her to run for
president! Oprah wasn’t interested in that job,
but she spoke highly of someone who was: a

rising politician named Barack Obama.

CHANGE

WE CAN BELIEVE IN

People listened. Obama was elected
president twice.

Oprah’s hard work has earned her a lot of

money, and her big heart has led her to share her

wealth in many ways. Once she gave an entire
audience brand-new cars!


In 2011, after twenty-five years and 4,561
episodes, Oprah ended her beloved talk show.
But she’s still as busy as ever. She continues to
interview celebrities, produce and star in movies,
oversee her media platform Oprah Daily, run

her television network (OWN), and support
numerous charities.

When she’s not working, Oprah enjoys
spending time with her family and friends at
her beautiful homes, taking long walks with her
“fur children” (she’s had more than twenty dogs
S throughout the years!), and curling up with
serenade

a good book.

Oprah never forgot how special she felt when
those nuns helped her family so many years ago.
Now she uses her gifts to help make millions of
other people feel special, too.

Oprah never forgot how special she felt when
those nuns helped her family so many years ago.
Now she uses her gifts to help make millions of


== Jonny Appleseed
a fine September day

more than two hundred

years ago, a boy named. John

J ohnny grew up in Massachusetts,
in a small, crowded house.

He liked to take long walks in the woods, where

it was calm and quiet. He liked to feel the sun on his
face and the earth under his bare feet.

4
When Johnny turned eighteen, he took a very long Settlers were starting to go west in covered
walk—more than four hundred miles! He brought along | wagons, looking for new places to live. Johnny
food, supplies, and a sack of apple seeds. figured they would want apples to eat and press into
Johnny had an idea.

cider. But there were no apple trees out west. Even
if the settlers planted seeds, it would take years for
trees to sprout and grow fruit.

Why not give the
settlers a head start?

Johnny reached Pennsylvania. Near a river, he
found a patch of land with rich soil and plenty of
sunlight. A perfect place for growing apple trees!

He planted some seeds. Then he built a sturdy
fence so that when the new seedlings came up,
deer and rabbits wouldn’t eat them.


Johnny planted more seeds—thousands of them—

Meanwhile, the settlers came. Sure enough, they
across Pennsylvania, Ohio, and Indiana. He worked wanted apples! They were happy to pay Johnny a few
and he walked, going from nursery to nursery to tend
his trees.

cents apiece for seedlings. Sometimes he even gave
them away to families who were
down on their luck.



People spread the word about Johnny and his
apple trees. That’s how he got his nickname.

Have you met Johnny Appleseed? He’s mighty kind,
people said. Mighty peculiar, too!

It was true. For one thing, Johnny looked

strange. He wore old, ragged pants. He cut holes
in coffee sacks to make his shirts.

He still didn’t wear shoes. By now, folks

claimed, his feet were so tough, a snake’s fangs
couldn’t prick them!


... and then cook his dinner in it!

Johnny’s diet was
another thing people
couldn’t get over. He
didn’t like to hurt
animals, so he wouldn’t
eat meat. Not one bite!
He filled up on corn
mush, potatoes, and

- nuts instead.

a pile of leaves.
He didn’t seem to
worry about the bear:



Johnny might have been odd, but he was friendly.
He got along with just about everyone he met.

Native Americans shared their trails with him.
They showed him which berries were safe to eat,

and how to make medicine from leaves and roots.

Settlers invited Johnny into their cabins and asked

him to tell stories. Sometimes he read from the Bible.

“Good news fresh from heaven!” he’d say. Other times,
he acted out his own wild adventures.



People retold Johnny’s tales . . . and made up new
ones, too! As the years went by, the tales grew taller
and taller... .

Once he tricked ten
woodsmen into a chopping
contest. They cleared a
whole acre of land for

Did you know Johnny can thaw ice
with his bare feet?

He has a tame wolf that
follows him around like

a puppy!



The stories wound their way east and west
and back again.

So did Johnny. He traveled hundreds of miles
a year, making new nurseries and tending the ©
old ones.

He kept this up for nearly fifty years!


Johnny was sorely missed. But he was not forgotten—
and neither was his great idea.
As settlers moved farther and farther west, they

carried along apple seeds, just the way Johnny had.
They planted apple trees of their own.

Today, apples grow in every state in America!

The apples that grew on Johnny’s trees
were mostly “‘spitters.” That meant they were

too sour to eat! Settlers used them to make
cider and vinegar.

Johnny’s worn-out clothes made him look
poor, but he wasn’t. When he died, he owned
over a thousand acres of land.

There’s a monument for Johnny in
Indiana, near the spot where he died. The
stone lists both of his names: JOHN CHAPMAN

and JOHNNY APPLESEED. And underneath:
HE LIVED FOR OTHERS.

Johnny probably walked more than a
hundred thousand miles in his lifetime.


== Elton John


Wen Elton John was born on March 25,

1947, he wasn’t Elton John at all. His name

was Reginald Dwight. He lived with his parents,

Sheila and Stanley, in his grandmother's house

in a town called Pinner, near London, England.
Reg was an only child. He often

felt awkward and shy, but one

thing made him light up: music.


Reg’s dad was a trumpet player. His mom
listened to lots of records. Even as a little kid,
Reg could hear a song once and know how to play
it on the piano. He took lessons and practiced.
His piano playing got better and better.

He got so good that the Royal Academy of
Music in London gave him a scholarship when
he was eleven years old. He went there to study
music every Saturday.

Well, almost every Saturday. Sometimes he
skipped out to buy records of his favorite rock
stars. The academy taught him classical music,
but Reg loved rock and roll!


At fifteen, Reg got a steady job playing the
piano at a local pub. Sometimes the rowdy crowd
sang along. Other times, they ignored him.

But Reg didn’t mind. He just kept on singing.

As a teenager, Reg played in a band called
Bluesology. After a few years, he saw an ad in
a newspaper: LIBERTY RECORDS WANTS TALENT.
They were looking for singers and songwriters.
Reg had talent! He could play piano and sing.
He could write melodies. But he wasn’t great at
writing lyrics—the words to the songs.


Reg didn’t get the job.
But a man at the record company handed
him lyrics written by Bernie Taupin, who had

answered the ad, too. Maybe together they could
write something special.

Reg and Bernie hit it off right away.

Reg knew he wanted to make music forever. *
But he didn’t feel cool enough for rock and roll.
And his name didn’t sound like a rock star. He
needed a change.

He borrowed “John” from one friend and

“Elton” from another. Just like that, Reg Dwight
became ELTON JOHN.





Elton and Bernie tried writing music for other
people, but when their quirky songs didn’t sell,
Elton sang them himself. His first album came
out in 1969. Hardly anyone paid attention to it.

Elton and Bernie kept trying. The more songs
they wrote, the better they got. Elton soon
recorded a second album.

That album changed everything.


e record company booked Elton at a
popular club in Los Angeles, California, calle
| the Troubadour. Famous musicians liked to

hang out there. That night, some even cai
hear him play!

though he was nervous, Elton launched int
is music. He stood up, kicked back his stool, an
pounded on the piano keys. He rocked the place.
and the crowd loved it!
After that, sales of the new album went
Iton and Bernie had a hit!


« Elton loved the spotlight, but he felt hidden
behind his piano. Other rock stars could carry
_ their instruments while they moved around the
stage. How could he make himself stand out?
He dressed in flashy clothing. He did
handstands on the keyboard. He sat on the floor
and reached up to play the piano keys. Elton knew
a how to grab a crowd’s attention—and keep it!

Elton and Bernie made hit after hit. Elton went
on tour, putting on shows in cities and countries
all around the world. Radio stations played his
songs. Fans wanted his autograph.

provi!
ROC

In 1973, he got a star on the Hollywood Walk

of Fame. But Elton John wasn’t just a star—he
was a superstar!


Even though he was famous, Elton didn’t take
himself too seriously. He played one concert in

a Donald Duck costume. For another, he sported
a sequined baseball uniform.

He wore hats, feathers, platform boots, and
really big glasses! Nothing was too over the top.

 One song, “Can You Feel t
onight,” won an Academy Award. Late:
movie became a Broadway show.

_ First music, then movies

In 1993, Elton met David Furnish, a filmmaker
from Canada. They fell in love, got married, and

had two kids, Zachary and Elijah. His family made
Elton very happy.


Everywhere he went, Elton made friends. He
danced with Princess Diana and sang with John
Lennon. He—and his music—helped lift people
up when they were sad or lonely.

Through it all, Elton and Bernie continued to
write songs together. Elton said Bernie was the
best friend he ever had.

Elton knew that, thanks to his fame, he could
help a lot of people. He started a charity to
support patients with AIDS, a disease that attacks
the body’s immune system. Every year, he holds
an Oscar party to raise money for the Elton John
AIDS Foundation.

The Queen of England even knighted him in honor of his music and charity work. Today,
he is Sir Elton Hercules John.

More than just his name has changed since
he was that shy, awkward kid. But one thing
has stayed the same: when he plays music,
Elton John lights up!


== Bee Gees
Barry, Maurice, and Robin Gibb made up the pop-
rock band the Bee Gees. They were singers. They
were songwriters. They were disco icons. But most
importantly, they were brothers.

Barry Gibb was born on September 1, 1946. His
younger twin brothers, Maurice and Robin, were born
on December 22, 1949. All three were born on the
Isle of Man, an island between Ireland and England.


The brothers grew up with music all around them.
Their father, Hugh, played the drums and was a
bandleader. Their mother, Barbara, loved to sing. The
Gibb family also included the boys’ older sister, Lesley,
and younger brother, Andy.

When Barry was nine, he was given a guitar as
a gift. Shortly after that, Barry, Maurice, and Robin
started performing around town. The brothers sang in
harmony, which is when singers’ voices blend together.
Back then, they called themselves the Rattlesnakes.

The brothers were certain that one day, they would
become famous.




In 1958, the family took a boat from England to In Australia, they played to crowds at a local racetrack,
Australia to start a new life. The brothers entertained catching the attention of first a race car driver and then
the other passengers on the long journey. a DJ. Both had the same initials as Barry. Because of that

coincidence, they renamed their group the BGs. Soon
after, their name officially became the Bee Gees.


Nine years later, the brothers decided to return to
England to chase their musical dreams. It was 1967,
and the London music scene was hopping. Everyone
loved a group called the Beatles. The Bee Gees hoped
people would love their music, too.


The Bee Gees got to work writing and recording.
They were inspired by legendary Black musicians such
as Smokey Robinson and Otis Redding, who played
blues and Motown music. The brothers worked those
musical styles into their own songs.

Their first big single was called “New York Mining
Disaster 1941.” The brothers wrote this song in a
stairwell during a power outage!

It was soon followed by two more hits, “To Love
Somebody” and “Massachusetts.” The band’s first

number one song in America, “How Can You Mend
a Broken Heart,” was released a few years later.


The brothers needed to do something different

to keep their fans interested. They went to Miami,
Florida, to record their next album. Being in a new

place inspired their new sound.

The band was doing great! But people’s taste
in music was changing.




In the Miami recording studio, Barry sang falsetto—
which made his voice sound higher—and the band
used synthesizers to create a more electronic tone.

The biggest hit from their new album was “Jive
Talkin’ .” It quickly boogied its way up to number one
on the music charts. The Bee Gees were back on
With these changes, the Bee Gees’ new disco sound top, and disco fever took over the world!
was born!


The Bee Gees’ producer requested some new songs
for a movie he was working on. Little did they know,
this movie would make the band more popular than
ever. Saturday Night Fever premiered in 1977. One of

the band’s most famous songs, “Stayin’ Alive,” played
during the very first scene.

The Saturday Night Fever soundtrack didn’t just
have one hit written by the Bee Gees—it had seven!
The album sold forty million copies and won four

Grammy Awards. Disco was played in clubs around the
world, and everyone danced to the Bee Gees’ music.



The Bee Gees had hits in the 1960s, 1970s, 1980s,
and 1990s! And with each decade, their style changed.
Their hair was short, long, and shaggy. Their music was
slow and fast. They sang low. They sang high. They sang
together. And they wore everything from blazers to bell-
bottom pants to sequined shirts.


But the one thing that never changed was their love
of making music. When disco stopped being popular,
the brothers wrote songs for other performers, including
Barbra Streisand, Kenny Rogers, Dolly Parton, and

Dionne Warwick. |


When Maurice passed away in 2003 and then Robin in
2012, Barry was left without his brothers. After thinking
about their time together and their epic careers, Barry
decided to make music again. He rerecorded some of the

Bee Gees’ classic songs with the help of famous country
music stars like Keith Urban.

After making music for more than forty years, the

Bee Gees were inducted into the Rock and Roll Hall of
Fame in 1997.


The Gibb brothers wrote over one thousand songs

and had countless number one hits. Their harmonies are
world famous, their lyrics tell stories, and their beats make
people want to shimmy and sway. Their music continues

to influence artists today.


The Bee Gees’ sound is still stayin’ alive!

== Dr. JONAS SALK
JONAS SALK WAS
A DOCTOR, WHO
SAVED MANY LIVES
BY CREATING
A VACCINE FOR, POLIO.

Jonas was born on October 28, 1914. He
and his younger brothers grew up near a
grassy park in the Bronx, in New York City.
The Salk family was Jewish. Jews were
treated harshly in many countries. Jonas’s
mother, Dora, escaped Russia when she was

thirteen. His father, Daniel, was also from an
immigrant family. Daniel and Dora hoped to
give their three sons a better life.


In 1918, when Jonas was four, he watched
wounded soldiers march in a parade to mark
the end of World War I.

That year, millions of people got sick from
influenza, or the flu. Many soldiers caught it. So
did families who crowded the streets to see parades.

curious from
Jonas was a quiet boy. He liked to spend time alone,

the earliest
reading and wondering about the world. He felt sad %
when he saw people suffering or in pain. age Ov


The flu was just one disease people worried
about. Jonas sometimes saw children his own

age wearing leg braces to help them walk. They’d
gotten a disease called polio.

Since polio spreads easily from person to person,
public swimming pools were closed to keep children

safe. Even in summer, kids couldn’t go outside to
play. Everyone felt afraid.

Polio is caused by the polio virus, a tiny germ. It can

damage nerves in the spine and cause problems with
moving and even breathing.

When Jonas was a boy, future president Franklin D.
Roosevelt got polio and lost his ability to walk. Still,
Roosevelt would go on to do great things.

And so would Jonas!

ere
Jonas
school when he was fifteen.
He became the first in his
family to go to college. The
City College of New York
was free, so Jonas only had
to pay for his books and
the fare for the streetcar.

Jonas fell in love with chemistry and medicine.
He decided to become a doctor to help others.


In medical school, Jonas asked lots of questions.
This helped him solve problems in the laboratory. He

liked performing experiments and became fascinated
by viruses.

On June 8, 1939, Jonas graduated from New York
University Medical School. He was now a doctor.

The next day, Jonas became a husband, too.
During their marriage, Jonas and his wife, Donna,
had three children: Peter, Darrell, and Jonathan.
They all grew up to become doctors, like their dad

Long before that, Jonas’s boys would help him
make medical history.

Jonas was brilliant. But it wasn’t easy for

The world was at war again. Jonas remembered
a young Jewish doctor who hadn’t gone to fancy the soldiers on parade and the crowds he’d seen
schools to find a job. However, in 1942, Jonas went when he was little. Jonas and Dr. Francis wanted to
to work for a scientist who'd once been his teacher: prevent another terrible flu outbreak. They went to
Dr. Thomas Francis Jr.

work finding a new way to make a safe vaccine for
influenza. And in 1943, they did just that!


After the war, Jonas started the Virus Research
Laboratory at the University of Pittsburgh. Soon he

was presented with his greatest challenge: to make
a vaccine to fight polio.

Vaccines tell our bodies to make special proteins
alled antibodies to fight off diseases. Vaccines help
us stay healthy.


People had been hoping for a polio vaccine for

a long time. By the early 1950s, there were as many
as 50,000 new cases of polio each year.


Jonas wanted to give people hope, too. He often
visited children with polio in the hospital wards near

his lab. Some could only breathe with the help of a big
machine called an iron lung.


When Jonas saw how much polio victims suffered,
he worked even harder to create a safe vaccine.

He used a recently discovered way to grow the
polio virus in his lab, and then he killed the virus so
it couldn’t make anyone sick. No one else was making
vaccines in this way. But Jonas felt sure that if he used

the killed virus as a vaccine, it would keep people from
getting polio.

The process wasn’t easy. Jonas and his team of
scientists worked hard for many long months. At last,
one night in 1953, Jonas brought something home
from the lab: his new vaccine!

Peter, Darrell, and Jonathan got their shots early in
the testing program—and right in their own kitchen.
Peter said it didn’t even hurt. Of course, their parents
got vaccinated, too.

Jonas felt sure he’d found the best way to prevent
polio. However, to prove that the vaccine was safe
and effective, he needed to test it on many others.

He needed polio pioneers!

Jonas had no interest in making money from
the vaccine. When he was asked who owned it,
he replied, “Well, the people, I would say.”

tt ase is

The people of America
_- were ready. Almost two
: million children took part

in a nationwide test of the

polio vaccine. : NX
On April 12, 1955, : ee
the test results were —

announced: the Salk


safe and effective!


nearly disappeared from the United States and
many other countries.

As long as everyone stays vaccinated, children
just like you can run and play without fear of getting
the disease. If we each do our part, we can save lives"
and help make polio disappear everywhere. aie


Jonas Salk became famous and was beloved by
everyone in America. He spent his whole life working
to help others.

Jonas died in 1995 at age eighty. But his dreams live
on at the Salk Institute for Biological Studies, where
researchers seek new cures to benefit us all.

Just like Jonas, they strive to make hopes come true.


== Strong as Sandow
Eugen Sandow was known as “the Strongest Man

on Earth.” He could break metal chains by expanding his
broad chest. He could hoist a grand piano over his head.
He boasted that he once wrestled a five-hundred-pound lion.
No doubt Eugen Sandow was the strongest of all strongmen.
But he wasn’t always strong.


The Delicate Days
K6nigsberg, Prussia, 1867-1885?

His birth name was Friedrich Wilhelm Miller. As a boy, he loved
athletics. But playing sports required a strong, healthy body.
Friedrich’s arms were skinny, and his legs were as frail as twigs.
He looked downright feeble. Often, he was too sick to play.

Friedrich was awestruck by the statues of ancient athletes.
Their muscles looked so powerful. If only he could look like a
Roman gladiator!

“How is it that these men were so strong, Father?”
Friedrich asked.

“The heroes of old,” his father said, “were ever active, ever
exercising their bodies.”

But Friedrich survived. His spirit was strong. He played sports,
and he excelled in school. As a reward for his high honors, his
father took him on a trip to Italy. They visited the famous art
galleries of Rome.



Exercise—that was it! To make his body stronger, Friedrich
would need to push himself even harder. When he returned
home, he ran longer and jumped higher. He exercised like
never before.

But his ten-year-old body wasn’t ready to bloom just yet.

To Friedrich’s despair, it remained weak and puny.


but he longed to do something more

physically active.

Strong and Stronger : am
Prussia to Belgium, 1885?-1887 =r
One day a traveling circus rolled into town. Friedrich snuck away
from school to watch. He was starstruck by the performers—
tumblers, wrestlers, acrobats, strongmen. The lure was simply too
much to resist. Friedrich left the university and joined the circus.
He became an acrobat.

Life as an acrobat was physically demanding. Friedrich tumbled
and bent and balanced. He flipped and flopped and stood on his

hands. Soon he began to notice a change in his body: his muscles
were getting bigger and stronger.

But the circus turned out to be a ragtag operation. It ran out of
money, and Friedrich lost the job he so adored.

To support himself, Friedrich found work as a model for art
students. His burly, ever-growing physique was the perfect
reference for their paintings and sculptures. Through their art,

Friedrich became the gladiator he had dreamed of being as a child.

One of the artists introduced Friedrich to Professor Attila,
a professional strongman. The Professor gave Friedrich a job at
his gym and offered to teach him bodybuilding.

“Attend to my instructions,” the Professor said, “and I shall
be able to make you the strongest man in the world.”

The Professor made Friedrich lift heavier weights. The metal
barbells were so heavy, Friedrich’s muscles quivered. But he didn’t
complain. The heavier the weights, the bigger his muscles grew.


Friedrich’s knowledge about the strongman business grew, too.
He learned about showmanship, costumes, and stage presence.

By the time he was twenty years old, Friedrich was a bona fide
professional strongman. He even changed his name. Friedrich
Miiller would be known forever after as Eugen Sandow.


The Big Challenge
London, 1889

Sampson and Cyclops were the greatest professional strongmen
of their time. They were brawny. They were brutes. They were

loudmouthed, muscle-bound lunks! Sampson and Cyclops lifted
horses and elephants as though they were as light as feathers.
Each night after their act in London, they roared out a
challenge to the audience: they dared anyone to try to defeat
them in a competition of strength. But who would accept such a
foolish challenge?
Eugen Sandow, that’s who.


Eugen jumped onstage. Dressed in a fine suit, he sauntered along
confidently—until he tripped over a barbell and almost fell on his
face. Everyone laughed—Sampson and Cyclops hardest of all.

But Eugen had a plan. With one swoop of his powerful arm, he
ripped off his suit, all at once. The audience gasped at the sight of

his mighty muscles.

The competition began. Sampson and Cyclops jerked pound
after pound of incredibly heavy weights above their heads. But
each time, Eugen effortlessly met their challenge. Sometimes
he lifted more. Sampson raged. Cyclops fumed. At last Eugen.
was declared the winner.


Victory and Beyond

London to America, 1890-1894

Victory over the great Sampson and Cyclops made Eugen famous.

He performed in music halls all over England, Scotland, and
Ireland. It wasn’t long before fame beckoned him overseas to the
United States.

First he performed at a casino in New York City. Then at a
theater in Boston. His popularity exploded when he performed at
the Chicago World’s Fair. Crowds poured into the theater to see
“the Modern Hercules.”


When the curtain rose, Eugen appeared onstage. He was dusted
head-to-toe with white powder, which made him look like a living,
breathing marble statue. When he lifted a heavy barbell over his
head, ‘some people in the audience gasped. Others fainted.

Truth be told, though, no one really cared about how much
weight Eugen could lift. They were in awe of his physique. His
chiseled muscles were things of beauty, like fine works of art.

After the show in Chicago, Eugen became one of the
most famous stars in America.


As Eugen went on to tell it, his greatest moment happened
one evening in San Francisco. “The Event of the Century”
packed hordes of spectators into a huge, circus-like tent.
Inside, a massive lion roared and people shrieked. But Eugen
was all confidence and smiles, ]


When Eugen entered the cage and flexed his hefty muscles,
the king of the beasts cowered down, tame as a kitty. Eugen
scooped up the lion and paraded him around the stage.

The lion wore mittens, and some people thought he looked
drugged. Was it all a trick? A showman’s illusion? Eugen Sandow
would never let on.

The so-called fight lasted just a few minutes, and the
strongman was declared the winner.

Home
America to London, 1898-1901

Eugen continued to travel. But over time the grueling schedule
proved too much even for him. He became tired and sickly.

He lost weight. His once powerful muscles seemed to fade away.
His body needed rest, and so did his mind.

Eugen said good-bye to America and returned home to Britain.

For months Eugen rested. While his body recovered, his brain

searched for ways to continue his career. He opened a gym. He
published books and magazines promoting bodybuilding and
nutritious eating. He designed his own equipment and techniques
for strengthening muscles. 31



In 1901 Eugen launched the Great Competition—the first
organized bodybuilding contest. Strongmen traveled from all
over the country to compete at the Royal Albert Hall in London.

But Eugen wasn’t interested in rewarding only big, muscular
physiques. He considered a man’s overall health and physical
development, too.

First the men performed athletic displays—wrestling,
gymnastics, even fencing. Then, after several rounds of posing,
a winner was chosen. He received a cash prize and a gold-plated
statue of none other than Eugen Sandow himself.




=

On the night of the Great Competition, Eugen Sandow
performed, too. He must have flexed a smile as broad as his
biceps. After all, the once-frail child was now known as “the
Strongest Man on Earth.” And it seemed that every man on
earth—and every woman and child, too—was now devoting
more attention to their own health. Everyone wanted to

34 become “as strong as Sandow.”


Afterword

David Beckham, LeBron James, and Justin Bieber are modern-day male superstars.
During the Victorian era (1837-1901), Eugen Sandow was that star. From England to
the United States and beyond, people flocked to see the strongman flex his muscles.

Deemed “the most perfect male specimen alive” by doctors of his time, Sandow
was often photographed in the buff, wearing only a fig leaf and high-laced sandals.
It was an image that harkened back to the Greek and Roman statues he had so
admired as a child. Sandow even measured the proportions of those statues in order
to develop his own body to more closely resemble them.

But while Sandow was fixated on looks, he was also passionate about helping
others to develop healthier minds and bodies. For children, he advocated a national
physical-fitness program in schools. For men, women, and children throughout
England, he established schools of physical culture. For everyone around the world,
he produced home exercise equipment and dietary supplements. His book Strength
and How to Obtain It became a best-seller, and his magazine, Sandow’s Magazine of
Physical Culture, was a forerunner to publications such as Flex and Men’s Health.

Sandow’s exercises and diet regimens are still in use today, as is the muscled
statuette that bears his name: the Sandow. For years, bodybuilding’s ultimate prize
was a sculpture of a nude, fig-leaf-adorned Sandow
clutching a barbell. The original was awarded at the 1901
Great Competition. Today the statuette is the top prize in
the Mr. Olympia bodybuilding competition. (For better
or for worse, the statuette was recently updated: the
Sandow is now beefier, and he’s lost the fig leaf in favor
of posing trunks.)

In his lifetime Sandow was filmed by no other than
Thomas Edison, and a plaster cast of his body was made
by the Natural History Museum in London. His followers
included celebrities such as Sherlock Holmes creator Arthur
Conan Doyle and famed writer James Joyce. He even
became the personal fitness instructor to King George V.

Eugen Sandow died in 1925 at the age of 58.

Life Is Movement!

Eugen Sandow believed it was important for everyone, especially kids, to stay physically active—
to move! Here are some exercises that you can try at home. With each exercise, be sure to keep
your back straight and your belly button tucked in—this will protect your back from injury.

Try to repeat each exercise ten times. And don’t forget to stretch first!

Push-ups

Balance on your hands and toes, keeping your
back straight. Bend your elbows and lower
yourself almost to the floor. Pause for a second,
then push back up, straightening your arms.
Focus on squeezing your chest muscles. Inhale
as you go down; exhale as you push up.

Chair squats

Stand a few inches in front of a chair, with your
feet apart and your toes facing forward. With
your weight on your heels, bend your knees until
you are ina sitting position—but don’t sit down!
Pause for a second, then return to the starting
position. Inhale as you lower; exhale as you rise.

Calf raises

Rest one hand on a wall for balance, with your
other hand hanging at your side. Rise up onto the
balls of your feet. Hold for a second, squeezing
your calf muscles, then lower to where you

started. Exhale as you rise; inhale as you lower.

If you have a pair of light dumbbells, great. If
Not, use two water bottles or cans of soup. Stand
with your feet apart and your knees slightly bent.
Holding a weight in each hand, begin with your
arms at your side. Slowly raise

your arms until they are in &
ey)
line with your shoulders, i
palms facing the floor. Hold
for a second, and return to \
where you started. Exhale
as you raise your arms;
inhale as you lower them.


Author’s Note
As a kid, I was skinny. Recognizing my anxiety about it, my dad
bought me a bench press and a copy of The Bodybuilder’s Nutrition
Book. It featured nutrition information, along with photos of famous
bodybuilders like Arnold Schwarzenegger and Lou Ferrigno. I was in
awe of their superhero-like physiques. I dreamed of someday having
powerful muscles like them.

Years later my younger brother, Brian, got involved in bodybuilding
and won a statewide contest. I wondered if I could bulk up and compete,

too. At age 32 I began my bodybuilding journey, training with my brother.

Don Tate, Upper Midwest Natural Bodybuilding We lifted weights, attended aerobics classes, practiced compulsory poses.
Championships, 1998. Two years later I entered my first bodybuilding contest. I was
terrified. I sweated a little (something you’re not supposed to do). I was having one of the best nights

of my life... until I lost. I didn’t even place. I was devastated, but I didn’t give up. I continued to lift
weights. I traded candy and sugary drinks for green beans, yams, and chicken breasts. And I perfected my
poses. When I competed again the next year, I took home first- and second-place trophies.

Natural bodybuilding is drug free—the use of steroids is forbidden. For that reason, there aren’t many
garbage-truck-size contestants at these shows. I may not have had the massive muscles of a superhero,
but I sure felt like I did.

Although I no longer compete in bodybuilding, I’ve often thought about writing a book for children
about it. But how? One day I stumbled upon a picture of Eugen Sandow online. Relating to his childhood
desire to beef up, I decided to tell his story.

Writing Sandow’s story was challenging. After his death, Sandow’s family destroyed his personal
belongings. In addition, books and magazine articles about him often contradict one another. It appears
Sandow was not only a builder of muscles, but also a manufacturer of his own story. Historians are still

unsure about his parentage and early life. They've even questioned the trip he and his father supposedly
made to Rome. And don’t even get me started on the controversy over the so-called fight with the lion!

My goal for this book was to tell the story as I think Sandow would have wanted it told, fanciful as
that might be. Regardless of his true origins (and a few less-than admirable things I learned about him),
the story of Eugen Sandow is an important one. His tale of sickly kid turned physical-fitness guru and
self-made businessman inspired millions of people. Through his example, Sandow demonstrated to the
world how a healthy body is necessary for a healthy mind. His lesson rings true today.

Bibliography

Art of Manliness. “The Art of Manliness Podcast #39: Eugen Sandow, Victorian Strongman, with David
Waller.” February 2, 2012. Available online at http://www.artofmanliness.com/2012/02/02/the-art-of-
manliness-podcast-39-eugen-sandow-victorian-strongman-with-david-waller/.

Barford, Vanessa, and Lucy Townsend. “Eugen Sandow: The Man with the Perfect Body.” BBC News Magazine,
October 19, 2012. Available online at http://www.bbc.com/news/magazine-19977415.

Buck, Joshua Michael. “The Development of the Performances of Strongmen in American Vaudeville Between
1881 and 1932.” Unpublished thesis, University of Maryland at College Park, 1999. Available online at
http://joshuabuck.com/about-josh/files/thesis.pdf.

Budd, Michael Anton. The Sculpture Machine: Physical Culture and Body Politics in the Age of Empire. New York:
New York University Press, 1997.

Chapman, David L. Sandow the Magnificent: Eugen Sandow and the Beginnings of Bodybuilding. Urbana and Chicago:
University of Illinois Press, 1994.

Dickson, W. K.-L., and William Heise. “Sandow.” Video by the Edison Manufacturing Co. 1894. Available
online at https://www.loc.gov/item/00694298/.

Liederman, Earle. “My Muscles Keep Me Young—Says Sandow.” Originally published in Muscle Builder (US),
December 1924. Available online at http://physicalculturist.ca/sandow-muscles-keep-me-young/.

Liederman, Earle. “Sandow: My Impressions When We First Met.” Originally published in Muscle Power (Canada),
April/May 1946. Available online at http://www.davidgentle.com/sandow/liederman/sandow.html.

Mordden, Ethan. Ziegfeld: The Man Who Invented Show Business. New York: St. Martin’s Press, 2008.

Pearl, Bill, George Coates, Tuesday Coates, and Richard Thornley Jr. Legends of the Iron Game: Reflections on the
History of Strength Training. Vol. 1. Phoenix, OR: Bill Pearl Enterprises, 2010.

“Sandow as a Samson.” San Francisco Chronicle, May 23, 1894, p. 13.

Sandow, Eugen, “My Reminiscences,” Strand Magazine, February 1910, pp. 144-152. Available online at
https://archive.org/stream/TheStrandMagazineAnIllustratedMonthly/TheStrandMagazine1910aVol
-XxxixJan-jun#page/n161/mode/2up.

Sandow, Eugen. Strength and How to Obtain It. London: Gale & Polden, 1897. Available online at https://archive
.org/details/strengthandhowt00sandgoog.

Sandow, Eugen, and G. Mercer Adam. Sandow on Physical Training. New York: J. Selwin Tait & Sons, 1894.
Available online at https://archive.org/details/sandowgetsphysicl00sanduoft.
