Julie Andrews was born on October 1, 1935, in a village called - Walton-on-Thames , — in England.

She grew up ina talented family. When she
_ was a little girl, her aunt would help put on show:

at a nearby playhouse. Julie’s mother would play —

piano, and her father built sets.

Julie gave her very first performance at one
of these shows. And she helped a fellow dancer
whose hat had fallen over her eyes. Even at age _
three, Julie knew the show must go on! F


When Julie was four years old, World War ge

began. At that point, Julie was living with her

mother and stepfather in London, where bombs
often fell.

To stay safe, Julie and her brother sometimes
had to go to the countryside and live with
strangers. While there, they loved learning
to ride horses.

Other times, her family hid in the London
Underground train stations with their neighbors.
Her stepfather would play guitar to take people’s

_ minds off the danger.


Meanwhile, Julie was learning to dance and sing.
She went to a special school, where she learned
ballet and tap dance. At age nine, she started taking
singing lessons.

Julie’s mother was a wonderful piano player, and her stepfather was a well-known
singer. They started to invite Julie onstage to sing with them.Julie enjoyed the
spotlight.

Not long after the war finally ended, Julie was
asked to perform for some British soldiers. She
didn’t know that Queen Elizabeth would also be

in the audience! The queen told Julie that she sang
beautifully.


Julie became known for her sweet, high
voice. She spent her teenage years traveling
around England, singing and dancing in
shows. She loved the stage, but she missed
her family when she was away.

Whenever she was homesick, Julie would
go to her dressing room and read. Books
helped her feel less lonely.



When Julie was sixteen years old, she went to
see a musical on the West End of London, where
some of the best plays in the world are performed.

Julie was amazed. The music! The costumes!
The sets! She never thought she would have the
chance to be in a show like that.

But she would—and soon! Just two years
later, Julie was cast as the star in Cinderella on
the West End. There were fancy costumes, a big
moving set, and real ponies on the stage. Julie
and the show got great reviews.

Thanks to the success of Cinderella,
Julie got her next big break—a role in a
Broadway musical, called The Boy Friend. ~~
Julie was going to New York!




Julie was sad to leave, but she couldn’t say no
to Broadway. Her whole family gathered at the
airport to see her off.

While rehearsing in New York, Julie struggled
at first. Sometimes she felt she was doing a good
job, and other times she didn’t. The director told
her to play the role as honestly as she could. On
opening night, the audience gave the show a
standing ovation.


The cast and crew waited overnight at a
nearby restaurant to read the reviews in the
next morning’s newspaper. The critics loved
the show—and Julie. It was official. Julie
Andrews was a Broadway star!


Later that year, a songwriting
duo named Lerner and Loewe were
finishing their newest musical. They

didn’t think Julie would be available
to star in it because most Broadway §

actors had two-year contracts. But
Julie had only wanted a one-year |
contract for her first show so that 7
she could visit her family sooner.

After a quick trip to England, Julie went back
to New York to star in My Fair Lady.

Julie played a flower seller named Eliza
Doolittle who learns to speak like a fancy lady.
Just like Eliza, Julie had to learn to speak in a new
accent. It was very difficult.

Her hard work paid off. My Fair Lady became
the longest-running Broadway musical at the

time, and the cast recording was the number-one
album of 1956.


Julie continued to act and sing in hit
musicals. One day, Walt Disney visited her
backstage after a show. He wanted her to star
in his next movie. Julie had performed on
Broadway, at the famous Carnegie Hall,
and on television—but never in movies.

By then, Julie had gotten married. Not long after
giving birth to her first daughter, Julie and her family
flew to Hollywood, California, so Julie could star in
Walt Disney’s Mary Poppins. Julie won the Academy
Award for Best Actress for her performance as the
magical nanny—and fans everywhere learned the
word “supercalifragilisticexpialidocious.”



In 1965, just one year after Mary Poppins was
released, Julie starred in The Sound of Music. In this
movie musical, Julie played a nun in training named
Maria who falls in love while looking after seven
children in the Austrian mountains. It became one
of her most famous roles, thanks to such songs as
“My Favorite Things” and “Do-Re-Mi.”

Julie spent the next twenty years starring in
movies. She also welcomed four more children
into her life.

One day, Julie’s stepdaughter, Jenny, asked her
to write a story for her. That was when Julie came
up with the idea for her first children’s book. She
would go on to write and publish many more.


Thirty-five years after leaving New York to
make Mary Poppins, Julie finally decided to return
to Broadway. She brought her role from the movie
musical Victor/Victoria to the stage.

Julie worked as hard as ever on this show, and
it was a big success.

Over the years, Julie sometimes found that
her voice got very tired, especially after singing in
a Broadway show for many months in a row. She
had to take long rests, do special exercises, and
occasionally have surgery to help keep her voice
healthy. But at one point, something went wrong.

After her most recent surgery, she found that she
couldn’t sing at all.


Julie was sad—she loved to sing! But although
fifty years had passed since she had read alone
in her dressing room, she knew books could still
bring comfort in a difficult time. With the help
of her daughter Emma, Julie wrote and published

many more children’s books and books about her
own life.

Julie stayed busy. She helped others, spent
time with her family, and kept starring in films.
She played a queen in the Princess Diaries movies
and another queen in the Shrek movies. But she
said it was the greatest honor of her life when
the real queen—Queen Elizabeth II—gave her
a special award honoring her work.


Julie Andrews followed her dreams, going
from her small village to London, New York,
Hollywood, and all over the world. She worked
hard to create unforgettable characters on the
screen, in books, and onstage.

Her many fans will always be
inspired by her talents, and they
will always love Julie Andrews.

== Oprah Winfrey
When Oprah got a little older, she lived
with her mother and younger half siblings in
Milwaukee. They didn’t have much money, and
life there was hard.

One Christmas, some nuns came to her house
and gave her and her family food and toys. The
nuns made Oprah feel special. She decided she
would help others like that someday, too.

Oprah’s high grades helped her become one
of the first Black students to attend a school in
the wealthy part of town. But Oprah soon started
misbehaving. So in high school, Oprah went to
live with her father, Vernon, and her stepmother,
Zelma, in Nashville, Tennessee.


Life was different there. Vernon was strict and
made sure Oprah did well in school. She followed

her dad’s rules, worked hard, and made many
friends.

At seventeen, Oprah won the Miss Fire
Prevention beauty pageant. When she picked up
her prize at a Nashville radio station, a DJ heard
her speak. He knew her voice was special, and he
hired Oprah to read the news as an after-school

job. She loved reading out loud, and now she was
being paid to do it!

-
Oprah was an excellent news anchor, but she
didn’t hide her feelings. Sometimes when a story
was sad, she would cry. Her boss didn’t like that.

But a new boss realized Oprah’s emotions were
a good thing—she could connect with others. He
made her cohost of a talk show called People Are
Talking. Audiences loved Oprah!


Just a few years later, Oprah moved to Illinois
and became the host of her own talk show called
AM Chicago. Again, Oprah was a hit!

One fan was a producer named Quincy Jones.
He asked her to act in his movie The Color
Purple. As a child, Oprah had admired beautiful
Black performers like Sidney Poitier and Diahann
Carroll, so this was a dream! She played the
role of Sofia so well she was nominated for an
Academy Award.

In 1986, The Oprah Winfrey Show, as AM
Chicago was now called, was shown across
America! That same year, Oprah started Harpo
Productions (Harpo is Oprah spelled backward)

and became the first Black woman to own a
TV studio.

Oprah worked hard to make her show great.
She talked with regular people and famous
people. She had fun road trips and awesome rock
concerts. She also shared secrets about herself.
Her show was so popular because Oprah made
everybody feel special.

»”))


----- Text from 10.png -----
Oprah was famous, just as she had dreamed.
But not everyone was nice to her. Sometimes
people made up stories about her past or said
unkind things about how she looked.

Thankfully, Oprah has people she can trust,
including her best friend, Gayle, and her partner,
Stedman Graham.

Oprah’s fans trust her opinion on just about
everything. Oprah loves reading, so she started a
book club. Many of the books she recommends
become bestsellers because so many people want
to read what she’s reading.


Some fans even wanted her to run for
president! Oprah wasn’t interested in that job,
but she spoke highly of someone who was: a

rising politician named Barack Obama.

CHANGE

WE CAN BELIEVE IN

People listened. Obama was elected
president twice.

Oprah’s hard work has earned her a lot of

money, and her big heart has led her to share her

wealth in many ways. Once she gave an entire
audience brand-new cars!


In 2011, after twenty-five years and 4,561
episodes, Oprah ended her beloved talk show.
But she’s still as busy as ever. She continues to
interview celebrities, produce and star in movies,
oversee her media platform Oprah Daily, run

her television network (OWN), and support
numerous charities.

When she’s not working, Oprah enjoys
spending time with her family and friends at
her beautiful homes, taking long walks with her
“fur children” (she’s had more than twenty dogs
S throughout the years!), and curling up with
serenade

a good book.

Oprah never forgot how special she felt when
those nuns helped her family so many years ago.
Now she uses her gifts to help make millions of
other people feel special, too.

Oprah never forgot how special she felt when
those nuns helped her family so many years ago.
Now she uses her gifts to help make millions of


== Jonny Appleseed
a fine September day

more than two hundred

years ago, a boy named. John

J ohnny grew up in Massachusetts,
in a small, crowded house.

He liked to take long walks in the woods, where

it was calm and quiet. He liked to feel the sun on his
face and the earth under his bare feet.

4
When Johnny turned eighteen, he took a very long Settlers were starting to go west in covered
walk—more than four hundred miles! He brought along | wagons, looking for new places to live. Johnny
food, supplies, and a sack of apple seeds. figured they would want apples to eat and press into
Johnny had an idea.

cider. But there were no apple trees out west. Even
if the settlers planted seeds, it would take years for
trees to sprout and grow fruit.

Why not give the
settlers a head start?

Johnny reached Pennsylvania. Near a river, he
found a patch of land with rich soil and plenty of
sunlight. A perfect place for growing apple trees!

He planted some seeds. Then he built a sturdy
fence so that when the new seedlings came up,
deer and rabbits wouldn’t eat them.


Johnny planted more seeds—thousands of them—

Meanwhile, the settlers came. Sure enough, they
across Pennsylvania, Ohio, and Indiana. He worked wanted apples! They were happy to pay Johnny a few
and he walked, going from nursery to nursery to tend
his trees.

cents apiece for seedlings. Sometimes he even gave
them away to families who were
down on their luck.



People spread the word about Johnny and his
apple trees. That’s how he got his nickname.

Have you met Johnny Appleseed? He’s mighty kind,
people said. Mighty peculiar, too!

It was true. For one thing, Johnny looked

strange. He wore old, ragged pants. He cut holes
in coffee sacks to make his shirts.

He still didn’t wear shoes. By now, folks

claimed, his feet were so tough, a snake’s fangs
couldn’t prick them!


... and then cook his dinner in it!

Johnny’s diet was
another thing people
couldn’t get over. He
didn’t like to hurt
animals, so he wouldn’t
eat meat. Not one bite!
He filled up on corn
mush, potatoes, and

- nuts instead.

a pile of leaves.
He didn’t seem to
worry about the bear:



Johnny might have been odd, but he was friendly.
He got along with just about everyone he met.

Native Americans shared their trails with him.
They showed him which berries were safe to eat,

and how to make medicine from leaves and roots.

Settlers invited Johnny into their cabins and asked

him to tell stories. Sometimes he read from the Bible.

“Good news fresh from heaven!” he’d say. Other times,
he acted out his own wild adventures.



People retold Johnny’s tales . . . and made up new
ones, too! As the years went by, the tales grew taller
and taller... .

Once he tricked ten
woodsmen into a chopping
contest. They cleared a
whole acre of land for

Did you know Johnny can thaw ice
with his bare feet?

He has a tame wolf that
follows him around like

a puppy!



The stories wound their way east and west
and back again.

So did Johnny. He traveled hundreds of miles
a year, making new nurseries and tending the ©
old ones.

He kept this up for nearly fifty years!


Johnny was sorely missed. But he was not forgotten—
and neither was his great idea.
As settlers moved farther and farther west, they

carried along apple seeds, just the way Johnny had.
They planted apple trees of their own.

Today, apples grow in every state in America!

The apples that grew on Johnny’s trees
were mostly “‘spitters.” That meant they were

too sour to eat! Settlers used them to make
cider and vinegar.

Johnny’s worn-out clothes made him look
poor, but he wasn’t. When he died, he owned
over a thousand acres of land.

There’s a monument for Johnny in
Indiana, near the spot where he died. The
stone lists both of his names: JOHN CHAPMAN

and JOHNNY APPLESEED. And underneath:
HE LIVED FOR OTHERS.

Johnny probably walked more than a
hundred thousand miles in his lifetime.


== Elton John


Wen Elton John was born on March 25,

1947, he wasn’t Elton John at all. His name

was Reginald Dwight. He lived with his parents,

Sheila and Stanley, in his grandmother's house

in a town called Pinner, near London, England.
Reg was an only child. He often

felt awkward and shy, but one

thing made him light up: music.


Reg’s dad was a trumpet player. His mom
listened to lots of records. Even as a little kid,
Reg could hear a song once and know how to play
it on the piano. He took lessons and practiced.
His piano playing got better and better.

He got so good that the Royal Academy of
Music in London gave him a scholarship when
he was eleven years old. He went there to study
music every Saturday.

Well, almost every Saturday. Sometimes he
skipped out to buy records of his favorite rock
stars. The academy taught him classical music,
but Reg loved rock and roll!


At fifteen, Reg got a steady job playing the
piano at a local pub. Sometimes the rowdy crowd
sang along. Other times, they ignored him.

But Reg didn’t mind. He just kept on singing.

As a teenager, Reg played in a band called
Bluesology. After a few years, he saw an ad in
a newspaper: LIBERTY RECORDS WANTS TALENT.
They were looking for singers and songwriters.
Reg had talent! He could play piano and sing.
He could write melodies. But he wasn’t great at
writing lyrics—the words to the songs.


Reg didn’t get the job.
But a man at the record company handed
him lyrics written by Bernie Taupin, who had

answered the ad, too. Maybe together they could
write something special.

Reg and Bernie hit it off right away.

Reg knew he wanted to make music forever. *
But he didn’t feel cool enough for rock and roll.
And his name didn’t sound like a rock star. He
needed a change.

He borrowed “John” from one friend and

“Elton” from another. Just like that, Reg Dwight
became ELTON JOHN.





Elton and Bernie tried writing music for other
people, but when their quirky songs didn’t sell,
Elton sang them himself. His first album came
out in 1969. Hardly anyone paid attention to it.

Elton and Bernie kept trying. The more songs
they wrote, the better they got. Elton soon
recorded a second album.

That album changed everything.


e record company booked Elton at a
popular club in Los Angeles, California, calle
| the Troubadour. Famous musicians liked to

hang out there. That night, some even cai
hear him play!

though he was nervous, Elton launched int
is music. He stood up, kicked back his stool, an
pounded on the piano keys. He rocked the place.
and the crowd loved it!
After that, sales of the new album went
Iton and Bernie had a hit!


« Elton loved the spotlight, but he felt hidden
behind his piano. Other rock stars could carry
_ their instruments while they moved around the
stage. How could he make himself stand out?
He dressed in flashy clothing. He did
handstands on the keyboard. He sat on the floor
and reached up to play the piano keys. Elton knew
a how to grab a crowd’s attention—and keep it!

Elton and Bernie made hit after hit. Elton went
on tour, putting on shows in cities and countries
all around the world. Radio stations played his
songs. Fans wanted his autograph.

provi!
ROC

In 1973, he got a star on the Hollywood Walk

of Fame. But Elton John wasn’t just a star—he
was a superstar!


Even though he was famous, Elton didn’t take
himself too seriously. He played one concert in

a Donald Duck costume. For another, he sported
a sequined baseball uniform.

He wore hats, feathers, platform boots, and
really big glasses! Nothing was too over the top.

 One song, “Can You Feel t
onight,” won an Academy Award. Late:
movie became a Broadway show.

_ First music, then movies

In 1993, Elton met David Furnish, a filmmaker
from Canada. They fell in love, got married, and

had two kids, Zachary and Elijah. His family made
Elton very happy.


Everywhere he went, Elton made friends. He
danced with Princess Diana and sang with John
Lennon. He—and his music—helped lift people
up when they were sad or lonely.

Through it all, Elton and Bernie continued to
write songs together. Elton said Bernie was the
best friend he ever had.

Elton knew that, thanks to his fame, he could
help a lot of people. He started a charity to
support patients with AIDS, a disease that attacks
the body’s immune system. Every year, he holds
an Oscar party to raise money for the Elton John
AIDS Foundation.

The Queen of England even knighted him in honor of his music and charity work. Today,
he is Sir Elton Hercules John.

More than just his name has changed since
he was that shy, awkward kid. But one thing
has stayed the same: when he plays music,
Elton John lights up!


== Bee Gees
Barry, Maurice, and Robin Gibb made up the pop-
rock band the Bee Gees. They were singers. They
were songwriters. They were disco icons. But most
importantly, they were brothers.

Barry Gibb was born on September 1, 1946. His
younger twin brothers, Maurice and Robin, were born
on December 22, 1949. All three were born on the
Isle of Man, an island between Ireland and England.


The brothers grew up with music all around them.
Their father, Hugh, played the drums and was a
bandleader. Their mother, Barbara, loved to sing. The
Gibb family also included the boys’ older sister, Lesley,
and younger brother, Andy.

When Barry was nine, he was given a guitar as
a gift. Shortly after that, Barry, Maurice, and Robin
started performing around town. The brothers sang in
harmony, which is when singers’ voices blend together.
Back then, they called themselves the Rattlesnakes.

The brothers were certain that one day, they would
become famous.



In 1958, the family took a boat from England to In Australia, they played to crowds at a local racetrack,
Australia to start a new life. The brothers entertained catching the attention of first a race car driver and then
the other passengers on the long journey. a DJ. Both had the same initials as Barry. Because of that

coincidence, they renamed their group the BGs. Soon
after, their name officially became the Bee Gees.


Nine years later, the brothers decided to return to
England to chase their musical dreams. It was 1967,
and the London music scene was hopping. Everyone
loved a group called the Beatles. The Bee Gees hoped
people would love their music, too.


The Bee Gees got to work writing and recording.
They were inspired by legendary Black musicians such
as Smokey Robinson and Otis Redding, who played
blues and Motown music. The brothers worked those
musical styles into their own songs.

Their first big single was called “New York Mining
Disaster 1941.” The brothers wrote this song in a
stairwell during a power outage!

It was soon followed by two more hits, “To Love
Somebody” and “Massachusetts.” The band’s first

number one song in America, “How Can You Mend
a Broken Heart,” was released a few years later.


The brothers needed to do something different

to keep their fans interested. They went to Miami,
Florida, to record their next album. Being in a new

place inspired their new sound.

The band was doing great! But people’s taste
in music was changing.




In the Miami recording studio, Barry sang falsetto—
which made his voice sound higher—and the band
used synthesizers to create a more electronic tone.

The biggest hit from their new album was “Jive
Talkin’ .” It quickly boogied its way up to number one
on the music charts. The Bee Gees were back on
With these changes, the Bee Gees’ new disco sound top, and disco fever took over the world!
was born!


The Bee Gees’ producer requested some new songs
for a movie he was working on. Little did they know,
this movie would make the band more popular than
ever. Saturday Night Fever premiered in 1977. One of

the band’s most famous songs, “Stayin’ Alive,” played
during the very first scene.

The Saturday Night Fever soundtrack didn’t just
have one hit written by the Bee Gees—it had seven!
The album sold forty million copies and won four

Grammy Awards. Disco was played in clubs around the
world, and everyone danced to the Bee Gees’ music.



The Bee Gees had hits in the 1960s, 1970s, 1980s,
and 1990s! And with each decade, their style changed.
Their hair was short, long, and shaggy. Their music was
slow and fast. They sang low. They sang high. They sang
together. And they wore everything from blazers to bell-
bottom pants to sequined shirts.


But the one thing that never changed was their love
of making music. When disco stopped being popular,
the brothers wrote songs for other performers, including
Barbra Streisand, Kenny Rogers, Dolly Parton, and

Dionne Warwick. |


When Maurice passed away in 2003 and then Robin in
2012, Barry was left without his brothers. After thinking
about their time together and their epic careers, Barry
decided to make music again. He rerecorded some of the

Bee Gees’ classic songs with the help of famous country
music stars like Keith Urban.

After making music for more than forty years, the

Bee Gees were inducted into the Rock and Roll Hall of
Fame in 1997.


The Gibb brothers wrote over one thousand songs

and had countless number one hits. Their harmonies are
world famous, their lyrics tell stories, and their beats make
people want to shimmy and sway. Their music continues

to influence artists today.


The Bee Gees’ sound is still stayin’ alive!

