Julie Andrews was born on October 1, 1935, in a village called - Walton-on-Thames , — in England.

She grew up ina talented family. When she
_ was a little girl, her aunt would help put on show:

at a nearby playhouse. Julie’s mother would play —

piano, and her father built sets.

Julie gave her very first performance at one
of these shows. And she helped a fellow dancer
whose hat had fallen over her eyes. Even at age _
three, Julie knew the show must go on! F


When Julie was four years old, World War ge

began. At that point, Julie was living with her

mother and stepfather in London, where bombs
often fell.

To stay safe, Julie and her brother sometimes
had to go to the countryside and live with
strangers. While there, they loved learning
to ride horses.

Other times, her family hid in the London
Underground train stations with their neighbors.
Her stepfather would play guitar to take people’s

_ minds off the danger.


Meanwhile, Julie was learning to dance and sing.
She went to a special school, where she learned
ballet and tap dance. At age nine, she started taking
singing lessons.

Julie’s mother was a wonderful piano player, and her stepfather was a well-known
singer. They started to invite Julie onstage to sing with them.Julie enjoyed the
spotlight.

Not long after the war finally ended, Julie was
asked to perform for some British soldiers. She
didn’t know that Queen Elizabeth would also be

in the audience! The queen told Julie that she sang
beautifully.


Julie became known for her sweet, high
voice. She spent her teenage years traveling
around England, singing and dancing in
shows. She loved the stage, but she missed
her family when she was away.

Whenever she was homesick, Julie would
go to her dressing room and read. Books
helped her feel less lonely.



When Julie was sixteen years old, she went to
see a musical on the West End of London, where
some of the best plays in the world are performed.

Julie was amazed. The music! The costumes!
The sets! She never thought she would have the
chance to be in a show like that.

But she would—and soon! Just two years
later, Julie was cast as the star in Cinderella on
the West End. There were fancy costumes, a big
moving set, and real ponies on the stage. Julie
and the show got great reviews.

Thanks to the success of Cinderella,
Julie got her next big break—a role in a
Broadway musical, called The Boy Friend. ~~
Julie was going to New York!




Julie was sad to leave, but she couldn’t say no
to Broadway. Her whole family gathered at the
airport to see her off.

While rehearsing in New York, Julie struggled
at first. Sometimes she felt she was doing a good
job, and other times she didn’t. The director told
her to play the role as honestly as she could. On
opening night, the audience gave the show a
standing ovation.


The cast and crew waited overnight at a
nearby restaurant to read the reviews in the
next morning’s newspaper. The critics loved
the show—and Julie. It was official. Julie
Andrews was a Broadway star!


Later that year, a songwriting
duo named Lerner and Loewe were
finishing their newest musical. They

didn’t think Julie would be available
to star in it because most Broadway §

actors had two-year contracts. But
Julie had only wanted a one-year |
contract for her first show so that 7
she could visit her family sooner.

After a quick trip to England, Julie went back
to New York to star in My Fair Lady.

Julie played a flower seller named Eliza
Doolittle who learns to speak like a fancy lady.
Just like Eliza, Julie had to learn to speak in a new
accent. It was very difficult.

Her hard work paid off. My Fair Lady became
the longest-running Broadway musical at the

time, and the cast recording was the number-one
album of 1956.


Julie continued to act and sing in hit
musicals. One day, Walt Disney visited her
backstage after a show. He wanted her to star
in his next movie. Julie had performed on
Broadway, at the famous Carnegie Hall,
and on television—but never in movies.

By then, Julie had gotten married. Not long after
giving birth to her first daughter, Julie and her family
flew to Hollywood, California, so Julie could star in
Walt Disney’s Mary Poppins. Julie won the Academy
Award for Best Actress for her performance as the
magical nanny—and fans everywhere learned the
word “supercalifragilisticexpialidocious.”



In 1965, just one year after Mary Poppins was
released, Julie starred in The Sound of Music. In this
movie musical, Julie played a nun in training named
Maria who falls in love while looking after seven
children in the Austrian mountains. It became one
of her most famous roles, thanks to such songs as
“My Favorite Things” and “Do-Re-Mi.”

Julie spent the next twenty years starring in
movies. She also welcomed four more children
into her life.

One day, Julie’s stepdaughter, Jenny, asked her
to write a story for her. That was when Julie came
up with the idea for her first children’s book. She
would go on to write and publish many more.


Thirty-five years after leaving New York to
make Mary Poppins, Julie finally decided to return
to Broadway. She brought her role from the movie
musical Victor/Victoria to the stage.

Julie worked as hard as ever on this show, and
it was a big success.

Over the years, Julie sometimes found that
her voice got very tired, especially after singing in
a Broadway show for many months in a row. She
had to take long rests, do special exercises, and
occasionally have surgery to help keep her voice
healthy. But at one point, something went wrong.

After her most recent surgery, she found that she
couldn’t sing at all.


Julie was sad—she loved to sing! But although
fifty years had passed since she had read alone
in her dressing room, she knew books could still
bring comfort in a difficult time. With the help
of her daughter Emma, Julie wrote and published

many more children’s books and books about her
own life.

Julie stayed busy. She helped others, spent
time with her family, and kept starring in films.
She played a queen in the Princess Diaries movies
and another queen in the Shrek movies. But she
said it was the greatest honor of her life when
the real queen—Queen Elizabeth II—gave her
a special award honoring her work.


Julie Andrews followed her dreams, going
from her small village to London, New York,
Hollywood, and all over the world. She worked
hard to create unforgettable characters on the
screen, in books, and onstage.

Her many fans will always be
inspired by her talents, and they
will always love Julie Andrews.

== Oprah Winfrey
When Oprah got a little older, she lived
with her mother and younger half siblings in
Milwaukee. They didn’t have much money, and
life there was hard.

One Christmas, some nuns came to her house
and gave her and her family food and toys. The
nuns made Oprah feel special. She decided she
would help others like that someday, too.

Oprah’s high grades helped her become one
of the first Black students to attend a school in
the wealthy part of town. But Oprah soon started
misbehaving. So in high school, Oprah went to
live with her father, Vernon, and her stepmother,
Zelma, in Nashville, Tennessee.


Life was different there. Vernon was strict and
made sure Oprah did well in school. She followed

her dad’s rules, worked hard, and made many
friends.

At seventeen, Oprah won the Miss Fire
Prevention beauty pageant. When she picked up
her prize at a Nashville radio station, a DJ heard
her speak. He knew her voice was special, and he
hired Oprah to read the news as an after-school

job. She loved reading out loud, and now she was
being paid to do it!

-
Oprah was an excellent news anchor, but she
didn’t hide her feelings. Sometimes when a story
was sad, she would cry. Her boss didn’t like that.

But a new boss realized Oprah’s emotions were
a good thing—she could connect with others. He
made her cohost of a talk show called People Are
Talking. Audiences loved Oprah!


Just a few years later, Oprah moved to Illinois
and became the host of her own talk show called
AM Chicago. Again, Oprah was a hit!

One fan was a producer named Quincy Jones.
He asked her to act in his movie The Color
Purple. As a child, Oprah had admired beautiful
Black performers like Sidney Poitier and Diahann
Carroll, so this was a dream! She played the
role of Sofia so well she was nominated for an
Academy Award.

In 1986, The Oprah Winfrey Show, as AM
Chicago was now called, was shown across
America! That same year, Oprah started Harpo
Productions (Harpo is Oprah spelled backward)

and became the first Black woman to own a
TV studio.

Oprah worked hard to make her show great.
She talked with regular people and famous
people. She had fun road trips and awesome rock
concerts. She also shared secrets about herself.
Her show was so popular because Oprah made
everybody feel special.

»”))


----- Text from 10.png -----
Oprah was famous, just as she had dreamed.
But not everyone was nice to her. Sometimes
people made up stories about her past or said
unkind things about how she looked.

Thankfully, Oprah has people she can trust,
including her best friend, Gayle, and her partner,
Stedman Graham.

Oprah’s fans trust her opinion on just about
everything. Oprah loves reading, so she started a
book club. Many of the books she recommends
become bestsellers because so many people want
to read what she’s reading.


Some fans even wanted her to run for
president! Oprah wasn’t interested in that job,
but she spoke highly of someone who was: a

rising politician named Barack Obama.

CHANGE

WE CAN BELIEVE IN

People listened. Obama was elected
president twice.

Oprah’s hard work has earned her a lot of

money, and her big heart has led her to share her

wealth in many ways. Once she gave an entire
audience brand-new cars!


In 2011, after twenty-five years and 4,561
episodes, Oprah ended her beloved talk show.
But she’s still as busy as ever. She continues to
interview celebrities, produce and star in movies,
oversee her media platform Oprah Daily, run

her television network (OWN), and support
numerous charities.

When she’s not working, Oprah enjoys
spending time with her family and friends at
her beautiful homes, taking long walks with her
“fur children” (she’s had more than twenty dogs
S throughout the years!), and curling up with
serenade

a good book.

Oprah never forgot how special she felt when
those nuns helped her family so many years ago.
Now she uses her gifts to help make millions of
other people feel special, too.

Oprah never forgot how special she felt when
those nuns helped her family so many years ago.
Now she uses her gifts to help make millions of


== Jonny Appleseed
a fine September day

more than two hundred

years ago, a boy named. John

J ohnny grew up in Massachusetts,
in a small, crowded house.

He liked to take long walks in the woods, where

it was calm and quiet. He liked to feel the sun on his
face and the earth under his bare feet.

4
When Johnny turned eighteen, he took a very long Settlers were starting to go west in covered
walk—more than four hundred miles! He brought along | wagons, looking for new places to live. Johnny
food, supplies, and a sack of apple seeds. figured they would want apples to eat and press into
Johnny had an idea.

cider. But there were no apple trees out west. Even
if the settlers planted seeds, it would take years for
trees to sprout and grow fruit.

Why not give the
settlers a head start?

Johnny reached Pennsylvania. Near a river, he
found a patch of land with rich soil and plenty of
sunlight. A perfect place for growing apple trees!

He planted some seeds. Then he built a sturdy
fence so that when the new seedlings came up,
deer and rabbits wouldn’t eat them.


Johnny planted more seeds—thousands of them—

Meanwhile, the settlers came. Sure enough, they
across Pennsylvania, Ohio, and Indiana. He worked wanted apples! They were happy to pay Johnny a few
and he walked, going from nursery to nursery to tend
his trees.

cents apiece for seedlings. Sometimes he even gave
them away to families who were
down on their luck.



People spread the word about Johnny and his
apple trees. That’s how he got his nickname.

Have you met Johnny Appleseed? He’s mighty kind,
people said. Mighty peculiar, too!

It was true. For one thing, Johnny looked

strange. He wore old, ragged pants. He cut holes
in coffee sacks to make his shirts.

He still didn’t wear shoes. By now, folks

claimed, his feet were so tough, a snake’s fangs
couldn’t prick them!


... and then cook his dinner in it!

Johnny’s diet was
another thing people
couldn’t get over. He
didn’t like to hurt
animals, so he wouldn’t
eat meat. Not one bite!
He filled up on corn
mush, potatoes, and

- nuts instead.

a pile of leaves.
He didn’t seem to
worry about the bear:



Johnny might have been odd, but he was friendly.
He got along with just about everyone he met.

Native Americans shared their trails with him.
They showed him which berries were safe to eat,

and how to make medicine from leaves and roots.

Settlers invited Johnny into their cabins and asked

him to tell stories. Sometimes he read from the Bible.

“Good news fresh from heaven!” he’d say. Other times,
he acted out his own wild adventures.



People retold Johnny’s tales . . . and made up new
ones, too! As the years went by, the tales grew taller
and taller... .

Once he tricked ten
woodsmen into a chopping
contest. They cleared a
whole acre of land for

Did you know Johnny can thaw ice
with his bare feet?

He has a tame wolf that
follows him around like

a puppy!



The stories wound their way east and west
and back again.

So did Johnny. He traveled hundreds of miles
a year, making new nurseries and tending the ©
old ones.

He kept this up for nearly fifty years!


Johnny was sorely missed. But he was not forgotten—
and neither was his great idea.
As settlers moved farther and farther west, they

carried along apple seeds, just the way Johnny had.
They planted apple trees of their own.

Today, apples grow in every state in America!

The apples that grew on Johnny’s trees
were mostly “‘spitters.” That meant they were

too sour to eat! Settlers used them to make
cider and vinegar.

Johnny’s worn-out clothes made him look
poor, but he wasn’t. When he died, he owned
over a thousand acres of land.

There’s a monument for Johnny in
Indiana, near the spot where he died. The
stone lists both of his names: JOHN CHAPMAN

and JOHNNY APPLESEED. And underneath:
HE LIVED FOR OTHERS.

Johnny probably walked more than a
hundred thousand miles in his lifetime.


== Elton John


Wen Elton John was born on March 25,

1947, he wasn’t Elton John at all. His name

was Reginald Dwight. He lived with his parents,

Sheila and Stanley, in his grandmother's house

in a town called Pinner, near London, England.
Reg was an only child. He often

felt awkward and shy, but one

thing made him light up: music.


Reg’s dad was a trumpet player. His mom
listened to lots of records. Even as a little kid,
Reg could hear a song once and know how to play
it on the piano. He took lessons and practiced.
His piano playing got better and better.

He got so good that the Royal Academy of
Music in London gave him a scholarship when
he was eleven years old. He went there to study
music every Saturday.

Well, almost every Saturday. Sometimes he
skipped out to buy records of his favorite rock
stars. The academy taught him classical music,
but Reg loved rock and roll!


At fifteen, Reg got a steady job playing the
piano at a local pub. Sometimes the rowdy crowd
sang along. Other times, they ignored him.

But Reg didn’t mind. He just kept on singing.

As a teenager, Reg played in a band called
Bluesology. After a few years, he saw an ad in
a newspaper: LIBERTY RECORDS WANTS TALENT.
They were looking for singers and songwriters.
Reg had talent! He could play piano and sing.
He could write melodies. But he wasn’t great at
writing lyrics—the words to the songs.


Reg didn’t get the job.
But a man at the record company handed
him lyrics written by Bernie Taupin, who had

answered the ad, too. Maybe together they could
write something special.

Reg and Bernie hit it off right away.

Reg knew he wanted to make music forever. *
But he didn’t feel cool enough for rock and roll.
And his name didn’t sound like a rock star. He
needed a change.

He borrowed “John” from one friend and

“Elton” from another. Just like that, Reg Dwight
became ELTON JOHN.





Elton and Bernie tried writing music for other
people, but when their quirky songs didn’t sell,
Elton sang them himself. His first album came
out in 1969. Hardly anyone paid attention to it.

Elton and Bernie kept trying. The more songs
they wrote, the better they got. Elton soon
recorded a second album.

That album changed everything.


e record company booked Elton at a
popular club in Los Angeles, California, calle
| the Troubadour. Famous musicians liked to

hang out there. That night, some even cai
hear him play!

though he was nervous, Elton launched int
is music. He stood up, kicked back his stool, an
pounded on the piano keys. He rocked the place.
and the crowd loved it!
After that, sales of the new album went
Iton and Bernie had a hit!


« Elton loved the spotlight, but he felt hidden
behind his piano. Other rock stars could carry
_ their instruments while they moved around the
stage. How could he make himself stand out?
He dressed in flashy clothing. He did
handstands on the keyboard. He sat on the floor
and reached up to play the piano keys. Elton knew
a how to grab a crowd’s attention—and keep it!

Elton and Bernie made hit after hit. Elton went
on tour, putting on shows in cities and countries
all around the world. Radio stations played his
songs. Fans wanted his autograph.

provi!
ROC

In 1973, he got a star on the Hollywood Walk

of Fame. But Elton John wasn’t just a star—he
was a superstar!


Even though he was famous, Elton didn’t take
himself too seriously. He played one concert in

a Donald Duck costume. For another, he sported
a sequined baseball uniform.

He wore hats, feathers, platform boots, and
really big glasses! Nothing was too over the top.

 One song, “Can You Feel t
onight,” won an Academy Award. Late:
movie became a Broadway show.

_ First music, then movies

In 1993, Elton met David Furnish, a filmmaker
from Canada. They fell in love, got married, and

had two kids, Zachary and Elijah. His family made
Elton very happy.


Everywhere he went, Elton made friends. He
danced with Princess Diana and sang with John
Lennon. He—and his music—helped lift people
up when they were sad or lonely.

Through it all, Elton and Bernie continued to
write songs together. Elton said Bernie was the
best friend he ever had.

Elton knew that, thanks to his fame, he could
help a lot of people. He started a charity to
support patients with AIDS, a disease that attacks
the body’s immune system. Every year, he holds
an Oscar party to raise money for the Elton John
AIDS Foundation.

The Queen of England even knighted him in honor of his music and charity work. Today,
he is Sir Elton Hercules John.

More than just his name has changed since
he was that shy, awkward kid. But one thing
has stayed the same: when he plays music,
Elton John lights up!


== Bee Gees
Barry, Maurice, and Robin Gibb made up the pop-
rock band the Bee Gees. They were singers. They
were songwriters. They were disco icons. But most
importantly, they were brothers.

Barry Gibb was born on September 1, 1946. His
younger twin brothers, Maurice and Robin, were born
on December 22, 1949. All three were born on the
Isle of Man, an island between Ireland and England.


The brothers grew up with music all around them.
Their father, Hugh, played the drums and was a
bandleader. Their mother, Barbara, loved to sing. The
Gibb family also included the boys’ older sister, Lesley,
and younger brother, Andy.

When Barry was nine, he was given a guitar as
a gift. Shortly after that, Barry, Maurice, and Robin
started performing around town. The brothers sang in
harmony, which is when singers’ voices blend together.
Back then, they called themselves the Rattlesnakes.

The brothers were certain that one day, they would
become famous.




In 1958, the family took a boat from England to In Australia, they played to crowds at a local racetrack,
Australia to start a new life. The brothers entertained catching the attention of first a race car driver and then
the other passengers on the long journey. a DJ. Both had the same initials as Barry. Because of that

coincidence, they renamed their group the BGs. Soon
after, their name officially became the Bee Gees.


Nine years later, the brothers decided to return to
England to chase their musical dreams. It was 1967,
and the London music scene was hopping. Everyone
loved a group called the Beatles. The Bee Gees hoped
people would love their music, too.


The Bee Gees got to work writing and recording.
They were inspired by legendary Black musicians such
as Smokey Robinson and Otis Redding, who played
blues and Motown music. The brothers worked those
musical styles into their own songs.

Their first big single was called “New York Mining
Disaster 1941.” The brothers wrote this song in a
stairwell during a power outage!

It was soon followed by two more hits, “To Love
Somebody” and “Massachusetts.” The band’s first

number one song in America, “How Can You Mend
a Broken Heart,” was released a few years later.


The brothers needed to do something different

to keep their fans interested. They went to Miami,
Florida, to record their next album. Being in a new

place inspired their new sound.

The band was doing great! But people’s taste
in music was changing.




In the Miami recording studio, Barry sang falsetto—
which made his voice sound higher—and the band
used synthesizers to create a more electronic tone.

The biggest hit from their new album was “Jive
Talkin’ .” It quickly boogied its way up to number one
on the music charts. The Bee Gees were back on
With these changes, the Bee Gees’ new disco sound top, and disco fever took over the world!
was born!


The Bee Gees’ producer requested some new songs
for a movie he was working on. Little did they know,
this movie would make the band more popular than
ever. Saturday Night Fever premiered in 1977. One of

the band’s most famous songs, “Stayin’ Alive,” played
during the very first scene.

The Saturday Night Fever soundtrack didn’t just
have one hit written by the Bee Gees—it had seven!
The album sold forty million copies and won four

Grammy Awards. Disco was played in clubs around the
world, and everyone danced to the Bee Gees’ music.



The Bee Gees had hits in the 1960s, 1970s, 1980s,
and 1990s! And with each decade, their style changed.
Their hair was short, long, and shaggy. Their music was
slow and fast. They sang low. They sang high. They sang
together. And they wore everything from blazers to bell-
bottom pants to sequined shirts.


But the one thing that never changed was their love
of making music. When disco stopped being popular,
the brothers wrote songs for other performers, including
Barbra Streisand, Kenny Rogers, Dolly Parton, and

Dionne Warwick. |


When Maurice passed away in 2003 and then Robin in
2012, Barry was left without his brothers. After thinking
about their time together and their epic careers, Barry
decided to make music again. He rerecorded some of the

Bee Gees’ classic songs with the help of famous country
music stars like Keith Urban.

After making music for more than forty years, the

Bee Gees were inducted into the Rock and Roll Hall of
Fame in 1997.


The Gibb brothers wrote over one thousand songs

and had countless number one hits. Their harmonies are
world famous, their lyrics tell stories, and their beats make
people want to shimmy and sway. Their music continues

to influence artists today.


The Bee Gees’ sound is still stayin’ alive!

== Dr. JONAS SALK
JONAS SALK WAS
A DOCTOR, WHO
SAVED MANY LIVES
BY CREATING
A VACCINE FOR, POLIO.

Jonas was born on October 28, 1914. He
and his younger brothers grew up near a
grassy park in the Bronx, in New York City.
The Salk family was Jewish. Jews were
treated harshly in many countries. Jonas’s
mother, Dora, escaped Russia when she was

thirteen. His father, Daniel, was also from an
immigrant family. Daniel and Dora hoped to
give their three sons a better life.


In 1918, when Jonas was four, he watched
wounded soldiers march in a parade to mark
the end of World War I.

That year, millions of people got sick from
influenza, or the flu. Many soldiers caught it. So
did families who crowded the streets to see parades.

curious from
Jonas was a quiet boy. He liked to spend time alone,

the earliest
reading and wondering about the world. He felt sad %
when he saw people suffering or in pain. age Ov


The flu was just one disease people worried
about. Jonas sometimes saw children his own

age wearing leg braces to help them walk. They’d
gotten a disease called polio.

Since polio spreads easily from person to person,
public swimming pools were closed to keep children

safe. Even in summer, kids couldn’t go outside to
play. Everyone felt afraid.

Polio is caused by the polio virus, a tiny germ. It can

damage nerves in the spine and cause problems with
moving and even breathing.

When Jonas was a boy, future president Franklin D.
Roosevelt got polio and lost his ability to walk. Still,
Roosevelt would go on to do great things.

And so would Jonas!

ere
Jonas
school when he was fifteen.
He became the first in his
family to go to college. The
City College of New York
was free, so Jonas only had
to pay for his books and
the fare for the streetcar.

Jonas fell in love with chemistry and medicine.
He decided to become a doctor to help others.


In medical school, Jonas asked lots of questions.
This helped him solve problems in the laboratory. He

liked performing experiments and became fascinated
by viruses.

On June 8, 1939, Jonas graduated from New York
University Medical School. He was now a doctor.

The next day, Jonas became a husband, too.
During their marriage, Jonas and his wife, Donna,
had three children: Peter, Darrell, and Jonathan.
They all grew up to become doctors, like their dad

Long before that, Jonas’s boys would help him
make medical history.

Jonas was brilliant. But it wasn’t easy for

The world was at war again. Jonas remembered
a young Jewish doctor who hadn’t gone to fancy the soldiers on parade and the crowds he’d seen
schools to find a job. However, in 1942, Jonas went when he was little. Jonas and Dr. Francis wanted to
to work for a scientist who'd once been his teacher: prevent another terrible flu outbreak. They went to
Dr. Thomas Francis Jr.

work finding a new way to make a safe vaccine for
influenza. And in 1943, they did just that!


After the war, Jonas started the Virus Research
Laboratory at the University of Pittsburgh. Soon he

was presented with his greatest challenge: to make
a vaccine to fight polio.

Vaccines tell our bodies to make special proteins
alled antibodies to fight off diseases. Vaccines help
us stay healthy.


People had been hoping for a polio vaccine for

a long time. By the early 1950s, there were as many
as 50,000 new cases of polio each year.


Jonas wanted to give people hope, too. He often
visited children with polio in the hospital wards near

his lab. Some could only breathe with the help of a big
machine called an iron lung.


When Jonas saw how much polio victims suffered,
he worked even harder to create a safe vaccine.

He used a recently discovered way to grow the
polio virus in his lab, and then he killed the virus so
it couldn’t make anyone sick. No one else was making
vaccines in this way. But Jonas felt sure that if he used

the killed virus as a vaccine, it would keep people from
getting polio.

The process wasn’t easy. Jonas and his team of
scientists worked hard for many long months. At last,
one night in 1953, Jonas brought something home
from the lab: his new vaccine!

Peter, Darrell, and Jonathan got their shots early in
the testing program—and right in their own kitchen.
Peter said it didn’t even hurt. Of course, their parents
got vaccinated, too.

Jonas felt sure he’d found the best way to prevent
polio. However, to prove that the vaccine was safe
and effective, he needed to test it on many others.

He needed polio pioneers!

Jonas had no interest in making money from
the vaccine. When he was asked who owned it,
he replied, “Well, the people, I would say.”

tt ase is

The people of America
_- were ready. Almost two
: million children took part

in a nationwide test of the

polio vaccine. : NX
On April 12, 1955, : ee
the test results were —

announced: the Salk


safe and effective!


nearly disappeared from the United States and
many other countries.

As long as everyone stays vaccinated, children
just like you can run and play without fear of getting
the disease. If we each do our part, we can save lives"
and help make polio disappear everywhere. aie


Jonas Salk became famous and was beloved by
everyone in America. He spent his whole life working
to help others.

Jonas died in 1995 at age eighty. But his dreams live
on at the Salk Institute for Biological Studies, where
researchers seek new cures to benefit us all.

Just like Jonas, they strive to make hopes come true.


== Strong as Sandow
Eugen Sandow was known as “the Strongest Man

on Earth.” He could break metal chains by expanding his
broad chest. He could hoist a grand piano over his head.
He boasted that he once wrestled a five-hundred-pound lion.
No doubt Eugen Sandow was the strongest of all strongmen.
But he wasn’t always strong.


The Delicate Days
K6nigsberg, Prussia, 1867-1885?

His birth name was Friedrich Wilhelm Miller. As a boy, he loved
athletics. But playing sports required a strong, healthy body.
Friedrich’s arms were skinny, and his legs were as frail as twigs.
He looked downright feeble. Often, he was too sick to play.

Friedrich was awestruck by the statues of ancient athletes.
Their muscles looked so powerful. If only he could look like a
Roman gladiator!

“How is it that these men were so strong, Father?”
Friedrich asked.

“The heroes of old,” his father said, “were ever active, ever
exercising their bodies.”

But Friedrich survived. His spirit was strong. He played sports,
and he excelled in school. As a reward for his high honors, his
father took him on a trip to Italy. They visited the famous art
galleries of Rome.



Exercise—that was it! To make his body stronger, Friedrich
would need to push himself even harder. When he returned
home, he ran longer and jumped higher. He exercised like
never before.

But his ten-year-old body wasn’t ready to bloom just yet.

To Friedrich’s despair, it remained weak and puny.


but he longed to do something more

physically active.

Strong and Stronger : am
Prussia to Belgium, 1885?-1887 =r
One day a traveling circus rolled into town. Friedrich snuck away
from school to watch. He was starstruck by the performers—
tumblers, wrestlers, acrobats, strongmen. The lure was simply too
much to resist. Friedrich left the university and joined the circus.
He became an acrobat.

Life as an acrobat was physically demanding. Friedrich tumbled
and bent and balanced. He flipped and flopped and stood on his

hands. Soon he began to notice a change in his body: his muscles
were getting bigger and stronger.

But the circus turned out to be a ragtag operation. It ran out of
money, and Friedrich lost the job he so adored.

To support himself, Friedrich found work as a model for art
students. His burly, ever-growing physique was the perfect
reference for their paintings and sculptures. Through their art,

Friedrich became the gladiator he had dreamed of being as a child.

One of the artists introduced Friedrich to Professor Attila,
a professional strongman. The Professor gave Friedrich a job at
his gym and offered to teach him bodybuilding.

“Attend to my instructions,” the Professor said, “and I shall
be able to make you the strongest man in the world.”

The Professor made Friedrich lift heavier weights. The metal
barbells were so heavy, Friedrich’s muscles quivered. But he didn’t
complain. The heavier the weights, the bigger his muscles grew.


Friedrich’s knowledge about the strongman business grew, too.
He learned about showmanship, costumes, and stage presence.

By the time he was twenty years old, Friedrich was a bona fide
professional strongman. He even changed his name. Friedrich
Miiller would be known forever after as Eugen Sandow.


The Big Challenge
London, 1889

Sampson and Cyclops were the greatest professional strongmen
of their time. They were brawny. They were brutes. They were

loudmouthed, muscle-bound lunks! Sampson and Cyclops lifted
horses and elephants as though they were as light as feathers.
Each night after their act in London, they roared out a
challenge to the audience: they dared anyone to try to defeat
them in a competition of strength. But who would accept such a
foolish challenge?
Eugen Sandow, that’s who.


Eugen jumped onstage. Dressed in a fine suit, he sauntered along
confidently—until he tripped over a barbell and almost fell on his
face. Everyone laughed—Sampson and Cyclops hardest of all.

But Eugen had a plan. With one swoop of his powerful arm, he
ripped off his suit, all at once. The audience gasped at the sight of

his mighty muscles.

The competition began. Sampson and Cyclops jerked pound
after pound of incredibly heavy weights above their heads. But
each time, Eugen effortlessly met their challenge. Sometimes
he lifted more. Sampson raged. Cyclops fumed. At last Eugen.
was declared the winner.


Victory and Beyond

London to America, 1890-1894

Victory over the great Sampson and Cyclops made Eugen famous.

He performed in music halls all over England, Scotland, and
Ireland. It wasn’t long before fame beckoned him overseas to the
United States.

First he performed at a casino in New York City. Then at a
theater in Boston. His popularity exploded when he performed at
the Chicago World’s Fair. Crowds poured into the theater to see
“the Modern Hercules.”


When the curtain rose, Eugen appeared onstage. He was dusted
head-to-toe with white powder, which made him look like a living,
breathing marble statue. When he lifted a heavy barbell over his
head, ‘some people in the audience gasped. Others fainted.

Truth be told, though, no one really cared about how much
weight Eugen could lift. They were in awe of his physique. His
chiseled muscles were things of beauty, like fine works of art.

After the show in Chicago, Eugen became one of the
most famous stars in America.


As Eugen went on to tell it, his greatest moment happened
one evening in San Francisco. “The Event of the Century”
packed hordes of spectators into a huge, circus-like tent.
Inside, a massive lion roared and people shrieked. But Eugen
was all confidence and smiles, ]


When Eugen entered the cage and flexed his hefty muscles,
the king of the beasts cowered down, tame as a kitty. Eugen
scooped up the lion and paraded him around the stage.

The lion wore mittens, and some people thought he looked
drugged. Was it all a trick? A showman’s illusion? Eugen Sandow
would never let on.

The so-called fight lasted just a few minutes, and the
strongman was declared the winner.

Home
America to London, 1898-1901

Eugen continued to travel. But over time the grueling schedule
proved too much even for him. He became tired and sickly.

He lost weight. His once powerful muscles seemed to fade away.
His body needed rest, and so did his mind.

Eugen said good-bye to America and returned home to Britain.

For months Eugen rested. While his body recovered, his brain

searched for ways to continue his career. He opened a gym. He
published books and magazines promoting bodybuilding and
nutritious eating. He designed his own equipment and techniques
for strengthening muscles. 31



In 1901 Eugen launched the Great Competition—the first
organized bodybuilding contest. Strongmen traveled from all
over the country to compete at the Royal Albert Hall in London.

But Eugen wasn’t interested in rewarding only big, muscular
physiques. He considered a man’s overall health and physical
development, too.

First the men performed athletic displays—wrestling,
gymnastics, even fencing. Then, after several rounds of posing,
a winner was chosen. He received a cash prize and a gold-plated
statue of none other than Eugen Sandow himself.




=

On the night of the Great Competition, Eugen Sandow
performed, too. He must have flexed a smile as broad as his
biceps. After all, the once-frail child was now known as “the
Strongest Man on Earth.” And it seemed that every man on
earth—and every woman and child, too—was now devoting
more attention to their own health. Everyone wanted to

34 become “as strong as Sandow.”


Afterword

David Beckham, LeBron James, and Justin Bieber are modern-day male superstars.
During the Victorian era (1837-1901), Eugen Sandow was that star. From England to
the United States and beyond, people flocked to see the strongman flex his muscles.

Deemed “the most perfect male specimen alive” by doctors of his time, Sandow
was often photographed in the buff, wearing only a fig leaf and high-laced sandals.
It was an image that harkened back to the Greek and Roman statues he had so
admired as a child. Sandow even measured the proportions of those statues in order
to develop his own body to more closely resemble them.

But while Sandow was fixated on looks, he was also passionate about helping
others to develop healthier minds and bodies. For children, he advocated a national
physical-fitness program in schools. For men, women, and children throughout
England, he established schools of physical culture. For everyone around the world,
he produced home exercise equipment and dietary supplements. His book Strength
and How to Obtain It became a best-seller, and his magazine, Sandow’s Magazine of
Physical Culture, was a forerunner to publications such as Flex and Men’s Health.

Sandow’s exercises and diet regimens are still in use today, as is the muscled
statuette that bears his name: the Sandow. For years, bodybuilding’s ultimate prize
was a sculpture of a nude, fig-leaf-adorned Sandow
clutching a barbell. The original was awarded at the 1901
Great Competition. Today the statuette is the top prize in
the Mr. Olympia bodybuilding competition. (For better
or for worse, the statuette was recently updated: the
Sandow is now beefier, and he’s lost the fig leaf in favor
of posing trunks.)

In his lifetime Sandow was filmed by no other than
Thomas Edison, and a plaster cast of his body was made
by the Natural History Museum in London. His followers
included celebrities such as Sherlock Holmes creator Arthur
Conan Doyle and famed writer James Joyce. He even
became the personal fitness instructor to King George V.

Eugen Sandow died in 1925 at the age of 58.

Life Is Movement!

Eugen Sandow believed it was important for everyone, especially kids, to stay physically active—
to move! Here are some exercises that you can try at home. With each exercise, be sure to keep
your back straight and your belly button tucked in—this will protect your back from injury.

Try to repeat each exercise ten times. And don’t forget to stretch first!

Push-ups

Balance on your hands and toes, keeping your
back straight. Bend your elbows and lower
yourself almost to the floor. Pause for a second,
then push back up, straightening your arms.
Focus on squeezing your chest muscles. Inhale
as you go down; exhale as you push up.

Chair squats

Stand a few inches in front of a chair, with your
feet apart and your toes facing forward. With
your weight on your heels, bend your knees until
you are ina sitting position—but don’t sit down!
Pause for a second, then return to the starting
position. Inhale as you lower; exhale as you rise.

Calf raises

Rest one hand on a wall for balance, with your
other hand hanging at your side. Rise up onto the
balls of your feet. Hold for a second, squeezing
your calf muscles, then lower to where you

started. Exhale as you rise; inhale as you lower.

If you have a pair of light dumbbells, great. If
Not, use two water bottles or cans of soup. Stand
with your feet apart and your knees slightly bent.
Holding a weight in each hand, begin with your
arms at your side. Slowly raise

your arms until they are in &
ey)
line with your shoulders, i
palms facing the floor. Hold
for a second, and return to \
where you started. Exhale
as you raise your arms;
inhale as you lower them.


Author’s Note
As a kid, I was skinny. Recognizing my anxiety about it, my dad
bought me a bench press and a copy of The Bodybuilder’s Nutrition
Book. It featured nutrition information, along with photos of famous
bodybuilders like Arnold Schwarzenegger and Lou Ferrigno. I was in
awe of their superhero-like physiques. I dreamed of someday having
powerful muscles like them.

Years later my younger brother, Brian, got involved in bodybuilding
and won a statewide contest. I wondered if I could bulk up and compete,

too. At age 32 I began my bodybuilding journey, training with my brother.

Don Tate, Upper Midwest Natural Bodybuilding We lifted weights, attended aerobics classes, practiced compulsory poses.
Championships, 1998. Two years later I entered my first bodybuilding contest. I was
terrified. I sweated a little (something you’re not supposed to do). I was having one of the best nights

of my life... until I lost. I didn’t even place. I was devastated, but I didn’t give up. I continued to lift
weights. I traded candy and sugary drinks for green beans, yams, and chicken breasts. And I perfected my
poses. When I competed again the next year, I took home first- and second-place trophies.

Natural bodybuilding is drug free—the use of steroids is forbidden. For that reason, there aren’t many
garbage-truck-size contestants at these shows. I may not have had the massive muscles of a superhero,
but I sure felt like I did.

Although I no longer compete in bodybuilding, I’ve often thought about writing a book for children
about it. But how? One day I stumbled upon a picture of Eugen Sandow online. Relating to his childhood
desire to beef up, I decided to tell his story.

Writing Sandow’s story was challenging. After his death, Sandow’s family destroyed his personal
belongings. In addition, books and magazine articles about him often contradict one another. It appears
Sandow was not only a builder of muscles, but also a manufacturer of his own story. Historians are still

unsure about his parentage and early life. They've even questioned the trip he and his father supposedly
made to Rome. And don’t even get me started on the controversy over the so-called fight with the lion!

My goal for this book was to tell the story as I think Sandow would have wanted it told, fanciful as
that might be. Regardless of his true origins (and a few less-than admirable things I learned about him),
the story of Eugen Sandow is an important one. His tale of sickly kid turned physical-fitness guru and
self-made businessman inspired millions of people. Through his example, Sandow demonstrated to the
world how a healthy body is necessary for a healthy mind. His lesson rings true today.

Bibliography

Art of Manliness. “The Art of Manliness Podcast #39: Eugen Sandow, Victorian Strongman, with David
Waller.” February 2, 2012. Available online at http://www.artofmanliness.com/2012/02/02/the-art-of-
manliness-podcast-39-eugen-sandow-victorian-strongman-with-david-waller/.

Barford, Vanessa, and Lucy Townsend. “Eugen Sandow: The Man with the Perfect Body.” BBC News Magazine,
October 19, 2012. Available online at http://www.bbc.com/news/magazine-19977415.

Buck, Joshua Michael. “The Development of the Performances of Strongmen in American Vaudeville Between
1881 and 1932.” Unpublished thesis, University of Maryland at College Park, 1999. Available online at
http://joshuabuck.com/about-josh/files/thesis.pdf.

Budd, Michael Anton. The Sculpture Machine: Physical Culture and Body Politics in the Age of Empire. New York:
New York University Press, 1997.

Chapman, David L. Sandow the Magnificent: Eugen Sandow and the Beginnings of Bodybuilding. Urbana and Chicago:
University of Illinois Press, 1994.

Dickson, W. K.-L., and William Heise. “Sandow.” Video by the Edison Manufacturing Co. 1894. Available
online at https://www.loc.gov/item/00694298/.

Liederman, Earle. “My Muscles Keep Me Young—Says Sandow.” Originally published in Muscle Builder (US),
December 1924. Available online at http://physicalculturist.ca/sandow-muscles-keep-me-young/.

Liederman, Earle. “Sandow: My Impressions When We First Met.” Originally published in Muscle Power (Canada),
April/May 1946. Available online at http://www.davidgentle.com/sandow/liederman/sandow.html.

Mordden, Ethan. Ziegfeld: The Man Who Invented Show Business. New York: St. Martin’s Press, 2008.

Pearl, Bill, George Coates, Tuesday Coates, and Richard Thornley Jr. Legends of the Iron Game: Reflections on the
History of Strength Training. Vol. 1. Phoenix, OR: Bill Pearl Enterprises, 2010.

“Sandow as a Samson.” San Francisco Chronicle, May 23, 1894, p. 13.

Sandow, Eugen, “My Reminiscences,” Strand Magazine, February 1910, pp. 144-152. Available online at
https://archive.org/stream/TheStrandMagazineAnIllustratedMonthly/TheStrandMagazine1910aVol
-XxxixJan-jun#page/n161/mode/2up.

Sandow, Eugen. Strength and How to Obtain It. London: Gale & Polden, 1897. Available online at https://archive
.org/details/strengthandhowt00sandgoog.

Sandow, Eugen, and G. Mercer Adam. Sandow on Physical Training. New York: J. Selwin Tait & Sons, 1894.
Available online at https://archive.org/details/sandowgetsphysicl00sanduoft.


Sports didn’t come easy for Ernest. He couldn't run very fast. He couldn't
dribble a basketball to save his life. No one picked him to play on their teams.
Ernest felt pretty lousy about it all. “I couldn't conform easily to the athletic
ideal,” he once said.

It seemed most everyone expected boys to be good at sports, especially
in “the Bottom,” a neighborhood of hardworking but poor African Americans
in Durham, North Carolina.


== Football-Playing Artist Ernie Barnes
Ernest was good at something, however. He was good at art. In his sketch pad,
he drew pictures of trees and clouds, animals and people. In the mud after a

light rain, he sketched flowing lines all over his yard.

Ernest never said much.

His artwork was his voice.

Opportunities to learn about art were slim for kids in the Bottom during the
1930s. Art museums—~—as well as restaurants, hotels, and most colleges—were
off-limits to Black people. Segregation was the law that kept white and Black
people apart.

Laws didn’t stop Ernest’s mother from finding a way.

Ernest’s father was a shipping clerk at a tobacco company in Durham.
His mother worked in the home of an attorney—a man who loved classical
music and art. Sometimes, she took Ernest along to her job.

While she worked, Ernest scanned art books the attorney had welcomed
him to look at, books brimming with the works of revered artists such as
Toulouse-Lautrec, Delacroix, and Michelangelo. Bold, expressive
brushstrokes. Bright, vivid colors. Long, exaggerated physiques painted
Ernest’s memories for years to come.


After that, his teachers allowed him to leave school early to avoid more fights.
At home, Ernest flooded his sketch pad with hurt feelings. “When I was at
home and drawing, I was happy. I made friends with lines,” Ernest later said.

At school, Ernest was a bully magnet. A boy who didn’t play sports?
Who loved art, played the trombone, and enjoyed reading poetry? He got
teased for being different. “They hated me,” he once said.

One day after class, kids circled around. They shoved Ernest.

They snatched away his trombone. Ernest fell and skinned his knee.


When the teasing became unbearable, Ernest dragged himself to the coaches’
office and joined the football team.

Practice drills began with an ear-piercing whistle. But Ernest couldn't
keep up. Running in a helmet and pads was like exercising in an oven.

The coach fumed. “You never will be nothing!” he yelled. His berating
didn’t stop there. “You too pretty to play this game!”
That was it. Ernest quit the team.


The taunts continued in junior high. One day, someone walloped him over the
head with a book! Every eye fixed on Ernest. He froze.
“Always drawing,” someone said.
“You gonna be an artist, babe?” someone else mocked.
Then someone blurted out, “He ain’t got no guts. That’s why he won't play.”
Play football—that’s what real boys do, so many people thought.


In high school, the pressure to play football turned up again. A large boy

like Ernest, everyone thought, would surely make a great defensive lineman.

Ernest had a plan, though: He instructed his mother to “just say no” should
any coaches come snooping around to ask about him joining the team.
But she didn’t listen.

Over a prayer and a plate of fried chicken, she and the coach made
the final decision: Ernest would become number seventy-three on the
Hillside Hornets.


Ernest was miserable. But his sketch pad and pencil

soothed him. In a quiet hallway far from the football

field, Ernest released his troubles onto the page.
Then one day, he got caught. ied

: “What are you doing here, boy?” A voice cut the silence.

It was Mr. Tucker, the weight-lifting coach. ;

‘ He took Ernest's sketch pad.

But then Mr. Tucker smiled. “Did you do these drawings?” he asked.
“Yes, sir,” Ernest said.
Mr. Tucker chatted with Ernest about his art. They talked about football
and grades, too, and... bodybuilding! Turned out, exercise had helped

Mr. Tucker to become a better athlete. Could bodybuilding help Ernest to
become a better football player?

Maybe. Ernest couldn't wait to find out.



For a while, Ernest’s attention turned away from art. Instead, he focused on
building muscle. At home, he followed Mr. Tucker’s instructions. He exercised
and lifted weights. He pushed himself all summer. When football season began
in the fall, Ernest was a muscle machine—with confidence to match!

Not only did he play football, but Ernest also became the team captain.
Later, he joined the track team, too, becoming state champion in the shot put.

By graduation, he had earned twenty-six athletic scholarships to colleges
and universities.


After that, no one messed with the six-foot-three, nearly 250-pound lineman
again. “I found a groove,” Ernest later said. “I loved to win.”


No offers came from Duke University, only seven miles from his home—
or from the University of North Carolina. Black players weren't allowed.
Segregation was still the law.

His mom promised him a car if he’d stay at home and attend nearby North
Carolina College—an all-Black school that welcomed him with a full-ride
scholarship. And so that’s what Ernest did. He played hard-nosed football.
He heaved the discus and hurled the shot put. But his heart longed to create.

Ernest quit the track team to devote more time to developing as an artist.

“I never left art,’ Ernest said.

He adored the large studio classrooms, the easels, the sweet smell

of oil paints. He studied anatomy, perspective, light, and shade.

He experimented with new mediums, like charcoal and
inks. And he learned more about art history, too.



----- Text from 15.png -----
@
8
>
je)
P”)]

Sometimes Ernest got stuck for ideas on what to paint. He asked his art
teacher about it. “If you're going to be an artist, you've got to work from your

experiences,” the teacher told Ernest. “When you're on the field, check out
what is going on around you.”

Ernest listened. Then he realized how football and art were one and the
same. Both required rhythm. Both required technique. Passing, pulling,
breaking down the field—that was an art.

For Ernest, art and football could not be divided. From that point
forward, he painted images from the game of football.



“Where are the paintings by Negro artists?” he asked the museum guide.
“I'm afraid your people don’t express themselves this way,” she said.
Words as cold as ice. Words Ernest knew weren't true.
Laws had changed. People’s attitudes had not.

While Ernest grew up admiring art in books, he’d never actually been to an
art museum. Laws prevented that. But now the laws had changed. When an
upcoming field trip to the North Carolina Museum of Art was announced,
Ernest was over-the-moon excited.

Other than the post office, the museum was the fanciest place he had
ever been. Some paintings on the walls were realistic. Others were abstract.

Ernest was having a great time, but he also felt disappointed. Something
was missing.




After college, Ernest was ready to pursue a career in art. He even sold his first
painting to a basketball player. “The ninety dollars I received was great,” Ernest
said, “but the real excitement was in having him hang my paintings in his home.”

Nothing slowed Ernest’s dreams...

... except for maybe one thing: an offer to play for the American Football
League!

On draft day, professional teams chose players, and Ernest hoped to get
picked. A career in football could make him a rich man. On the morning of the
draft, he opened the sports section of the newspaper and searched for his name.
Ernest’s hands were sweating; his heart pounded. Several of his teammates were
listed, but his name was missing. Then he saw it: “Ernest Barnes, a tackle at
North Carolina College.”

He dashed out to the garden to show his mom.
“Look, Mama, look! I got drafted by the Colts!”

Wow! Imagine that! The kid from the Bottom, who no one chose to play on
their team, was now in demand from the biggest football league in the nation.

Ernest would become a professional football player. sind



The World Champion Baltimore Colts had been eyeing Ernest throughout his

college years. Soon, they jetted him off to Baltimore to watch the championship
game and to sign a contract.

“When a sportswriter learned about Ernest, he requested aninterview. |
A football-playing artist? Now there was a story to tell! But when the article
was printed in the Baltimore News-Post, Ernest’s name was misspelled as
“Ernie.” From that day forward, Ernest Barnes became known as Ernie Barnes.
And the football-playing artist was just fine with that.

Officially, Ernie Barnes was a Baltimore Colt. But new players had to make
it through training camp before officially making the team, which proved to
be tougher than Ernie had imagined. Guys in the big leagues were larger than

‘ ee college players. Muscle-bound bodies bashed. Heads banged. Sometimes
Ernest could not sleep that night. Excited, SS clashes were bloody.
he spiraled out of bed and grabbed a ig Ernie gave his best, but it wasn’t good enough. By the final day of camp,
paintbrush. Then he expressed his delight i he had been cut from the Colts. Ernie was crushed.
on canvas, painting a picture of his new
teammates. He named his artwork The Bench.






During time-outs, he scribbled notes of what he’d seen while playing.
He recorded what his body felt like when it moved. He planned how he
could splash that movement onto canvas later.
Sketching during team meetings was a big no-no, however. One time, a
coach fined him a hundred dollars as punishment. His teammates didn’t mind,

though—they nicknamed him “Big Rembrandt,” after the famous Dutch artist.

play for the New York Titans. Later, he played for the San Diego Charger
before ending up on the Denver Broncos. ;

Art remained in Ernie's heart, even on the field. Before games,
Ernie slipped the stub of a pencil and a notepad into his sock, —




ns of football slogged by. Ernie battled on the gridiron, but his


heart ached for more time to paint. After an injury, Ernie decided it was
‘to retire from football. He was twenty-seven ye: r 4



Definitely not. Ernie had a plan: At a meeting with league owners, he asked
to be hired back. Not as a player, but as an artist—the Official Artist of the

American Football League!
The owners got quiet as Ernie pled his case. No one knew quite how to

respond. An artist? For a football league? They were confused.



On the night of the exhibition, the gallery quickly swarmed with football |
players, art critics, sports announcers, and reporters. t

Ran naaa aa naa maaan shes eens i , ‘ ae rl
) Ernie was worried, his nerves like jelly. Had he made a mistake? Would nnn

¥
f ») anyone even purchase a painting?
s A phone call from his mother calmed him. She offered a prayer, then sent

him off to greet his guests.

Owners of the New York Jets liked the idea, however, and Ernie soon

joined their team—yes, as an artist! He quickly went to work creating thirty
new paintings in just a few months.

A solo art show at a Manhattan gallery was soon arranged by Sonny
Werblin, the owner of the Jets.


NORTH CAROLINA

Ernie’s paintings were dynamic. Lights and shadows swirled. Lines and
patterns sang. The raw muscle of football danced with the grace of a ballerina.
Ernie began painting the people of the Black community he so admired.
This collection of paintings he called The Beauty of the Ghetto. One of his

paintings was featured on the national television show Good Times.
Ernie even appeared on the show—twice!

MUSEUM OF ART |

@

In the spring of 1979, Ernie’s art career churned full circle, when he exhibited
at the North Carolina Museum of Art. Surely he thought about the tour guide
from twenty-three years ago, the one who said that Black people didn’t express
themselves artistically. He must have thought about all the bullies who teased
him for wanting to be an artist. Maybe he thought about his father, who had
passed away by now and hadn't believed art was a good career choice.


Ernest Barnes had been a boy who liked art. He was shy. He was quiet.
Others tried to decide who he should be.

But Ernest decided for himself. He became an athlete. He became an
artist. This boy could be anything he wanted to be! “Football demands
creativity,’ Ernie once said.

From pigskins to paintbrushes, Ernie Barnes grew to be a man successful
at being himself.


AFTERWORD

During my research, | discovered that there were sometimes
conflicting dates about events in Ernie's Life. | used From Pads to

Palette, Ernie’s memoir, as my principal source. On a few occasions,
| had to make educated guesses based on other events in his Life. |
am not an official spokesperson for the Ernie Barnes Family trust. |
am a children’s picture book biographer. In my work, | strive to give

SAM BOND PHOTOGRAPHY

my readers a taste of a subject's life through words and pictures.

Don Tate

That becomes a challenge in the limited number of pages | have

to work with. In addition, telling the story of an iconic and beloved artist, whose works
continue to exhibit around the world, presents additional challenges. In telling this story, |
was intentional about not creating images representative of Ernie Barnes's artwork, style,
or technique. In order to see and enjoy the true artwork of Ernie Barnes in its Full glory,
please see his official website, ErnieBarnes.com, or other sources Listed in the bibliography.
(About the title: Early footballs were made of animal bladders—often from pigs. They were
inflated and sometimes stuffed with straw or other material. Today’s footballs, and those of

Ernie Barnes's day, were made of rubber, but the nickname “pigskins” stuck.)

Ernest (Ernie) Eugene Barnes Jr. was a beloved African American artist, football
player, actor, and author. He was born on July 15, 1938, in Durham, North Carolina.
Barnes's artwork, with its elongated human figures and graceful movement, possessed
a similarity of technique and style prevalent during the sixteenth century, prompting
an art critic to describe Barnes as the founder of the Neo-Mannerism movement.
However it is labeled, Ernie Barnes’s artwork is a testament to his love of sports and to
the African American experience.

The Barnes family lived on Willard Street, an unpaved road in a poor area of town
folks referred to as the Bottom. This was during the Jim Crow era, when Durham was
segregated.

Ernie’s father, Ernest Eugene Barnes Sr., worked as a shipping clerk for a tobacco
company. His mother, Fannie Mae Geer, worked as a domestic. Ernie had an older half
brother, Benjamin, and a younger brother, James.

Fannie Mae introduced her children to the arts at an early age, encouraging them
to take tap-dance lessons and learn to play several musical instruments. She worked

in the home of prominent attorney and school board member Frank L. Fuller Jr., a
lover of art and classical music. On the occasions when Ernest accompanied his mom
to work, Mr. Fuller shared his art books and discussed his favorite painters with Ernie.
Mr. Fuller's discarded classical records and art prints were like gold in the hands of the
young artist. By the time Ernest entered first grade, he was familiar with such masters
as Toulouse-Lautrec, Delacroix, Rubens, and Michelangelo.

Barnes described himself as overweight, shy, and sensitive, with a mother who
dressed him like “the white kids who went to the fashionable private schools.” He
became the target of bullies throughout his grade school years.

In high school, he turned low self-esteem on its head after a weight-lifting coach
taught him about bodybuilding. After that, Barnes became a prolific athlete, earning
twenty-six athletic scholarships.

Barnes credits Ed Wilson, the chairman of his college department, with helping
him to develop the foundation of his art. Wilson reminded his student that art was all
around him and that he should work from his experiences. He advised Barnes to pay
special attention to what his body felt like while playing football and then to express
that movement in his art.

Erie Barnes standing alongside one of his paintings at the Grand Central Art Galleries in New York, November 15,1966. (AP
Photo/John Rooney, File)


In 1960, at the dawn of the civil rights movement, Barnes was drafted into the
National Football League, an opportunity he could not resist. An art career would
have to wait. He played five seasons as an offensive guard. Originally, he was selected
to play for the Washington Redskins, who dropped him from the team minutes after
discovering he was Black.

By the end of his career, Barnes had grown angry with football—the brutality and
violence, the dehumanization of the sport. He retired in 1966 following an injury.

He approached the league owners with the idea of becoming the official artist for
the American Football League. The idea led to his being hired by Sonny Werblin,
owner of the New York Jets, “to just paint” for six months, wherein he earned more
money than his previous year as a player. A solo art exhibition was then set up, and its
success launched Barnes'’s art career.

As a response to the 1960s Black Is Beautiful movement, Barnes created a series of
thirty-five paintings that served as visual love letters to Black America. The Beauty of
the Ghetto toured major cities from 1972 through 1979.

In most of his later paintings, Barnes portrayed subjects with their eyes closed, a
detail that expressed his belief that “most people are blind to one another’s humanity,
to their inner light.” He believed that racism had “taught many of us ‘what’ to think
about each other, but not ‘how’ to think about one another.”

In 1984, Ernest Barnes became the official artist of the Olympic Games in Los
Angeles. In 1984, and again in 2004, he was named Sport Artist of the Year by the
American Sport Art Museum and Archives. In 1990, Barnes was awarded an honorary
doctorate of fine arts by North Carolina Central University.

Barnes won commissions from entertainers of his time—such as Harry Belafonte, Flip
Wilson, and Charlton Heston—in addition to more recent celebrities like Kanye West.
Barnes's artwork has appeared in magazines and on album covers, while he himself has
appeared on television and in movies.

Ernest Barnes died on April 27, 2009. & @
Boise Wwe

Poke
4

SSI
01 eolONg
< LLCOIoeg

AUTHOR'S NOTE

Asa child, I loved the 1970s television show Good Times. It featured a Black family at
a time when there weren't many other shows on TV that featured people who looked
like me.

One of the main characters was teenage J. J. Evans. He was an artist who painted
positive images of Black people with graceful, elongated bodies—his artwork moved.
Years later, I learned that J.J. was not the actual artist who created those paintings. The
real-life artist was former football player Ernie Barnes. What? I tucked away a mental
note until years later, when I'd write this book.

While doing research for this story, I realized that Barnes’s childhood experience
was similar to my own. I was not good at sports, and I felt inadequate about it. Boys,
especially in the Black community where I grew up, were expected to excel at baseball
and basketball. But I was always the last choice when teams picked players. I could
not dribble a basketball. I could not catch a baseball. While playing right field in Little
League baseball, I prayed the ball would not come my way. And football? Just no.

I was an art kid. Researching Barnes's childhood story conjured memories of when I
was made to feel less of a boy as I avoided the fast and furious basketball courts during
summer camps in favor of coloring or making crafts—most times with a group of girls.
Drawing, painting, braiding, sewing, and macramé were some of my favorite pastimes.
But these activities ran counter to many others’ definition of masculinity.

It wasn’t until much later in life that I became drawn
to athletics. Not football or basketball—definitely not any
contact sports. My sport was bodybuilding. Inspired by
my brother, who became an award-winning competitor in
natural bodybuilding, I started working out every day.

I became a gym rat, loving the gym as much as my art
studio. Eventually, I competed in natural bodybuilding,
too—and I won!

Today, I am an artist; I draw, paint, and write. Today, I
am an athlete, too; I run, swim, and practice yoga daily.
And just like Ernest Barnes, I define myself, not letting
others decide who I should be.


NOTES

For more information about the sources below, please see the bibliography.

5 “I couldn't conform...athletic ideal”: Barnes, From Pads to Palette, p. 8.
10 “They hated me”: Ibid.

11 “When I was at home ...1 made friends with lines ”: Ibid.

12 “Always drawing”: Barnes, p. 10.

12 “You gonna be an artist, babe?”: Barnes, From Pads to Palette, p. 10.
Front and back of the 1964 Denver Broncos

Topps football card. Barnes is shown wearing 12 “He ain't got... won't play”: Ibid.
jersey #55 although his jersey was actually #62.
eae Sa card used courtesy of The Topps 13 “You never will be nothing!”: Barnes, p. 11. @
13 “You too pretty to play this game!”: Ibid. ‘es
a }
F < > yf
A 16 “What... here, boy?”: Barnes, p. 12. WEY
NIE B 2
ERI BRONCOS 17 “Did you do these drawings?”: Ibid. “ey

19 “I found a groove”: Ibid.

20 “Inever left art”: “Ernie Barnes Links Art and Athletics.” Baytown Sun,
March 13, 1983, p. 11.

22 “Ifyou're going...on around you”: Barnes, p. 14.

25 “Where are the paintings ... themselves this way”: Barnes, p. 15.
26 “The ninety dollars ...in his home”: Barnes, p. 16.

26 “Look, Mama...the Colts!”: Barnes, From Pads to Palette, p. 17.

38 “Football demands creativity”: “Former Pro Gridder Ernie Barnes Sees No
Conflict Between Football and Art,” Sioux City Journal (Associated Press),
November 14, 1972; p. 24.

BIBLIOGRAPHY S
ARTICLES .

Baytown Sun (Baytown, TX). “Ernie Barnes Links Art and Athletics.” ees
March 13, 1983. beg

Clarion-Ledger (Jackson, MS). “Ernie Barnes Paints Portraits in Dignity.”
September 29, 1974.

Colorado Springs Gazette-Telegraph. “Ernie Barnes Combines Football,
Art—Successfully.” October 12, 1972.

Daily News (New York). “Beauty in the Ghetto.” September 29, 1975.

Durham Sun (Durham, NC). “Barnes’ Museum Exhibit Personal Accomplishment.”
May 17, 1979.

Morning Herald (Durham, NC). “Durham Artist Opens Show.” May 20, 1979.

Murphy, Zacki. “Ernie Barnes: Native Son and Artist Extraordinaire.” Herald
Sun (Durham, NC). June 21, 2018. See www.heraldsun.com/opinion
/article213558884.html.

Robinson, Louie. “The Violent Brush of Ernie Barnes.” Ebony, March 1973 (p. 40).

Weber, Bruce. “Ernie Barnes, Artist and Athlete, Dies at 70.” New York Times,
April 30, 2009. See www.nytimes.com/2009/04/30/arts/30barnes.html.

BOOKS
Barnes, Ernie. From Pads to Palette. Waco, TX: WRS, 1995.

Hurd, Michael. Black College Football, 1892-1992: One Hundred Years of History,
Education, and Pride. Marceline, MO: Walsworth, 2000 (p. 63-65).

Wallace, Sandra Neil. Between the Lines: How Ernie Barnes Went from the
Football Field to the Art Gallery. New York: Simon & Schuster/Paula
Wiseman, 2018.



CNN Tribute to Ernie Barnes (featuring Akili Richards)
youtube.com/watch?v=T24QlwFuzTo a

Ernie Barnes: An American Story & :

North Carolina Museum of History
youtube.com/watch?v=7QBj726-bwI

Ernie Barnes Exhibit

North Carolina Museum of History

www.pbs.org/video/ernie-barnes-exhibit-nc-museum-history-rj7yek

Kareem Abdul-Jabbar for the Hollywood Reporter
How Athlete-Artist Ernie Barnes Captured Black Culture’s “Joy and Communal Dignity”
hollywoodreporter.com/news/kareem-abdul-jabbar-how-athlete-artist-ernie
-barnes-captured-black-cultures-communal-dignity-1209376


== Lonnie Johnson's Super-Soaking Stream of Inventions
Lonnie loved building and creating. Ideas for
inventions just kept on flowing.

He learned how to make rockets from scratch.
Kids at school gathered to watch Lonnie launch them.

And he learned how to make rocket fuel. When it
XN caught fire in the kitchen, Lonnie’s mom didn’t make
> him stop. She just sent him to work outside.

Lonnie wanted to spend his life designing things,
building things, and getting them to work. He wanted
to be an engineer. However, Lonnie took an exam that
said he would not make a very good one.

His dream had been challenged. Lonnie was
discouraged. But he knew that whoever had graded his
test hadn’t met Linex.


Inspired by a TV show, Lonnie had built his own robot.
He made it out of scrap metal and named it Linex.

Compressed-air cylinders and valves allowed Linex’s
body to turn and its arms to move. The switches came
from an old, broken jukebox. Lonnie used a tape recorder
to program Linex, and as a bonus the reels looked like eyes.
Lonnie wanted to enter his creation in a science fair, but
he couldn’t get the transmitter to work. Without it Lonnie
couldn’t send commands to Linex.

Science fairs came and went. Lonnie missed one
and then another—until he got an idea.

Now, Lonnie may or may not have asked before he
borrowed his little sister’s walkie-talkie . . .


. . . but it fixed the transmission issue. His school’s team
took freshly finished Linex to a 1968 science fair at the
University of Alabama—where only five years earlier,
African American students hadn’t even been allowed.

LYFT PENT

Having to compete in a place that still wasn’t very
welcoming? Now, that was a challenge with a capital C.

Against other schools from all over the state, Lonnie’s
team won first place.

ne to to college at Tuskegee
stood out as a self-confident, insightful,

tas a student who asked the right questions,



----- Text from 10.png -----
When NASA was sending an orbiter and probe

_ called Galileo to Jupiter, the space agency needed to
ensure a constant supply of power to the orbiter’s
computer memory. The engineer wha had to figure
out how to do it was Lonnie. .

His challenge was to come up with a lightweight
backup system able to keep essential functions going
in case the main power was lost. ‘

It wasn’t easy. It wasn’t obvious. But Lonnie found
a solution. :

Some at NASA’s Jet Propulsion Laboratory doubted
his idea would work. Lonnie convinced them it would. —

He was right.

As it photographed Jupiter and its moons, Galileo was
supported by the power package that Lonnie designed.
Much of what we know about Jupiter could have been
at risk in a power failure if not for Lonnie.

Ideas for other problems to solve just kept on flowing.

They flowed whether Lonnie was working with hundreds
of people at NASA or up late tinkering with his own
inventions in—finally!—his own workshop.

Lonnie knew the world’s millions of refrigerators and air
conditioners needed a new cooling system—one that didn’t
use R-12, a chemical that was bad for the environment.

He had an idea for using water and air pressure instead.

To test his idea, he made a pump and nozzle...
connected them to the bathroom faucet . . . turned on the
faucet, turned on the pump, and then...


The stream that blasted across the bathroom was so

powerful, it created a curtain-swirling breeze. It also gave

Lonnie an idea for yet another invention.
“This,” he thought, “would make a great water gun.” l)
First he had to find or make the parts, including a pump

small enough for a child to handle.
Then he had to glue the parts together into a prototype—

an early version with room for improvement.

Finally Lonnie tested his strange-looking squirt gun at
a picnic.

“Does it really work?” a man asked.

“Sure,” Lonnie said. “Wanna see?”

Lonnie worked the pump, which squeezed air into a
chamber. When he pulled the trigger, the air escaped,
forcing water out witha...



----- Text from 14.png -----
oy)

For a water battle to be a fair fight, there couldn’t

be just one of Lonnie’s water guns. He needed help
making more.

So, he went to toy company...
after toy company... .
after toy company.

The word “no” flowed again and again. But finally one
company said, “Yes!” It planned to make his water gun!
Lonnie also had other projects: a water-propelled toy
airplane, two kinds of engines, and his cooling system. He
found investors to provide the money for turning his ideas
into products people could buy. He made a leap of faith,
quit his day job, and devoted himself to full-time inventing.


But soon each plan fell apart—even the one for the water
gun. These things sometimes happen. But when they happen
one after another to the same person—well, that’s some
pretty bad luck.

Lonnie didn’t have a job. He didn’t have the money he’d
been counting on. He and his family had to move out of their
home and into a little apartment. He was angry and scared.

But Lonnie had dealt with challenges all his life. He knew
a lot about solving problems. And he still believed in his
inventions, especially the water gun. Lonnie went looking
for another toy company.

In 1989 he found a toy maker who was interested

in seeing the water gun if Lonnie ever happened to
be in Philadelphia.

“But don’t make a special trip,” the guy said.
Lonnie made a special trip.


In his wife’s suitcase, he carried a new
prototype. He unpacked it, filled the tank
with water, pumped the gun until the air
pressure was good and high, and... .

Kids everywhere agreed with that “Wow!” Lonnie’s

water gun, called the Super Soaker, became a smash hit.
In no time there were Super Soakers in backyards and
on beaches, in parks and on playgrounds. Each sale of
a Super Soaker put a little money into Lonnie’s pocket.

So what did Lonnie do?

He got a bigger workshop, which is where you'll find
him today. Because facing challenges, solving problems,

and building things are what Lonnie Johnson loves to do.
And his ideas just keep on flowing.


Avtuor’s Note

A SUPER SoakER usesa pump
to compress the air found in its water
reservoir, which puts pressure on the
water. When the trigger is pulled, the
pressurized water can escape and...
WHOOSH! If you search the internet for
“how Super Soakers work,” you'll find a
lot more about what goes on inside
Lonnie Johnson’s most famous
invention.* But if you want to better
understand how Lonnie Johnson himself
works, then you’ll put this book down,
step away from the computer screen, and
get permission to take something apart
so you can see those kinds of goings-on
for yourself. You might even start with a
Super Soaker.

This book began with a lunchtime
conversation I had with a couple of
librarians in Texas. They had recently
gone to a seminar where attendees were
asked to draw a picture of a scientist.
The most common image was of a guy
who resembled Albert Einstein—lab coat,
wild hair, white skin. The point of the
exercise was to draw attention to the fact
that scientists are more diverse than that.

The lesson those librarians learned rubbed
off on me, and by dinnertime | had found
the story of the African American rocket
scientist who invented the Super Soaker.

What was most appealing to me
about Lonnie Johnson’s story was the fact
that it was still unfolding. He didn’t just
take his Super Soaker money and retire
young. Instead, he directed it toward
hands-on efforts to solve one of the most
important engineering puzzles of our day.
His mission? To efficiently harness heat
energy—from the sun and other sources—
in order to generate the electricity we
need without polluting the planet.



