CompTIA Network

=== What Does This Book Cover?
Chapter 1, “Introduction to Networks” This chapter includes an introduction to what a
network is and an overview of the most common physical network topologies you'll find in
today’s networks.

Chapter 2, “The Open Systems Interconnection Specifications” This chapter covers the
OSI model, what it is, what happens at each of its layers, and how each layer works.

Chapter 3, “Networking Topologies, Connectors, and Wiring Standards” This chapter
covers the various networking media and topologies, plus the cable types and properties
used in today’s networks.

Chapter 4, “The Current Ethernet Specifications” This chapter covers how a basic
Ethernet LAN works and describes and categorizes the different Ethernet specifications.

Chapter 5, “Networking Devices” It’s important for you to understand all the various
devices used in today’s networks, and this chapter will describe how hubs, routers, and
switches and some other devices work within a network.

Chapter 6, “Introduction to the Internet Protocol” This is your introduction to the all-
important IP protocol stack.

Chapter 7, “IP Addressing” This chapter will take up from where Chapter 6 left off and
move into IP addressing. It also contains information about public versus private addressing
and DHCP.

Chapter 8, “IP Subnetting, Troubleshooting IP, and Introduction to NAT” Beginning
where Chapter 7 ends, we'll be tackling IP subnetting in this one. But no worries here—I’ve
worked hard to make this not-so-popular-yet-vital topic as painless as possible.

Chapter 9, “Introduction to IP Routing” This is an introduction to routing that basically cov-
ers what routers do and how they do it. This chapter, along with Chapter 10 and Chapter 11,
cover routing and switching in much more detail than what is necessary to meet the CompTIA
Network+ objectives because this knowledge is so critical to grasp when working with today’s
networks.

Chapter 10, “Routing Protocols” This chapter goes into detail describing the protocols
that run on routers and that update routing tables to create a working map of the network.

Chapter 11, “Switching and Virtual LANs” This chapter covers Layer 2 switching, the
Spanning Tree Protocol (STP), and virtual LANs. I went deeper than needed for the exam
with the routing chapters, and I’ll cover switching and virtual LANs (which are also vital
in today’s corporate networks) more thoroughly as well.

Chapter 12, “Wireless Networking” Because wireless is so important for both home and
business networks today, this chapter is loaded with all the information you need to be
successful at wireless networking at home and work.

Chapter 13, “Authentication and Access Control” This is the first of three security chapters.
There are tons of exam objectives about network security that are so important that I took
three chapters to cover all of them. In this chapter, I’ll introduce security, security filtering,
tunneling, and user authentication.

Chapter 14, “Network Threats and Mitigation” This is probably the most fun of the
three security chapters because I'll tell you all about security threats and how to stop them.
The only way to get good at network security is to implement it, and this chapter shows
you how.

Chapter 15, “Physical and Hardware Security” This chapter’s focus is on explaining basic
firewalls, security devices, and device security.

Chapter 16, “Wide Area Networks” In this chapter, you get to learn all about things like
Frame Relay, E1/T1, DSL, cable modems, and more. All of the CompTIA Network+ WAN
objectives are covered in this chapter.

Chapter 17, “Troubleshooting Tools” This is also a fun chapter because again, you can
follow along and run all the commands yourself. And I repeat, it’s a really good idea to run
through all the commands in this chapter!

Chapter 18, “Software and Hardware Tools” This chapter introduces you to the network
tools you will use to help you run your networks. Both software and hardware tools will
be discussed.

Chapter 19, “Network Troubleshooting” In almost every chapter, I discuss how to verify
and fix problems, but this chapter will really get into the nuts and bolts of detailed network
troubleshooting and documentation.

Chapter 20, “Management, Monitoring, and Optimization” This last chapter will pro-
vide configuration-management documentation and covers wiring, logical diagrams, base-
lines, policies, and regulations.

=== Chapter 1 Introduction to Networks
==== 1. First Things First: What’s a Network? 2

The Local Area Network (LAN) 3

Common Network Components 5

Wide Area Network (WAN) 7

Network Architecture: Peer-to-Peer or Client-Server? 9

==== 2. Physical Network Topologies 12

Bus Topology 12

Star Topology 13

Ring Topology 14

Mesh Topology 15

Point-to-Point Topology 16

Point-to-Multipoint Topology 17

Hybrid Topology 18

==== 3. Topology Selection, Backbones, and Segments 18

Selecting the Right Topology 19

The Network Backbone 20

Network Segments 21

=== Chapter 2 The Open Systems Interconnection Specifications

==== 1. Internetworking Models 28
The Layered Approach 28

Advantages of Reference Models 29

===== 2. The OSI Reference Model 30

The Application Layer 31

The Presentation Layer 33

The Session Layer 33

The Transport Layer 33

The Network Layer 39

The Data Link Layer 42

The Physical Layer 44

==== 3. Introduction to Encapsulation 45


Summary

Exam Essentials
Written Lab
Review Questions

=== Chapter 3 Networking Topologies, Connectors, and Wiring Standards

==== 1. Physical Media
Coaxial Cable

Twisted-Pair Cable

Fiber-Optic Cable

Media Converters

Broadband over Power Line

Serial Cables

==== 2. Cable Properties
Transmission Speeds
Distance
Duplex
Noise Immunity (Security, EMI)
Frequency

==== 3. Wiring Standards
S68A vs. 568B
Straight-Through Cable
Crossover Cable
T1 Crossover Cable

==== 4. Installing Wiring Distributions
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 4 The Current Ethernet Specifications

==== 1. Network Basics

==== 2. Ethernet Basics

Collision Domain

Broadcast Domain

CSMA/CD

Half- and Full-Duplex Ethernet

==== 3. Ethernet at the Data Link Layer
Binary to Decimal and Hexadecimal Conversion
Ethernet Addressing

Ethernet Frames

Channel Bonding

==== 4. Ethernet at the Physical Layer
Summary

=== Chapter 5 Networking Devices
==== 1. Common Network Connectivity Devices
Hub

Network Interface Card

Bridge

Switch

Router

Firewall

Dynamic Host Configuration Protocol Server

==== 2. Other Specialized Devices

Multilayer Switch

Load Balancer

Domain Name Service Server

Proxy Server

Encryption Devices

VPN Concentrator

==== 3. Planning and Implementing a Basic SOHO Network Using Net-

work Segmentation

Determining Requirements
Switches and Bridges at the Data Link Layer
Hubs at the Physical Layer
Environmental Considerations

Summary

Exam Essentials

Written Lab

Review Questions

=== Chapter 6 Introduction to the Internet Protocol

==== 1. Introducing TCP/IP
A Brief History of TCP/IP
TCP/IP and the DoD Model
The Process/Application Layer Protocols
The Host-to-Host Layer Protocols
The Internet Layer Protocols

==== 2. Data Encapsulation

Summary

Exam Essentials

Written Lab

Review Questions


=== Chapter 7 IP Addressing

==== 1. IP Terminology

==== 2. The Hierarchical IP Addressing Scheme
Network Addressing
Private IP Addresses

==== 3. IPv4 Address Types
Layer 2 Broadcasts
Layer 3 Broadcasts
Unicast Address
Multicast Address

==== 4. Internet Protocol Version 6 (IPv6)
Why Do We Need IPv6?
The Benefits of and Uses for IPv6
IPv6 Addressing and Expressions
Shortened Expression
Address Types
Special Addresses

Summary

Exam Essentials

Written Lab

Review Questions

=== Chapter 8. IP Subnetting, Troubleshooting IP, and Introduction to NAT

==== 1. Subnetting Basics
How to Create Subnets
Subnet Masks
Classless Inter-Domain Routing (CIDR)
Subnetting Class C Addresses
Subnetting Class B Addresses

==== 2. Troubleshooting IP Addressing
Determining IP Address Problems

==== 3. Introduction to Network Address Translation (NAT)
Types of Network Address Translation
NAT Names
How NAT Works
Summary
Exam Essentials
Written Labs
Review Questions

=== Chapter 9. Introduction to IP Routing

==== 1. Routing Basics

==== 2. The IP Routing Process

==== 3. Testing Your IP Routing Understanding

==== 4. Static and Dynamic Routing

Summary

Exam Essentials

Written Lab

Review Questions

=== Chapter 10. Routing Protocols

==== 1. Routing Protocol Basics
Administrative Distances
Classes of Routing Protocols

==== 2. Distance Vector Routing Protocols
Routing Information Protocol (RIP)
RIP Version 2 (RIPv2)
VLSM and Discontiguous Networks
EIGRP
Border Gateway Protocol (BGP)

==== 3. Link State Routing Protocols
Open Shortest Path First (OSPF)
Intermediate System-to-Intermediate System (IS-IS)

==== 4. IPv6 Routing Protocols
RIPng
EIGRPv6
OSPFv3
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 11. Switching and Virtual LANs

==== 1. Networking Before Layer 2 Switching

==== 2. Switching Services

Limitations of Layer 2 Switching

Bridging vs. LAN Switching

Three Switch Functions at Layer 2

==== 3. Spanning Tree Protocol

Spanning-Tree Port States

STP Convergence

Rapid Spanning Tree Protocol 802.1w


==== 4. Virtual LANs
VLAN Basics
Quality of Service
VLAN Memberships
Static VLANs
Dynamic VLANs
Identifying VLANs
VLAN Identification Methods

==== 5. VLAN Trunking Protocol
VTP Modes of Operation
Configuring VTP

==== 6. Two Additional Advanced Features of Switches
Power over Ethernet
Port Mirroring/Spanning
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 12. Wireless Networking
==== 1. Introduction to Wireless Technology

==== 2. The 802.11 Standards
2.4GHz (802.11b)
2.4GHz (802.11g)
SGHz (802.11a)
5GHz (802.11h)
2.4GHz/S5GHz (802.11n)

==== 3. Comparing 802.11 Standards
Range Comparisons

==== 4. Wireless Network Components
Wireless Access Points
Wireless Network Interface Card
Wireless Antennas

==== 5. Installing a Wireless Network
Ad Hoc Mode: Independent Basic Service Set
Infrastructure Mode: Basic Service Set
Signal Degradation
Installing and Configuring Hardware

==== 6. Wireless Security
Open Access
Service Set Identifiers, Wired Equivalent Privacy,
and Media Access Control Address Authentication
Remote Authentication Dial In User Service

Temporal Key Integrity Protocol
Wi-Fi Protected Access or WPA 2 Pre-Shared Key
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 13. Authentication and Access Control

==== 1. Security Filtering
Access Control Lists
Tunneling
Encryption
Remote Access

==== 2. Managing User Account and Password Security
Managing User Accounts
Managing Passwords
Single Sign-On
Multifactor Authentication

==== 3. User-Authentication Methods
Public Key Infrastructure (PKI)
Kerberos
Authentication, Authorization, and Accounting (AAA)
Network Access Control (NAC)
Challenge Handshake Authentication Protocol (CHAP)
MS-CHAP
Extensible Authentication Protocol (EAP)
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 14. Network Threats and Mitigation

==== 1. Recognizing Security Threats
Denial of Service
Viruses
Worms
Buffer Overflow
Wireless Threats
Attackers and Their Tools
Social Engineering (Phishing)

==== 2. Understanding Mitigation Techniques
Active Detection
Passive Detection
Proactive Defense

==== 3. Policies and Procedures
Security Policies
Security Training
Patches and Upgrades
Updating Antivirus Components
Fixing an Infected Computer
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 15. Physical and Hardware Security

==== 1. Using Hardware and Software Security Devices

==== 2. Defining Firewalls
Network-Based Firewalls
Host-Based Firewalls

==== 3. Firewall Technologies
Access Control Lists
Port Security
Demilitarized Zone
Protocol Switching
Dynamic Packet Filtering
Proxy Services

==== 4. Firewalls at the Application Layer vs. the Network Layer
Stateful vs. Stateless Network Layer Firewalls
Application Layer Firewalls

==== 5. Scanning Services and Other Firewall Features
Content Filtering
Signature Identification
Zones

==== 6. Intrusion Detection and Prevention Systems
Network-Based IDS
Host-Based IDS
Vulnerability Scanners

==== 7. VPN Concentrators

==== 8. Understanding Problems Affecting Device Security
Physical Security
Logical Security Configurations
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 16. Wide Area Networks

==== 1. What’s a WAN?
Defining WAN Terms
The Public Switched Telephone Network
WAN Connection Types
Bandwidth or Speed

==== 2. T-Series Connections
The T1 Connection
The T3 Connection

==== 3. Transmission Media
Wired Connections
Dense Wavelength Division Multiplexing
Passive Optical Network
Wireless Technologies

==== 4. Broadband Services
DSL Technology and xDSL
Cable Modem

==== 5. Wireless WAN Technologies
Cellular WAN

==== 6. WAN Protocols

Integrated Services Digital Network
Frame Relay Technology
Asynchronous Transfer Mode
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 17. Troubleshooting Tools

==== 1. Protocol Analyzers

==== 2. Throughput Testers

==== 3. Connectivity Software

==== 4. Using Traceroute

==== 5. Using ipconfig and ifconfig

Using the ipconfig Utility
Using the ifconfig Utility

==== 6. Using the ping Utility

==== 7. Using the Address Resolution Protocol
The Windows ARP Table
Using the arp Utility

==== 8. Using the nslookup Utility
==== 9. Resolving Names with the Hosts Table
==== 10. Using the Mtr Command
==== 11. Using the route Command
Using the route Command Options
Some Examples of the route Command

==== 12. Using the nbtstat Utility
he -a Switch
he -A Switch
he —c Switch
he —n Switch
he -r Switch
he —R Switch
he —S Switch
he —s Switch

==== 13. the netstat Utility
he -a Switch
he -e Switch
he -r Switch
he —s Switch
he —p Switch
he — Switch

==== 14. Using the File Transfer Protocol
Starting FTP and Logging In to an FTP Server
Downloading Files
Uploading Files

==== 15. Using the Telnet Utility
How to Enable Telnet in Vista
Don’t Use Telnet, Use Secure Shell
Summary
Exam Essentials
Written Lab
Review Questions


=== Chapter 18. Software and Hardware Tools

==== 1. Understanding Network Scanners
Packet Sniffers
Intrusion Detection and Prevention Software
Port Scanners

==== 2. Identifying Hardware Tools
Cable Testers
Protocol Analyzer
Certifiers
Time-Domain Reflectometer
Optical Time-Domain Reflectometer
Multimeter
Toner Probe
Butt Set
Punch-Down Tool
Cable Stripper/Snips
Voltage Event Recorder
Environmental Monitors
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 19. Network Troubleshooting

==== 1. Narrowing Down the Problem
Are There Any Cabling Issues? Did You Check
the Super Simple Stuff?
Is Hardware or Software Causing the Problem?
Is Ita Workstation or a Server Problem?
Which Segments of the Network Are Affected?
Is It Bad Cabling?

==== 2. Troubleshooting Steps
Step 1: Identify the Problem
Step 2: Establish a Theory of Probable Cause
Step 3: Test the Theory to Determine Cause
Step 4: Establish a Plan of Action to Resolve the
Problem and Identify Potential Effects
Step 5: Implement the Solution or Escalate as Necessary
Step 6: Verify Full System Functionality and
If Applicable Implement Preventative Measures
Step 7: Document Findings, Actions, and Outcomes

==== 3. Troubleshooting Tips
Don’t Overlook the Small Stuff
Prioritize Your Problems
Check the Software Configuration
Don’t Overlook Physical Conditions
Don’t Overlook Cable Problems
Check for Viruses
Summary
Exam Essentials
Written Lab
Review Questions

=== Chapter 20. Management, Monitoring, and Optimization

==== 1. Managing Network Documentation
Using SNMP
Schematics and Diagrams
Baselines
Policies, Procedures, and Regulations

==== 2. Monitoring the Network and Optimizing Its Performance
Network Monitoring and Logging
Reasons to Optimize Your Network’s Performance
How to Optimize Performance
Virtual Networking
Summary
Exam Essentials
Written Lab
Review Questions


certification.comptia.org/Training/testingcenters/

http://certification.comptia.org/getCertified/steps_to_certification/
stayCertified.aspx

http: //itpro.comptia.org

=== Introduction
==== 1.0 Network Concepts 21%
===== 1.1 Compare the layers of the OSI and TCP/IP models.
OSI model:
» Layer 1 - Physical
Layer 2 - Data link
» Layer 3 - Network
Layer 4 - Transport
= Layer 5S - Session
Layer 6 — Presentation
«Layer 7 - Application

TCP/IP model:
= Network Interface Layer
= Internet Layer
Transport Layer
» Application Layer

===== 1.2 Classify how applications, devices, and protocols relate to the OSI model layers.

===== 1. Physical Layer (Layer 1):
Devices: Hubs, Repeaters, Cables, Network Adapters

Protocols: Ethernet, USB, HDMI

===== 2. Data Link Layer (Layer 2):
The Data Link Layer is responsible for the reliable transmission of frames between nodes on the same network link.

Frames are the units of data at this layer and consist of both data and control information.

The Data Link Layer adds a header and trailer to the data received from the Network Layer (Layer 3), creating a frame for transmission over the physical medium.

Devices: Switches, Bridges, NICs (Network Interface Cards)

Protocols: MAC (Media Access Control) addresses, PPP (Point-to-Point Protocol)

===== 3. Network Layer (Layer 3):
The Network Layer is responsible for logical addressing, routing, and forwarding of data between different networks.

It deals with packets, which are units of data that include both the actual data being transmitted and the network-layer header information, such as source and destination IP addresses.

Devices: Routers, Layer 3 Switches

Protocols: IP (Internet Protocol), ICMP (Internet Control Message Protocol)

===== 4. Transport Layer (Layer 4):
Devices: Gateways

Protocols: TCP (Transmission Control Protocol), UDP (User Datagram Protocol)

===== 5. Session Layer (Layer 5):
Software: NetBIOS (Network Basic Input/Output System)

===== 6. Presentation Layer (Layer 6):
Software: Encryption/Decryption software, Compression software

Protocols: SSL/TLS

===== 7. Application Layer (Layer 7):
Software: Web browsers, Email clients, File Transfer Protocol (FTP) clients

Protocols: HTTP/HTTPS, FTP, SMTP, POP3, IMAP

==== 1.3 Explain the purpose and properties of IP addressing.

2.0 Network Installation and Configuration 23%

3.0 Network Media and Topologies 17%

4.0 Network Management 20%

5.0 Network Security 19%

Total 100%

