words summary for grandma:

www.facebook.com/collinsdictionary

== CONTENTS

THE ESSENTIALS
TRANSPORT
IN THE HOME
AT THE SHOPS
DAY-TO-DAY=
LEISURE
SPORT
HEALTH
PLANET EARTH
SPECIAL DAYS
ACKNOWLEDGEMENTS
PHOTO CREDITS

== ESSENTIALS
Hello. Pleased to meet you.
See you on Saturday.
Have a good evening!

==== YOU SHOULD KNOW...
British people often shake hands when they first meet.
Friends and relatives usually give each other a hug, or perhaps a kiss on the cheek.

I don’t understand.

==== YOU SHOULD KNOW...
When someone says “Sorry?” as a question, it means
they would like you to repeat what you’ve said.

I’m from Russia/Turkey.

I’m Russian/Turkish.

YOU SHOULD KNOW...
It is not polite in the UK to ask an adult how old they
are.

=== FRIENDS AND FAMILY
This is my husband/wife
How are they?
Are you married/single? Very well, thanks, and you?
I’m married/single. Fine, thanks.
I’m divorced. Great!
I have a partner. I’m OK.
I’m widowed. Not bad, thanks.
Do you have any children? I’m tired.
I have ... children. I’m thirsty.
I don’t have any children.


==== WELLBEING
He/She is...
How are you? They/We are...
How’s it going? happy
How is he/she? excited

Where do you work?
What do you do?
I work part-/full-time.
I work as a/an...

It’s ten past nine.
TIME It’s quarter past nine.
What time is it?
It’s 25 past nine.
It’s half past nine.
It’s 20 to ten.
It’s quarter to ten.
It’s five to ten.
It’s 17:30.
in 60 seconds/two minutes.
in quarter of an hour/half an hour.
the day before yesterday

==== YOU SHOULD KNOW...
In the UK, people don’t usually use the 24-hour clock to
talk about the time.

the week before last week
the week after next week
in the ’80s

==== WEATHER
What’s the weather like?
What’s the temperature?
How warm/cold is it?
Is it going to rain?
What a lovely day!

== TRANSPORT

There are lots of ways to get to the UK and
to travel around the country. There are
many good roads and motorways, as well
as railways that go up, down and across the
country, and airports in many of the bigger
towns and cities. Ferries also travel to a lot
of European places, and take passengers to
the many islands off the British coast.

say how far the place is in either yards and
miles, or metres and kilometres.

Excuse me...
Where is...?
Which way is...?
What’s the quickest way to...?
How far away is it?
Is it far from here?
I’m lost.
I’m looking for...
I’m going to...
Can I walk there?
It’s over there.

==== Do you know?
When you ask someone for directions, first
say “Excuse me”, then ask for the
information you want. The person might It’s ... miles/minutes away.

It’s in the other direction.

Go straight ahead.

==== YOU SHOULD KNOW...
Turn left/right. At traffic lights, an amber light signals to traffic that a
change is about to happen. Pedestrians should not cross

It’s next to... the road while the amber light is on. Remember to look right before you cross.

It’s opposite...
It’s near to...
Follow the signs for...
pedestrian
Is this the road to...?
Can I park here?
Do I have to pay to park?

I'd like to hire a car.
How much is it per day/week?
When/Where must I return it?

Where is the nearest petrol station?

YOU MIGHT HEAR...

You can/can’t park here.

It’s free to park here.

It costs ... to park here.

Car hire is ... per day/week.

May I see your documents, please?
Which pump are you at?

How much fuel would you like?

==== YOU SHOULD KNOW...

If you are in the UK for more than 12 months and you
want to drive, you must change your non-UK driving
licence for a British one.

==== VOCABULARY

passenger seat
clutch
cruise control
hybrid
to start the engine
to brake
to slow down
to speed
to stop
child seat
sunroof
to overtake
dashboard
fuel gauge
gearstick
glove compartment
headrest
ignition
rearview mirror
seatbelt
speedometer
steering wheel

bonnet

 windscreen
windscreen wiper
wing mirror
bumper
number plate
indicator
headlight

==== DRIVING

dual carriageway
slip road
hard shoulder
junction

Can you help me?
I’ve broken down.
I’ve run out of petrol.
antifreeze
to get a puncture
puncture repair kit

BICYCLE

handlebars pl
gears pl
saddle
pedal


aisle
railcard
peak ticket

off-peak ticket

single ticket
return ticket coach
e-ticket

to change trains
Departures

departure board

first class

freight train

light railway
locomotive

luggage rack

seat reservation
