words summary for grandma:

www.facebook.com/collinsdictionary

== CONTENTS

THE ESSENTIALS
TRANSPORT
IN THE HOME
AT THE SHOPS
DAY-TO-DAY=
LEISURE
SPORT
HEALTH
PLANET EARTH
SPECIAL DAYS
ACKNOWLEDGEMENTS
PHOTO CREDITS

== ESSENTIALS
Hello. Pleased to meet you.
See you on Saturday.
Have a good evening!

==== YOU SHOULD KNOW...
British people often shake hands when they first meet.
Friends and relatives usually give each other a hug, or perhaps a kiss on the cheek.

I don’t understand.

==== YOU SHOULD KNOW...
When someone says “Sorry?” as a question, it means
they would like you to repeat what you’ve said.

I’m from Russia/Turkey.

I’m Russian/Turkish.

YOU SHOULD KNOW...
It is not polite in the UK to ask an adult how old they
are.

=== FRIENDS AND FAMILY
This is my husband/wife
How are they?
Are you married/single? Very well, thanks, and you?
I’m married/single. Fine, thanks.
I’m divorced. Great!
I have a partner. I’m OK.
I’m widowed. Not bad, thanks.
Do you have any children? I’m tired.
I have ... children. I’m thirsty.
I don’t have any children.


==== WELLBEING
He/She is...
How are you? They/We are...
How’s it going? happy
How is he/she? excited

Where do you work?
What do you do?
I work part-/full-time.
I work as a/an...

It’s ten past nine.
TIME It’s quarter past nine.
What time is it?
It’s 25 past nine.
It’s half past nine.
It’s 20 to ten.
It’s quarter to ten.
It’s five to ten.
It’s 17:30.
in 60 seconds/two minutes.
in quarter of an hour/half an hour.
the day before yesterday

==== YOU SHOULD KNOW...
In the UK, people don’t usually use the 24-hour clock to
talk about the time.

the week before last week
the week after next week
in the ’80s

==== WEATHER
What’s the weather like?
What’s the temperature?
How warm/cold is it?
Is it going to rain?
What a lovely day!

== TRANSPORT

There are lots of ways to get to the UK and
to travel around the country. There are
many good roads and motorways, as well
as railways that go up, down and across the
country, and airports in many of the bigger
towns and cities. Ferries also travel to a lot
of European places, and take passengers to
the many islands off the British coast.

say how far the place is in either yards and
miles, or metres and kilometres.

Excuse me...
Where is...?
Which way is...?
What’s the quickest way to...?
How far away is it?
Is it far from here?
I’m lost.
I’m looking for...
I’m going to...
Can I walk there?
It’s over there.

==== Do you know?
When you ask someone for directions, first
say “Excuse me”, then ask for the
information you want. The person might It’s ... miles/minutes away.

It’s in the other direction.

Go straight ahead.

==== YOU SHOULD KNOW...
Turn left/right. At traffic lights, an amber light signals to traffic that a
change is about to happen. Pedestrians should not cross

It’s next to... the road while the amber light is on. Remember to look right before you cross.

It’s opposite...
It’s near to...
Follow the signs for...

That’s ... pounds, please.

=== VOCABULARY

pedestrian

Traffic drives on the left-hand side in the
UK. Remember to carry your driving
licence and insurance documents while
driving.

YOU MIGHT SAY...

Is this the road to...?
Can I park here?
Do I have to pay to park?

I'd like to hire a car.
How much is it per day/week?
When/Where must I return it?

Where is the nearest petrol station?

YOU MIGHT HEAR...

You can/can’t park here.

It’s free to park here.

It costs ... to park here.

Car hire is ... per day/week.

May I see your documents, please?
Which pump are you at?

How much fuel would you like?

YOU SHOULD KNOW...

If you are in the UK for more than 12 months and you
want to drive, you must change your non-UK driving
licence for a British one.

VOCABULARY

passenger seat

driver’s seat
back seat
engine

brake
accelerator
clutch

air conditioning
cruise control
manual
automatic
electric

hybrid

to start the engine
to brake

to slow down

to speed

to stop

YOU SHOULD KNOW...

A

Ds)

OF OY OO
a
a
There are drink-driving laws in the UK; you should not GENERAL
drink and drive.

roof rack

child seat

—

sunroof

people carrier
to overtake

to reverse

INTERIOR

dashboard

fuel gauge

gearstick

=g

glove compartment

handbrake

headrest

ignition

—

rearview mirror

seatbelt

speedometer

steering wheel

Da]

EXTERIOR

1. boot

2. roof

3. window
4. wheel
5. door

6. wing

7. tyre

1. bonnet

2. windscreen

3. windscreen wiper
4. wing mirror

5. bumper

6. number plate

7. indicator

8. headlight

DRIVING

In the UK, the speed limit is usually 70
mph (112 kmph) on motorways, 60 mph
(75 kmph) on main roads, and 30 mph (48

@ AQ A

kmph) in towns and cities. You have to pay Double yellow lines on the road means no parking at
any time.

for some roads and bridges, and in London
you have to pay to drive into the city
centre.

VOCABULARY

dual carriageway
corner

exit

slip road

hard shoulder
services pl
driving licence
car insurance

car hire/rental

rental car
unleaded petrol

diesel

YOU SHOULD KNOW...

car park double yellow lines p/

diversion junction
motorway

parking meter
parking space petrol station

pedestrian crossing road
speed camera

single-track road toll
traffic cone

traffic warden

tunnel

CAR TROUBLE

If you break down and your car stops
working on the motorway, you can call the
police or a breakdown service using one of
the orange emergency telephones at the
side of the road. Get out of your car and
stand a little way away from it while you
wait for help.

YOU MIGHT SAY...

Can you help me?

I’ve broken down.
@ AQ

OF OY OO

Ds)

I’ve had an accident. The car will be ready by...
I’ve run out of petrol. I need to take your details.
I’ve got a flat tyre.

YOU SHOULD KNOW...

I’ve lost my car keys. . . . . .
It is useful to keep items such as a warning triangle, hi-

The car won’t start. viz vest, and jump leads in your car.

There’s a problem with...

VOCABULARY
Call an ambulance/the police.

accident
Is there a garage/petrol station near here?

breakdown
Can you help me change this wheel?

hazard lights p/

When will the car be fixed?
to have an accident

May I take your details?
to have a flat tyre
to run out of petrol
YOU MIGHT HEAR...
Do you need any help?

Are you hurt?
What’s wrong with your car?
Where have you broken down?

It will cost...
GENERAL

antifreeze

breakdown service

de-icer

»”))

emergency phone hi-viz vest

garage
mechanic

petrol can

snow shovel

tow truck
warning triangle

to break down

to change a tyre

BUS

Bus services in towns and cities are usually
good; there are fewer buses in the country.
Coaches take people on longer journeys
from one city to another.

YOU MIGHT SAY...

Is there a bus to...?
When is the next bus to...?
Which bus goes to...?

Where is the bus stop?

»”))

@ AQ

i

Dy)

Which stand does the coach leave from? bus pass

Where can I buy tickets? fare

How much is it to go to...? concession

A single/return, please. day ticket

Could you tell me when to get off? wheelchair access
How many stops is it? school bus

I want to get off at the next stop, please. to catch the bus

to miss the bus

YOU MIGHT HEAR...

The number 17 goes to...

The bus stop is...

It leaves from stand 21.
There’s a bus every 10 minutes. bus
You can buy tickets at the office/on the bus.

This is your stop.

Have you got a bus pass?

VOCABULARY

bus route
C=

bus lane

bus shelter

bus station

B)

bus stop

double-decker bus

— YOU MIGHT HEAR...

o> — Ee Bike hire is ... per day/week.

You must wear a helmet.

minibus
VOCABULARY
yerrt SHUTTLE am CITY - AIRPORT - CITY” EVERY 10 MINUTES AIRPORT SHUTTLE)
eee cyclist
cycle lane
shuttle bus cycle path
to cycle
BICYCLE to go for a bike ride

to get a puncture
There are many cycling routes in the UK,
both short- and long-distance. Some roads
have cycle lanes, but otherwise cyclists
must keep to the left-hand side of the road.

YOU MIGHT SAY...

Where can I hire a bicycle?

How much is it to hire a bike?

Dy)

GENERAL

bike rack

child seat

mountain bike

puncture

a
e@ @

puncture repair kit

road bike

ACCESSORIES

bell

bike lock

helmet

lights p/

pump

»”))

———

reflective vest

BICYCLE

1. handlebars pl
2. gears pl

3. brake

4. saddle

5. wheel

6. tyre

7. chain

8. pedal

MOTORBIKE

»”))

To ride a moped or motorcycle in the UK
you must have a provisional licence and do
a training course before you take your

motorbike test. By law, motorcyclists must
wear a helmet.

GENERAL

boots pl

helmet
helmet cam

leather gloves pl

leather jacket

motorbike

ch,
6

motorcyclist
scooter

RAIL TRAVEL

You can travel by rail across England,
Scotland, Wales, and Northern Ireland.
There are also rail connections to Europe
via the Channel Tunnel. There are metro
systems in London, Glasgow, and
Newcastle, and trams operate in some

cities, including Blackpool and Edinburgh.

YOU MIGHT SAY...

Is there a train to...?

When is the next train to...?

How many stops is it?

Which platform does it leave from?

Which line do I take for...?

A ticket to ..., please.

A single/return ticket to ..., please.

I’d like to reserve a seat, please.
Do I have to change?
Where do I change for...?

Where is platform 4?

Is this the right train/platform for...?

Is this seat free?

I’ve missed my train!

YOU MIGHT HEAR...

The next train leaves at...

Would you like a single or return ticket?

I’m sorry, this journey is fully booked.

You must change at...

Dy)

Platform 4 is down there. YOU SHOULD KNOW...

This is the right train/platform. You can buy your ticket before you travel, but you can
also buy tickets on the train. Train tickets will cost more

You have to go to platform 2. during busy morning and evening periods (peak times).

This seat is free/taken.

Tickets, please.
The next stop is...

Change here for...

VOCABULARY

quiet coach
aisle
railcard
peak ticket

off-peak ticket

single ticket
return ticket coach
e-ticket

to change trains

»”))
Departures

departure board

first class

freight train

light railway
locomotive

luggage rack

RAL a ara Naat

“ERT =

platform

en

seat reservation

|

si

sliding doors p/
ticket barrier

£ Tickets & Tickets

Travel today Travel today

ticket office

train
train conductor

train station

viaduct
@ AQ
EP

AIR TRAVEL Check-in has opened for flight...

May I see your passport, please?

Ds)

The UK has many airports. Some airlines How many bags are you checking in?
only fly at certain times of the year to and Pl ho cat ,
from the UK. ease go to gate number...

Your flight is on time/delayed.

YOU MIGHT SAY... Is this your bag?

Flight ... is now ready for boarding.

I’m looking for check-in/my gate.
Last call for passenger...
I’m checking in one bag.

Which gate does the plane leave from? VOCABULARY
When does the gate open/close? airline
Is the flight on time? Arrivals/Departures
I would like a window/an aisle seat, please. Security
I’ve lost my luggage. Customs
My flight has been delayed. business class
I’ve missed my flight/connection. economy class
Is there a shuttle bus service? aisle
seatbelt
YOU MIGHT HEAR...

hand luggage

oversize baggage

hold luggage

hold

wing

jetlag

to check in (online) baggage reclaim
>
~ = Pe.
> coment | warmer

airport cabin

»”))

cabin baggage

cabin crew

check-in desk

Helsinki
Doha
Helsinki
Rimini
Rasterdan
Frankturt

duty-free shop
|
oxygen mask

lifejacket
runway

%

suitcase

terminal
tray table

FERRY AND BOAT TRAVEL

A lot of ferries travel from the UK to
Europe. Ferries also travel to the many
islands around Britain.

YOU MIGHT SAY...

When is the next boat to...?
Where does the boat leave from?
What time is the last boat to...?
How long is the trip/crossing?

How many crossings a day are there?

How much for ... passengers?

How much is it for a vehicle?

YOU MIGHT HEAR...

The boat leaves from...
The trip/crossing lasts...
There are ... crossings a day.

The ferry is delayed/cancelled.

VOCABULARY

ferry crossing
ferry terminal
car deck
coastguard
lifeboat
captain

foot passenger
to board

to sail

Dy)

©)
»”))

YOU SHOULD KNOW...

The UK also has thousands of miles of canals and
rivers. Many people enjoy travelling along the canals on
canal boats, and some people even live on these boats.

GENERAL

anchor

buoy
deck

harbour

lifebuoy

lifejacket

lock
marina port

pier
canal boat

inflatable

canoe

SesEEE enn el

PTLlire
Berth

—_ 7

kayak

cruise ship
sailing boat

yacht

a...
. =

— ae

IN THE HOME

Many people come to the UK for a holiday
or for a longer stay if they are going to
work or study. In the UK their home might
be a city flat, a house in the country, or a
family home in a town.

block of flats

1. roof
2. balcony
3. window

THE BASICS

Many people in the UK live in the city.
Often people go to the countryside at the

weekend or for a holiday.

YOU MIGHT SAY...

I live in...

I’m staying at...
My address is...

I have a flat/house.
I’m moving to...

I’d like to buy/rent here.

YOU MIGHT HEAR...

Where do you live?

Where are you staying?

How long have you lived here?
What’s your address, please?
Do you like this area?

Where are you moving to?

VOCABULARY

building

»”))

house

flat
address
owner
tenant
neighbour
deposit
mortgage
rent

to rent

to own

to move house
to buy

to sell

YOU SHOULD KNOW...

To rent a house or a flat in the UK go to an estate
agent’s office. They can help you.

TYPES OF BUILDING

bungalow

»”))

detached house

farmhouse

studio flat

4
_Pa
To
ed
i
aa
-
-
—
tat
-
—
—_

» » »

townhouse

villa

THE HOUSE

YOU MIGHT SAY...

There’s a problem with...

It’s not working.

The drains are blocked.

The boiler has broken.

There’s no hot water.

I need a plumber/an electrician.
Can you recommend anyone?

Can you repair it?
@ AQ

a as

Ds)

I can smell gas/smoke. central heating

to break
YOU MIGHT HEAR... to repair
What’s the problem? to decorate
How long has it been broken/blocked? to paint

i ?
Where is the meter/fusebox? YOU SHOULD KNOW...

9 oe
Here’s the number for a plumber/an electrician. The best way to find someone to repair something in

your home in the UK is to ask a friend or neighbour if
VOCABULARY they know anybody who can help.

room
basement
attic
ceiling
wall

floor
balcony
electricity
plumbing

air conditioning
INSIDE

extension cable

French windows

fusebox

ee EZ
—
Ss ee
SEZs
——

>

heater

light bulb

meter

AY

plug

radiator

satellite dish

co SE es EE
= cs en ee
— wae
co eee

security alarm

EY

am,

GE

socket

switch

se .
(ec

thermostat

is

wood-burning stove
OUTSIDE YOU MIGHT SAY/HEAR...

»”))

Would you like to come round?
Hi! Come in.

Make yourself at home.

Shall I take my shoes off?

Can I use your bathroom?

Thanks for inviting me.

VOCABULARY
stairs pl
1. roof landing
2. chimney
3. gutter lift
4. drainpipe
5. window lock
6. gate
hut th
7. driveway to open/shut the door
8. front door to let somebody in
9. garage
to wipe your feet
to hang your jacket up
THE ENTRANCE

YOU SHOULD KNOW...

If you are invited round to somebody’s house, it is
usually polite to take a small gift, such as flowers or a
bottle of wine.

doorbell

doormat

7

letterbox

»”))

lift

THE LOUNGE

VOCABULARY

carpet

satellite TV
cable TV
smart TV

TV on demand

to sit down

GENERAL

(aval) Pes |
bhonte) Mn aS i
ERY 2 RD

DAW TNL Deane id
me UD i
WN ak YC Aion) a

bookcase

curtains pl

display cabinet

—

DVD/Blu-ray® player

radio

coach
©

°
3

remote control

sideboard

sofa bed

»”))

table lamp

TV stand

Venetian blind

to relax
to watch TV

LOUNGE

1. wall light
2.TV

3. fireplace
4. coffee table
5. sofa

6. picture

7. ornament
8. shelves p/
9. armchair
10. rug

11. cushion

THE KITCHEN

Kitchens in the UK often have a table
where you can eat.

VOCABULARY

to cook

to boil

to roast

to bake

to clean

GENERAL

aluminium foil

apron

»”))

bin bag

clingfilm

kitchen roll

to stir fry
to wash up

KITCHEN EQUIPMENT

baking tray

cafetiére

casserole dish

chopping board

cooker hood

cooker

food processor
frying pan

hand mixer

als)

-~

‘)

kettle

kitchen knife
ladle

measuring jug

4

mixing bowl

a

peeler

te

rolling pin

saucepan

spatula

tin opener

toaster
y 4
P

wooden spoon

KITCHEN

1. sink

2. oven

3. hob

4. microwave

5. fridge-freezer
6. cupboard

7. tap

8. draining board
9. drawer

10. worktop

11. tiles pl

THE DINING ROOM

It is good manners to wait until everyone
has their food before you begin eating. It is
also polite to wait for everyone to finish
their meals before you leave the table.

GENERAL

dining table

napkin

pepper

place mat

4

salad bowl

serving dish

~-)

¥

vinegar
to set the table

TABLE SETTINGS

ee

cup and saucer

cutlery

plate

spoon

teaspoon

wine glass

THE BEDROOM

fi a
@
oy)
VOCABULARY

master bedroom
spare room
en-suite bathroom
bed

bedding

to make the bed

GENERAL

alarm clock

blanket

bunk beds p/
coat hanger

double bed

dressing table

hairdryer

laundry basket

nursery

single bed

to go to bed
sheets p/

he

to sleep
to wake up

BEDROOM

1. mirror

2. chest of drawers
3. wardrobe

4. duvet

5. curtains pl

6. drawer

7. bedside lamp
8. pillow

9. mattress

10. bedside table

THE BATHROOM

VOCABULARY

to have a shower

to go to the toilet

YOU SHOULD KNOW...

You cannot have electrical sockets in British bathrooms.

GENERAL

bath mat

face cloth

W

handwash
shower cap

shower curtain

soap

sponge

toilet brush

toilet roll
toothbrush

aa

toothpaste

towel

to brush your teeth
ay
“wed

to have a bath

to wash your hands
BATHROOM soil

grass

plant
tree
flower

to grow

1. mirror
2. sink

3. shower
4. toilet
5. tap

6. cabinet
7. bidet
8. bath

THE GARDEN

VOCABULARY

»”))

GENERAL

allotment

decking

gardener

garden fork

garden hose

gardening gloves p/

lawnmower

garden shed

plant pot

greenhouse
pruners p/

Strimmer®

trowel

watering can

Wellington boots p/
wheelbarrow

to water the plants

to mow the lawn
@ AQ

A

i

GARDEN

1. lawn

2. shrub

3. gate

4. fence

5. birdbox
6. path

7. flowers pl
8. patio

9. flowerpot

HOUSEWORK

VOCABULARY

recycling bin

to sweep the floor
to do the laundry
to hoover

to tidy up

to clean

YOU SHOULD KNOW...

In the UK, different coloured bins are used for different
types of waste.

bin
bleach

brush and dustpan

bucket

cloth

clothes horse

clothes pegs p/

dishwasher tablet

»

iron

ironing board

laundry detergent

mop
rubber gloves pl

tea towel

:
i

tumble drier

4

vacuum cleaner

washing line

»”))

ie

washing machine

washing-up liquid

AT THE SHOPS

There are lots of places to shop in the UK. You can go
shopping in local high streets where there are attractive
small shops, buy fresh food at farmers’ markets, and
visit the many large shopping centres where you can
find all the well-known shops.

basket
1. banana

2. bread
3. vegetable oil

THE BASICS

»”))

Most shops in the UK are open seven days a week. Are you being served?
Many have shorter hours at weekends, especially on
Sundays. In big cities you can find 24-hour

Can I help you?

. . 9

supermarkets . Would you like anything else?
It costs...

YOU MIGHT SAY... I’m sorry, we don’t have...

Can you enter your PIN?
Where is the...?

Would you like a receipt?
Where is the nearest...?

We don’t offer refunds.
Where can I buy...?

Have you got a receipt?
What time do you open/close?

Have a good day!
I’m just looking.
Do you sell...? YOU SHOULD KNOW...
May I have...? Single-use plastic bags are available from most shops, but you have to
pay for them. However, many people use their own bags or buy reusable
Can I pay by cash/card? bags.
Can I use contactless?
VOCABULARY
How much does this cost?
shop

How much is delivery?
corner shop

I need...

customer
I would like...

cash
I'd like to exchange this.

change
Can I get a refund?

PIN
That’s all, thank you.

exchange
YOU MIGHT HEAR... refund

voucher

Ds)
gift voucher
loyalty card
to buy
to pay

to order

basket

card reader

»”))

counter paper bag

S000 0000 0000 OO00

wm 11/19
MR, CARDHOLDER

debit/credit card
plastic bag

market

receipt
retail park

.

reusable shopping bag

shop assistant

to pay using contactless

to shop online

SUPERMARKET

Shopping online is very popular in the UK. Most

supermarkets will deliver your shopping to your house.

YOU MIGHT SAY...

Where can I find...?
I’m looking for...
Do you have...?

Can I have a plastic bag?

YOU MIGHT HEAR...

We have/don’t have...
It’s in aisle 1/2/3.

You have to pay for plastic bags.

»”))

Do you have a loyalty card?

VOCABULARY

fresh
frozen

low-fat

GENERAL

oo ee

box

»”))

carton

GROCERIES

breakfast cereal

cooking sauce

couscous

»”))

flour

honey

instant coffee

»”))

ketchup

marmalade

\,

mayonnaise

olive oil
rice

salt

spices pl

sugar

»”))

teabags pl

vegetable oil

a

¥

vinegar

SNACKS

biscuits pl

\

chocolate

crisps pl
nuts pl

fizzy drink
=

sweets p!

DRINKS fruit juice

a MARKET

Dy)

You can find markets in towns and cities all across the
UK. There are also farmers’ markets in many villages,
and car-boot sales at weekends.

YOU MIGHT SAY...
mineral water When is market day?
Do you have...?
| What do I owe you?
YOU MIGHT HEAR...

The market is on a Tuesday.
What would you like?

spirits pl Here’s your change.

VOCABULARY

stall
produce
local
organic
seasonal

wine home-made
flea market

market

market trader

»”))
FRUIT AND VEGETABLES

VOCABULARY

juice
fresh
rotten
ripe
unripe

seedless

GENERAL

peel

rind

skin

stone

FRUIT

apricot

avocado

»”))

blackberry

blackcurrant

blueberry

gooseberry
grapefruit lime

kiwi fruit

mango
orange

pineapple
raspberry

redcurrant

rhubarb

strawberry

watermelon
VEGETABLES

==.

asparagus

a:

aubergine

Ee

broccoli

Brussels sprout

cabbage

carrot

»”))

cauliflower courgette

celery

chilli garlic
mushroom

green beans pl

onion

leek

peas pl

lettuce
potato

red pepper

spinach

sweetcorn

we

tomato

turnip

FISHMONGER’S

YOU MIGHT SAY...

I'd like this filleted, please.

Can you remove the bones?

YOU MIGHT HEAR...

The fish was caught this morning.

Would you like the fish filleted?

VOCABULARY

fishmonger
seafood
fillet

scales pl
farmed
wild
smoked

deboned

GENERAL

shellfish

»”))
FISH

cod

herring

lemon sole

mackerel

monkfish

plaice

»”))

sardine

qa

sea bass

tuna

turbot

SEAFOOD

crab

crayfish
prawn

mussel

scallop
@ AQ

i

Dy)

I’d recommend...

VOCABULARY

meat
fillet

beef

pork
shrimp lamb
chicken
duck
turkey

liver

cooked
squid raw

free-range

BUTCHER’S

YOU MIGHT SAY...

A kilo/slice of...

Can you slice this for me, please?

YOU MIGHT HEAR...

How much/many would you like?
GENERAL

red meat

white meat

TYPES OF MEAT

bacon

chicken breast
(cured) sausage

ham

paté

»”))

BAKERY

Many British bakeries sell sandwiches, as well as cakes,
fresh bread, and rolls.

YOU MIGHT SAY...

sausages pl Do you sell...?
Could I have...?

How much are...?

YOU MIGHT HEAR...

Who’s next?

Would you like anything else?

It costs...

VOCABULARY

baker

white bread
brown bread
loaf

slice

pastry
gluten-free

to bake

cupcake

»”))
doughnut

éclair

muffin

scone

»”))

SAVOURY

“Sta

baguette

E>

(bread) rolls p/

croissant

pasty

sandwich

»”))

sliced bread

FRESH AND DAIRY PRODUCTS

VOCABULARY

blue cheese
single/double cream
free-range
dairy-free
pasteurized

unpasteurized

YOU SHOULD KNOW...

The colour on the top of a milk bottle shows you what type of milk is
inside.

»”))
GENERAL

butter

cream

eggs pl

margarine

|

semi-skimmed milk

(

skimmed milk

whole milk

yoghurt

CHEESE

cottage cheese

»”))

cream cheese

Edam

a ‘

“Ss

goat’s cheese

mozzarella

parmesan

»”))

@ AQ

Pharmacies (sometimes called “chemist’s’’) can also be
found in some supermarkets in the UK.

YOU MIGHT SAY...

I need something for...

I’m allergic to...
Red Leicester I’m collecting a prescription.
a sy »

. >

What would you recommend?

Is this suitable for young children?

ck ee > YOU MIGHT HEAR...
a oe
a + y Do you have a prescription?

Do you pay for your prescription?
Do you have any allergies?
You should see a doctor.

I’d recommend...

(

‘ °

ar | Pa oN YOU SHOULD KNOW...
a ;

s * @ . we : oe
‘ ne =a You can only get antibiotics from a pharmacy with a prescription from a
Ati # ‘ doctor. Prescriptions are free for everyone in Scotland, Wales, and
a fe Northern Ireland; in England you should check if you need to pay.
Wensleydale VOCABULARY
pharmacist

PHARM ACY prescription

antibiotics p/

Dy)
antihistamine
antiseptic
painkiller
cold

the flu
diarrhoea
allergy

hay fever
stomach ache
headache

sore throat

GENERAL

bandage

condom

cough mixture

™

»”))

insect repellent

medicine

drops pl

plaster

inhaler
suntan lotion antiperspirant

=

conditioner
“¥

<> “ oO
a,

tablet/pill

tissues pl

handwash
HYGIENE

fs
=

mouthwash

sanitary towel

shampoo

shaving foam

shower gel

=
435

tampon

»”))

4

toothbrush

Seu
———

toothpaste

BEAUTY

blusher

comb

eyeshadow

»”))

foundation

hairbrush

hairspray

\N

lip balm

lipstick

»”))

f

mascara

nail varnish

powder

BABY GOODS

VOCABULARY

disposable/reusable nappy
nappy sack

nappy rash

teething gel

to be teething

to breast-feed

»”))

CLOTHING

bib

bootees p/

mittens p/

snowsuit

»”))

vest

HEALTH AND HYGIENE

baby food

baby lotion

baby’s bottle

»”))

changing bag

cotton buds pl

cotton wool

nappy

nappy cream
wet wipes p/

ACCESSORIES

baby bath

baby sling

»”))
»”))

baby walker

yj qu.

dummy

highchair

G3

Moses basket
pushchair

7

sterilizer

« ——

teething ring

J

travel cot

NEWSAGENT

»”))

As well as newspapers and magazines, newsagents in
the UK usually sell stationery, stamps, lottery tickets,
and scratch cards.

VOCABULARY

book of stamps
to play the lottery

to smoke

GENERAL

cigar

x

comic book

»”))

confectionery

e-cigarette

envelope

greetings card

kiosk

lottery ticket

»”))

notebook

map pen

DAILY NEWS

— - —

newspaper pencil
scratch card

stationery

™

tobacco

DEPARTMENT STORE

»”))

There are lots of department stores in the UK. These YOU SHOULD KNOW...

sell all kinds of different products. In the UK, the ground floor is the same as the first floor in some other
countries; the first floor is the same as the second floor, and so on.

YOU MIGHT SAY...

Where is the ... department?
Which floor is this?
Can you gift-wrap this, please?

Are there any toilets in the store?

YOU MIGHT HEAR...

It is on the second floor.
This is the first floor.
Would you like this gift-wrapped?

The lift is over there.

VOCABULARY

counter
department
floor

sale
womenswear
menswear
sportswear

swimwear
GENERAL

lift

toilets p/

DEPARTMENTS

electrical goods pl

»”))

=r
eee eee ee

ee it | 5

footwear lighting
soft furnishings p/

@ AQ

CLOTHING AND FOOTWEAR

In the UK, you can find all your favourite international
fashion shops as well as some British ones you may not
know. Many people now also buy their clothes online.

YOU MIGHT SAY...

I’m just looking, thank you.

I'd like to try this on, please.
Where are the fitting rooms?
I’m a size...

Have you got this in...?

This is too...

YOU MIGHT HEAR...

Can I help you?

Let me know if I can help.
What size are you?

I’m sorry, we don’t have any.

I can get you another size.

YOU SHOULD KNOW...

Clothing and shoe sizes in the UK are different from those in other
countries.

VOCABULARY

»”))

(GK

GENERAL

clothes p/

shoes pl

wool

cotton

leather

petite

eo
a
?
n
2
—"

to try on

fitting room

to fit

sale

As Aes

3 : aie

5 a

BOE

EI Neesky AY

a€ Ss
3) Sa

size
CLOTHING

bikini

boxer shorts pl

cardigan

coat

»”))

dress

dressing gown

jacket

jeans pl

jogging bottoms p/

jumper
knickers p/

leggings pl

pyjamas pl
sweatshirt

swimsuit

(three-piece) suit

i
J

tights pl
trousers pi

T-shirt

waterproof jacket

ACCESSORIES

baseball cap

ee Bi

bracelet

»”))

jewellery
fragrance

gloves pl necklace
purse

woolly hat

umbrella
FOOTWEAR

boots p/

high heels p/

lace-up shoes pl

slippers pl

_—_

trainers pl

DIY STORE

»”))

DIY is popular in the UK; small shops or large stores
will sell what you may need.

VOCABULARY

home improvements p/
hardware shop

tool

power tool

toolbox

to do DIY

SKILLS

painting and decorating

plumbing

woodwork

EQUIPMENT

EP

chisel

-

electric drill

hammer

nails pl

nuts and bolts p/

»”))

paintbrush

paint roller

pliers p/

saw

screwdriver

screws pl

spanner
spirit level

tiles pl

wallpaper

wrench

GARDEN CENTRE

The local garden centre is often a nice place to visit at
the weekend. People choose plants and look at garden
furniture and equipment, and then many like to relax in
the café with afternoon tea. Many garden centres also
sell clothing and gifts.

»”))

GENERAL

bedding plant

compost

garden centre

garden furniture

hanging basket

»”))

parasol

seeds pl

OTHER SHOPS

barber’s

beauty salon

»”))

bookmaker’s

Pan e ry =

SMOSIDGK

boutique discount store
h

florist’s health food shop
off-licence

phone shop

»”))

toyshop

r

travel agent’s

DAY-TO-DAY

Business meetings, meals with friends, or courses of
study... whatever your schedule is while in the UK, you
will want to talk about what you are doing from day to
day.

tea (with milk)

1. cup
2. handle
3. saucer

»”))

THE BASICS

YOU MIGHT SAY...

Where are you going?
What time do you finish?
What are you doing today?
Are you free on...?

Would you like to meet up?

When/Where do you want to meet?

YOU MIGHT HEAR...

I’m at work/uni.
I have a day off.
I’m going to...
T’ll be back by...
T’ll meet you at...

I can’t meet up then, sorry.

VOCABULARY

to arrive
to work

to go home

to leave

Dy)

BREAKFAST

In the UK, breakfast is usually a small meal of cereal,
toast, and tea or coffee. Some people like to have a
cooked breakfast, often at the weekend. British people
often drink their tea with cold milk, and sometimes a
little sugar.

VOCABULARY

breakfast in bed
to have breakfast

to miss breakfast

»”))

DRINKS

orange juice

coffee
smoothie

hot chocolate

— a
—~4) |
\ }

tea (with milk)

milk

»”))
FOOD

bread and jam

breakfast cereal

ew

chocolate spread

continental breakfast

»”))

ee

cooked breakfast

croissant

marmalade

muesli

porridge

»”))

scrambled eggs p/

yoghurt

MAIN MEALS

The evening meal is the main meal of the day for most
people in the UK. This meal can be called either dinner,

@ AQ

tea, or supper, depending on where you live in the UK.
Lunch is often quite small, for example, sandwiches,
salad, or soup.

YOU MIGHT SAY...

What’s for dinner?

May I have...?

YOU MIGHT HEAR...

Dinner’s ready!

Would you like...?

VOCABULARY

to have lunch

to have dinner/tea/supper

YOU SHOULD KNOW...

Afternoon tea is usually made up of tea, sandwiches, and cakes.

»”))

lunch

GENERAL

to drink

to have a snack

»”))
STARTERS

breaded camembert

garlic bread

olives pl

pakora

paté

wo

prawn cocktail

»”))

soup
smoked salmon
SIDES

baked beans p/

cauliflower cheese

chips pl

coleslaw

green salad

»”))

mashed potato

onion rings p/

peas pl

potatoes pl

rice

Yorkshire puddings p/
CLASSIC DISHES

cottage pie

fish and chips

haggis

Irish stew

Lancashire hotpot

»”))

——_—

pea and ham soup

steak and kidney pie
ploughman’s lunch

roast dinner Welsh rarebit
DESSERTS

apple pie

Bakewell tart

cheesecake

chocolate cake

crumble

custard

»”))

ice cream

if
Lae ANS
ak

meringue

rice pudding

sticky toffee pudding

— NB Pass -

Victoria sponge
EATING OUT

Restaurants in the UK offer many different foods from
around the world, so it’s usually easy to find something
that you like to eat. It is best to book a table before you
go out, especially if you are going to a restaurant.

YOU MIGHT SAY...

I'd like to reserve a table.

A table for four, please.

We’re ready to order.

What would you recommend?

What are the specials today?

May I have ..., please?

Do you have vegetarian/vegan options?
I’m allergic to...

Excuse me, this is cold.

This is not what I ordered.

May we have the bill, please?

YOU MIGHT HEAR...

At what time?
For how many people?

Sorry, we’re fully booked.

Would you like anything to drink?
Are you ready to order?

I would recommend...

The specials today are...

Enjoy your meal!

VOCABULARY

set menu
vegetarian
vegan
gluten-free
dairy-free

to reserve a table
to order

to ask for the bill

to leave a tip

YOU SHOULD KNOW...

Many people leave some money for the waiter or waitress. This is called
a tip. In the UK a tip is usually about 10% of the bill.

Ds)
»”))

PLACES TO EAT OUT

GENERAL

=
' ~~ ?] ee
Pes

tera. yy
‘ aii oe tt

_

ae
}

beer garden

restaurant ”
bread basket

cheese knife

condiments p/

(daily) specials pi

fish knife

»”))

jug of water

menu

napkin

a

8

salt and pepper

steak knife

table

»”))

tablecloth

toothpicks p/

vinegar and oil

a

waiter/waitress

I

wine glass

»”))

FAST FOOD

Most larger British towns and cities have lots of
different fast-food and takeaway restaurants. Online
food delivery services also make it easy to order meals

to enjoy at home.

YOU MIGHT SAY...

I'd like to order, please.
Do you deliver?

I’m sitting in/taking away.
How long will it be?

That’s everything, thanks.

YOU MIGHT HEAR...

Can I help you?

Sit-in or takeaway?

We deliver/don’t deliver.
Would you like anything else?

Small, medium, or large?

VOCABULARY

street food
drive-thru

an order to go/a takeaway

to sit in

to take away

to deliver

to order (online)
to place an order

to collect an order

Ds)
[Feed Facto: |

fish and chip shop

FOOD

burger

filled baguette

»”))
fish and chips

kebab

sandwich

wy

)
ae F

»”))

@ AQ

Technology is an important part of our everyday lives.
It helps us to stay in touch with friends and family,
know what’s going on, and find the information we
need.

YOU MIGHT SAY/HEAR...

»”))

T’ll give you a call later.

T’ll text/email you.

What’s your number?

This is a bad line.

I don’t have any signal/WiFi.
What’s your email address?
The website address is...
What’s the WiFi password?
It’s all one word.

It’s upper/lower case.

VOCABULARY

post

social media
wrap email
email address

internet

COMMUNICATION AND IT

WiFi

website
link

icon

app

battery

cable

data

mobile phone
landline

text message

phone signal

voice mail

to make a phone call
to post (online)

to download/upload
to charge your phone

to switch on/off

to click/double-click on

to crash

YOU SHOULD KNOW...

The QWERTY keyboard is used in the UK.

GENERAL

JS)

charger

\

mouse mat

SIM card

»”))

wireless router

COMPUTER

@

1. screen

2. tower

3. button

4. keyboard
5. mouse

EDUCATION

Children start school at age 4-5 and can leave at age 16.
England, Scotland, Wales, and Northern Ireland all have
different education systems.

YOU MIGHT SAY...

What are you studying?

What year are you in?

»”))

YOU MIGHT HEAR...

I’m studying...

I’m in Year 6/my final year.

VOCABULARY

nursery school
primary school
secondary school
university
college

pupil

teacher
headteacher
playground
interactive whiteboard
timetable

lesson

lecture

tutorial
homework

exam

degree

student union

student card

to learn

to revise

YOU SHOULD KNOW...

School is usually from 9 a.m. to 3 p.m. Most pupils must wear school
uniform.

Ds)
SCHOOL UNIFORM

school uniform

tie

GENERAL

canteen/cafeteria

playing field
to sit an exam

to study

to teach

SCHOOL

i
\ i

colouring pencils p/

e—

eraser

exercise book

»”))

—

paper pencil case
5
/ schoolbag

™ —

sharpener
textbook
eo 2
e@
@
@
e — P
whiteboard

HIGHER EDUCATION

campus

lecture hall

»”))

student

THE OFFICE

YOU MIGHT SAY/HEAR...

Can we have a meeting?
May I speak to...?

Who’s calling?

Can I call you back?

I have a meeting with...
T’ll email the files to you.
Mr/Ms ... is on the phone.

Here’s my business card.

YOU SHOULD KNOW...

It’s quite normal for workers in many British offices to eat at their desks
or work through their lunch break.

VOCABULARY

manager

staff pl

colleague

client

human resources/HR
salary

accounts p/

figures p/

»”))

meeting
presentation
report
conference call
video conference
inbox

file
attachment
username
password

to type

to log on/off

CHARLIE
GORDON

CO-FOUNDER
BUSINESS NAME

business card

calculator

desk

»”))
hole punch

desk lamp

ink cartridge

filing cabinet

in/out tray

folder
laptop

Voeeeoeeee

notepad

paper clip

~~ 37

photocopier

printer

ring binder

»”))

Fy

scanner

oy

scissors pl

spreadsheet

stapler

“BE
|

sticky notes pl

sticky tape

»”))

swivel chair

telephone

USB stick

to make a video call
THE BANK

Most banks are open during normal business hours from
Monday to Friday, and some are also open on Saturday

mornings.

YOU MIGHT SAY...

I'd like to...

+». Open an account.

... exchange some money.

Is there a fee for this service?

I need to cancel my debit/credit card.

YOU MIGHT HEAR...

May I see your ID, please?

How much would you like to withdraw/deposit?
Could you enter your PIN, please?

You must fill out a form.

You will have to make an appointment.

VOCABULARY

branch
PIN
online banking

bank account

current account
savings account
account number
sort code

bank balance
overdraft

bank transfer
currency

loan

mortgage
interest

to borrow

to repay

Ds)
ATM

bank statement

cashier

chequebook

»”))

»))

5000 0000 0000 OO000

Ss

GS
st

safety deposit box to make a deposit
to withdraw money

THE POST OFFICE

Post offices can sometimes be found inside other shops,
for example, in newsagents.

YOU MIGHT SAY...

I'd like to send this first-class/by airmail.
How long will delivery take?

I'd like a book of stamps, please.

YOU MIGHT HEAR...

Place it on the scales, please.
What are the contents?
What is the value of this parcel?

How many stamps do you need?

VOCABULARY

address
postcode
postman
postwoman
courier
mail
airmail
first-class

second-class

YOU SHOULD KNOW...

Postboxes in the UK are red, but you may see gold postboxes in some
towns and cities — these celebrate gold medals won by local athletes at

the 2012 London Olympic and Paralympic Games®.

Dy)

GENERAL

delivery card

envelope

»”))
padded envelope

parcel tape

postal worker

postbox

»”))

to sign for

IN TOWN

When you are in the UK, there are many places that you

might need or want to visit. Some of the main ones are
shown here.

YOU MIGHT SAY...

How do I get to...?

Id like to visit...

»”))

I need to go to...

What are the opening hours?

YOU MIGHT HEAR...

It’s open between ... and...
Ask at the tourist office.
It’s here on the map.

It’s closed on Sundays.

PLACES OF IMPORTANCE

café

church

conference centre

»”))

a

a Ne ~~

courthouse

TE ec starion =
a —

fire station

fountain

hospital

laundrette
mosque

office block police station
town hall

LEISURE

A day trip, a weekend away, a night out,
maybe even a night in — we all like to do
different things in our free time. We also
like to talk with friends and colleagues
about our holidays and hobbies, or what
we did at the weekend.

tent

1. flysheet

2. guy rope

3. groundsheet
4. tent peg

THE BASICS

British people like to do different things
with their free time; favourite things to do
include playing sport, going out, or having
a quiet night in with a good book!

YOU MIGHT SAY...

What would you like to do?

What do you do in your spare time?
Have you got any hobbies?

Do you enjoy...?

Are you going on holiday this year?

YOU MIGHT HEAR...

My hobbies are...

I like...

I really enjoy it.

It’s not for me.

I’m going to ... on holiday.

I don’t have a lot of spare time.

VOCABULARY

spare time

activity

»”))

hobby
holiday
fun
boring
exciting
relaxing

interesting

GENERAL

to be bored

to enjoy

»”))

to relax

DIY

HOBBIES

»”))
reading

jogging shopping
walking

watching TV/films

SIGHTSEEING

Tourists from all over the world come to
the UK every year. They visit the UK’s
exciting cities and beautiful countryside.

YOU MIGHT SAY...

How much is it to get in?

Is there a discount for...?
Where is the tourist office?
Are there sightseeing tours?

Are there audio guides available?
YOU MIGHT HEAR...

Entry costs...

There is/isn’t a discount.
The tourist office is located...
You can book a guided tour.

Audio guides are/are not available.

VOCABULARY

tourist attraction
excursion

nature reserve
historic site

to visit

to see

YOU SHOULD KNOW...

Some cultural and historical sites, such as museums, art
galleries, and stately homes, offer discounts for certain
visitors.

audio guide

camera

»”))

castle

city map

guided tour
sightseeing bus

tourist

tourist office

»”))
@ AQ

| uo

EVENINGS OUT There is/isn’t a lot to do here.

My favourite bar/club is...

Ds)

There are lots of things to do in the I’m going for a few drinks/to the theatre.
evenings in most UK towns and cities. Ask

bf bd 7
what’s on at the tourist office, or ask There’s a film/show I'd like to see.

people who live there where they like to There are tickets/no tickets left.
80. It begins at 7 o’clock.

Please turn off your mobile phones.
YOU MIGHT SAY...

VOCABULARY
What is there to do at night?

a drink
What’s on at the cinema/theatre?

art

Where are the best bars/clubs? pay

film

Do you want to go for a drink?

to socialize
Do you want to go and see a film/show?

to enjoy yourself
Are there tickets for...? Jovy

; to see a show
Two seats in the stalls/balcony, please.

to watch a film
What time does it start?

to go dancing

YOU MIGHT HEAR... to order food/drinks

YOU SHOULD KNOW...

Restaurants in the UK do not usually stay open as late
as they do in other parts of the world.

ballet

bar

»”))
box

casino

cinema

comedy show

» |

concert

»”))

festival

karaoke

musical

opera

Da]

restaurant

stalls

theatre

HOTEL

There are plenty of places to stay in the
UK. You can stay in a boutique hotel, a
cosy bed and breakfast, or a cheap youth
hostel.

YOU MIGHT SAY...

Have you got any rooms available?

How much is it per night?
Is breakfast included?

I’d like to check in/out, please.

I have a reservation.

I’d like to book a single/double room, please.
What time do I have to check out?

What time is breakfast served?

I need fresh towels for my room.

I’m in room number...

I’ve lost my key.

I’d like to make a complaint.

YOU MIGHT HEAR...

We have some/don’t have any rooms available.

Our rates are...

Breakfast is/is not included.

Breakfast is served at...

May I have your room number, please?

May I see your documents, please?

@ AQ

You may check in after...

You must check out before...

YOU SHOULD KNOW...

There are plans to introduce a tourist tax in some places
across the UK.

VOCABULARY

bed and breakfast
full board

half board

wake-up call

per person per night
to check in

to check out

to order room service

Ds)

OF OY OO
PLACES TO STAY

guesthouse

hotel

or

A ie b=

youth hostel

»”))

GENERAL

a | (a

corridor

“do not disturb” sign

en-suite bathroom

key card

minibar

porter

reception

receptionist

room number

room service
toiletries p/

twin room

CAMPING

There are many campsites all around the
UK. You can also try “wild camping”,
where you don’t camp in a campsite.
However, if you are planning to do this,
you should ask the person who owns the
@ AQ

OF OY OO

Ds)

place you want to camp for permission pitch
where possible. glamping
to camp
YOU MIGHT SAY... .
to pitch a tent
Is it OK to camp here? to take down a tent
Have you got spaces available? to go caravanning

I’d like to book for ... nights.
How much is it per night?
Where is/are...?

Is the water drinkable?

YOU MIGHT HEAR...

You can/can’t put your tent up here.

We have some/don’t have any spaces available.
It costs ... per night.

The toilets/showers are...

The water is/is not drinkable.

VOCABULARY

GENERAL

air bed

campsite

electricity hook-up

picnic blanket

rucksack

motorhome

sleeping bag
@ A

The UK is an island, so it has many
colourful seaside towns and beaches, as
well as high cliffs you can walk along.

YOU MIGHT SAY...

»”))

tent
Is there a good beach nearby?

Is swimming permitted?
Is the water cold?
Can we hire...?

Help! Lifeguard!

toilet/shower block YOU MIGHT HEAR...

This is a public/private beach.

Swimming is allowed/not allowed.

Swimming is/is not supervised.

torch The water is warm/cold.

VOCABULARY

THE BEACH

sea

beach

Blue Flag beach
“No swimming”
to sunbathe

to swim

YOU SHOULD KNOW...

Not all UK beaches have lifeguards. A red-and-yellow
flag means that there is a lifeguard on the beach. A red
flag means it is dangerous to swim, and a yellow flag
means that you should be very careful in the water.

GENERAL

beach ball

beach flag

»”))

beach hut

beach towel

bikini

bucket and spade

flip-flops p/

ice-cream van
seaweed
sunglasses p/ sun umbrella

sunhat

swimming trunks p/

suntan lotion
swimsuit

windbreak

THE SEASIDE

‘ a TTT Ma
a. AHA rer J
—

1. pier
2.sea

3. beach

4. deckchair

MUSIC

The UK has many music festivals
throughout the year, from large concerts
like Glastonbury, to smaller classical
music festivals such as The Proms in
London.

»”))

@ AQ

—_——— -_ a, p OO TTCSCS—=OS:C~CT

Ds)

YOU MIGHT SAY... folk
electronic
I enjoy listening to music.
jazz
I’m learning to play the...
country

What kind of music do you like?
to play an instrument

YOU MIGHT HEAR... to sing

to listen to music

I like/don’t like...

to go to gigs
My favourite band is...

to stream music

VOCABULARY

song
album
live music
pop

rock
hip-hop
rap

classical
GENERAL

band

choir

DJ

gig

sheet music

»”))
MUSICAL INSTRUMENTS

accordion

acoustic guitar

bagpipes p/

bass guitar

cello

clarinet

double bass

harp
> a

keyboard

a

mouth organ

\

piano

saxophone

trombone

2
®

xylophone
trumpet

tuba

EQUIPMENT

Bluetooth® speaker

earphones p/

|

headphones p/

microphone

soundbar

speakers p/

turntable

vinyl record

PHOTOGRAPHY

Photography is a popular hobby in the UK.
There are a lot of things to photograph,
from beautiful scenery to exciting city
landscapes.

YOU MIGHT SAY...

Can I take photos here?

Where can I print my photos?

YOU MIGHT HEAR...

Photography isn’t allowed.

Say cheese!

VOCABULARY

photographer
photo

selfie

Dy)
selfie stick
landscape

portrait

to upload a photo

to take a photo/selfie

to zoom in

camera lens

compact camera

drone

»”))

DSLR camera

SD card

tripod

GAMES

Many people play board games at home.
People also play other games like darts and
cards in pubs. Many pubs have quiz nights
when teams try to answer questions and
win prizes.

YOU MIGHT SAY...

What would you like to play?
What are the rules?

How do you play?

YOU MIGHT HEAR...

Let’s play a game of...
It’s your turn.

Time’s up!

VOCABULARY

player

Dy)

team

hand (in cards)
to play

to win

to lose

GAMING

game controller

games console

Da]

gaming

joystick

video game

virtual reality headset

GENERAL

cards pl

counters pl

crossword

»”))

sudoku

ARTS AND CRAFTS

»”))

VOCABULARY

knitting
sewing
dressmaker
artist

to paint

to sketch

GENERAL CRAFTS

jewellery-making

to crochet

pottery to knit
ART MATERIALS

canvas

easel

»”))
paintbrush

palette

pastels p/

»”))

pen

watercolours p/

pencil

sketchpad
SEWING AND KNITTING

ball of wool

crochet hook

fabric scissors p/

/

knitting needles pl

needle and thread

pins p/

tape measure

safety pin
SPORT

People in the UK love watching and playing different

sports, for example, football, rugby, tennis, and cricket.

There are lots of sports and fitness clubs you can join,
and many sporting events that you can watch. You may
want to play a sport or go to the gym, or maybe just
chat about your favourite team or sportsperson.

2)

football pitch

1. centre circle
2. penalty box
3. goal
THE BASICS

YOU MIGHT SAY...

Where is the nearest...?
I play...
I'd like to book...

I support...

YOU MIGHT HEAR...

Do you do any sports?
What’s your favourite team?
Ima... fan.

Who do you support?

VOCABULARY

player
competition
manager
match
points p/
score

to coach

to compete

to score
to win
to lose

to draw

Ds)
draw official

leisure centre podium
PERIOD

scoreboard

spectators p/

sportsperson

stadium

stands p/
teammate

trophy

AT THE GYM

YOU MIGHT SAY...

I'd like to join the gym.
Id like to book a class.

What classes can you do here?

YOU MIGHT HEAR...

Are you a member here? EXERCISES

»”))

What time would you like to book for?

VOCABULARY

sym
gym membership
gym instructor

personal trainer

exercise class °

Pilates
to exercise
to book

to go for arun

to go to the gym

press-ups p/

running
spinning

yoga

THE GYM

changing room

L

cross trainer

dumbbell

»”))

exercise bike

oS w

gym ball

kettle bell

locker

rowing machine

showers p/
skipping rope

IK"

treadmill

weightlifting bench

FOOTBALL

Football is the most popular sport in the UK. There is
no UK team; each country has its own national team.
Many people support the team where they live, rather
than one of the larger teams.

YOU MIGHT SAY...

Are you going to watch the match?

What’s the score?

YOU MIGHT HEAR...

The score is...

Go on!

VOCABULARY

supporter
defender
striker
substitute
kick-off
half-time
full-time
free kick
offside
foul

to play football

to pass the ball

Dy)

assistant referee

football

football boots pl

football pitch

Ne

football player

»”))

goalkeeper

ev

goalkeeper’s gloves pl

penalty kick

shin pads pl

»”))

TB as
4 oa o£

tackle to kick the ball

ea

whistle

to save

yellow/red card

to score a goal
RUGBY

Rugby union and rugby league are both popular in the
UK. The Six Nations tournament — with teams from
England, Scotland, Ireland, Wales, France, and Italy — is
in February and March every year.

VOCABULARY

forward
back
conversion
penalty kick
pass
headguard
to play rugby
to tackle

to score a try

mouthguard

rugby

rugby ball

»”))

rugby field

(rugby) posts p/

rugby player

scrum

wheelchair rugby

CRICKET

Cricket is very popular in England. The most important
competition is the Ashes tournament. It is played
between the English and Australian national teams, and
happens every two years.

VOCABULARY

batsman/batswoman
bowler
wicket-keeper
cricket pitch

innings

over

run

to play cricket

to score a run

cricket ball

cricket bat
cricket helmet

al

i
Iho

leg pads pl

|

wicket

to field

RACKET SPORTS

@ AQ

i

Dy)

People in the UK have played tennis since 1873, and GENERAL
today it is one of the most popular sports in the country.

VOCABULARY

ace
fault
rally

deuce

game, set and match backhand
singles (match)

doubles (match)

to play badminton/squash/tennis
to hit

to serve

YOU SHOULD KNOW...

Wimbledon started in 1877 and is the oldest tennis competition in the
world. forehand

4
£4

serve
BADMINTON

badminton

badminton racket

' ?
i

shuttlecock

SQUASH

squash ball

squash racket

Da]

TENNIS

net

tennis

tennis ball

tennis court

»”))

a

tennis player

umpire

WATER SPORTS

VOCABULARY

swimming
diving

to swim
to dive

to surf

to paddle
to row

to sail

to fish

POOL

armbands p/

»”))

diving board

flippers p/

a

goggles p/l

lifeguard

»”))

swimmer

swimming cap

swimming pool

swimming trunks p/

swimsuit

»”))

OPEN WATER

bodyboarding

canoeing

fishing rod

jetski

»”))

lifejacket

rowing

paddle

»”))
scuba diving

snorkelling

&

surfboard

surfer

»”))

WINTER SPORTS

»”))

There are a number of ski resorts in the Scottish
Highlands, and excellent walking and climbing in areas
such as the Peak District and Snowdonia.

YOU MIGHT SAY...

waterskiing Can I hire some skis?

I'd like a skiing lesson, please.
What are the snow conditions like?

T’ve fallen.

YOU MIGHT HEAR...

You can hire skis here.
You can book a skiing lesson here.

The conditions are good/bad.

VOCABULARY

skier
ski resort
ski instructor

snow

ice

windsurfing

ice rink

mountain rescue service
to ski

to snowboard
to go sledging
to go ice skating

to go mountain climbing

GENERAL

avalanche

»”))
ice skates pl

ice skating

salopettes p/

ski boots pl

ski gloves p/

»”))

ski goggles pl

ski helmet

ski jacket

ski lift

ski poles pl

|

skis pl
snowboard

—_

snowboarding boots p/

WALKING AND CLIMBING

carabiner clip

compass

»”))

crampons p/

PY

ice axe

map

rucksack

walking boots p/

»”))

walking poles pl

COMBAT SPORTS

VOCABULARY

martial arts p/
fight

fighter
opponent

to box

to wrestle

to punch

to kick

to knock out

GENERAL

belt

©

fencing sword

headguard

Dy)

judo/karate suit

“9

mouthguard

.
t
Ss

referee

BOXING

boxing gloves p/

——

.

boxing ring

»”))

ASS
=

boxing shoes p/

knockout

punchbag

OTHER COMBAT SPORTS

fencing

»”))

kickboxing

taekwondo

wrestling

ATHLETICS

VOCABULARY

runner
race
marathon
start line
finish line

heat
final

sprint

triple jump
indoor athletics
to do athletics
to run

to race

to jump

to throw

YOU SHOULD KNOW...

The modern Olympics® started in Athens in 1896, and the Paralympic
movement started in England in 1948.

athlete

discus

high jump

»”))

javelin pole vault

lane relay
running track

shot put

spikes p/

starting blocks p/
golfer

golf course
green

hole
hole-in-one
handicap
over/under par
to play golf

to tee off

stopwatch

GOLF

People say that the modern game of golf started in Scotland in the 15th
century.

VOCABULARY

»”))

bunker

caddie

clubhouse

golf bag

golf buggy
A

a

golf club

putter

tee

OTHER SPORTS

archery

baseball

»”))

basketball

bowls
a >
5 ™ Pe 7 2
we S \ x 177 -’

3

ea Gt ou oom

horse racing motor racing

motorcycle racing shooting
showjumping

skateboarding

snooker

table tennis

triathlon
weightlifting

HEALTH

It is best to be prepared for your visit to the
UK. Make sure you have the correct
healthcare cover, and if you are on holiday,
you must have travel insurance.

first-aid kit

1. bandage
2. tablet

3. plaster
4. syringe
THE BASICS

The National Health Service (NHS)
provides free medical care for people who
usually live in the UK. There are also
many private hospitals and healthcare
practices.

YOU MIGHT SAY...

I don’t feel well.
I’ve hurt...
I need to see a doctor/go to hospital.

Can you call an ambulance?

YOU MIGHT HEAR...

What’s wrong?
Where does it hurt?
What happened?

How long have you been feeling ill?

@ AQ

YOU SHOULD KNOW...

999 is the emergency number for the UK — use it to call
the police, ambulance, or fire brigade. 111 is the number
for non-emergency medical advice. You can ask for a
translator when you call either number.

VOCABULARY

first aid

illness

symptom
mental health
treatment
health insurance
to hurt

to recover

to treat

EMERGENCY SERVICES

Ds)

OF OY OO
ambulance

first-aid kit

medicine

q

nurse pharmacist

to be in pain

ae

to feel sick

THE BODY

VOCABULARY

tongue
skin

(body) hair
beard
moustache
genitals p/
breast

height
weight
to see
to smell
to hear
to touch
to taste
to stand
to walk

to move

YOU SHOULD KNOW...

In English, the possessive adjective (for example, my,
his, their) is generally used when talking about body
parts. For instance, you say “We washed our hands” or
“T’ve hurt my leg”.

HEAD

1. hair

2. eye

3. ear

4. nose

5. jaw

6. throat

7. forehead
8. cheek

9. mouth
10. chin

Dy)

1. eyebrow
2. eyelid

3. eyelash

4. nostrils p/
5. earlobe

6. lips pl

HAND

1. wrist

2. knuckle
3. fingernail
4. palm

5. thumb

6. finger

»”))

FOOT BODY - FRONT

1. big toe
2. toe

3. sole

4. heel

5. toenail
6. ankle

»”))

1. head
2. neck

3. chest

4. stomach
5. thigh

6. knee

7. shin

8. face

9. arm

10. hand
11. leg

12. foot

»”))

BODY - BACK

1 ° shoul: der
2. back

@ AQ

—_——— -_ a, p OO TTCSCS—=OS:C~CT

Ds)

3. buttocks pl vein

4. elbow

5. hip oxygen
6. calf

INSIDE THE BODY

VOCABULARY

organ
blood
joint
skeleton
bone
muscle
nerve
tendon
tissue
ligament
cell

artery
INTERNAL ORGANS SKELETON

1. brain

2. lung

3. liver

4. intestines pl
5. heart

6. stomach

7. kidney

8. bladder

1. skull

2. collarbone
3. humerus
4. radius
5.ulna

6. pelvis

7. kneecap

8. vertebrae pl
9. breastbone
10. ribs pl

11. spine

12. femur

13. fibula

14. tibia

THE DOCTOR’S SURGERY

In the UK, you may wish to register with a
local GP practice or a health centre. You
will need to live near to the GP practice or
health centre, and you must have proof of
address and photo ID.

YOU MIGHT SAY...

I'd like to register with the practice.

I’d like to make an appointment.

@ AQ

| uo

Ds)

I have an appointment with Dr... test

I’m allergic to... prescription

I’m on medication for... antibiotics p/

I’ve been feeling unwell. insulin
sleeping pill

YOU MIGHT HEAR...

to make an appointment

The doctor will see you now. to examine
What are your symptoms? to be on medication
May I examine you?

Tell me if that hurts.

Do you have any allergies?

Do you take any medication?

Take two tablets twice a day.

VOCABULARY

health centre
appointment
clinic

examination
blood pressure monitor

ene

examination room

examination table

practice nurse
stethoscope

syringe

the pill

=~

thermometer

vaccination

‘
\ i

waiting room

@ AQ

—_——— -_ a, p OO TTCSCS—=OS:C~CT

THE DENTIST’S SURGERY check-up

wisdom teeth p/

Ds)

YOU MIGHT SAY... filling

crown

I need a check-up.
P root canal treatment

I have toothache/an abscess.

extraction
My filling has come out.
toothache
I’ve broken my tooth.
abscess
My dentures are broken.
YOU SHOULD KNOW...
YOU MIGHT HEAR... You usually have to pay for dental care in the UK.

We don’t have any emergency appointments
available.

You need a new filling.
Unfortunately your tooth has to come out.

You will need to make another appointment.

VOCABULARY

hygienist
GENERAL

dental floss

dentist’s chair
dentist’s drill

gums p/

mouthwash

teeth p/

A

toothbrush

4
——,

toothpaste

to floss

to have toothache

THE OPTICIAN’S

YOU MIGHT SAY...

Can I book an appointment?
My eyes are dry.
My eyes are sore.

Do you repair glasses?

YOU MIGHT HEAR...

Your appointment is at...

Look up/down/ahead. In most parts of the UK you have to pay for eye care,
although it is free in Scotland.
You have perfect vision.

You need glasses.

VOCABULARY

reading glasses pl
lens
conjunctivitis
blurred vision
cataracts pl
short-sighted
long-sighted
visually impaired
blind
colour-blind

to wear glasses

to wear contacts

YOU SHOULD KNOW...

GENERAL

A

contact lens case

contact lenses p/

=

eye test

—_

frames pl

glasses pl

glasses case

guide dog

optician
stye

THE HOSPITAL

In the UK, hospitals see patients who are
sent there by their GP, and help people in
an emergency.

YOU MIGHT SAY...

Which ward is he/she in?

When are visiting hours?

YOU MIGHT HEAR...

He/She is in ward...

Visiting hours are from ... to...

VOCABULARY

patient

visitor

visiting hours pl
diagnosis

to have surgery

to be admitted/discharged

YOU SHOULD KNOW ...

Treatment at a UK hospital is free at the
moment of need. However, patients from
other countries may need to pay for some
hospital services.
Accident &

crutches p/

defibrillator

hospital trolley

monitor

operating theatre

oxygen mask

plaster cast
stitches pl

surgeon

wheelchair

X-ray

Zimmer frame®
@ AQ

OF OY OO

Ds)

INJURY GP, or go to A&E at the nearest hospital.
VOCABULARY

YOU MIGHT SAY... accident

I’ve had an accident. concussion

I’ve hurt... fall

I’ve broken/sprained... whiplash
CPR

I’ve cut/burnt myself.

I’ve hit my head.

YOU MIGHT HEAR...

Do you feel faint?

Do you feel sick?

I’m calling an ambulance.
Where does it hurt?

Tell me what happened.

YOU SHOULD KNOW...

Ambulances in the UK are for serious accidents and
emergencies only. If you hurt yourself, you should see a

recovery position
pulse
to be unconscious
to injure yourself
to fall

to break your arm

to twist your ankle
GENERAL

to put someone into the recovery
position

to take someone’s pulse

INJURIES

blister

burn

cut

dislocation

»”))

fracture

graze

scar

splinter

sunburn
swelling

adhesive tape

antiseptic cream
(GK

or

neck brace

dressing

plaster

ice pack
I’m going to be sick.

YOU MIGHT HEAR...

»”))

You should go to the doctor.

You need to rest.
sling
VOCABULARY

heart attack

stroke

infection

the flu

migraine

tweezers pl

virus

stomach bug

ILLNESS

nausea

diarrhoea

YOU MIGHT SAY... constipation

I have... diabetes

epilepsy
asthma
dizziness

to feel/be sick
to faint

to have high/low blood pressure

rash
to cough

to sneeze

|

to vomit

PREGNANCY

If you plan to have your baby in the UK,
you will be able to see a midwife during
your pregnancy.

YOU MIGHT SAY...

I’m/She’s (six months) pregnant.
I’m/She’s having contractions every ... minutes.

My/Her waters have broken.

YOU MIGHT HEAR...

How long is it between contractions?
May I examine you?

Push!

VOCABULARY

foetus

cervix

labour

gas and air
birth plan
delivery
Caesarean section
miscarriage
due date

to be pregnant
to be in labour
to give birth
to miscarry

to breast-feed

YOU SHOULD KNOW...

A full-term pregnancy in the UK is 39 weeks and 6
days.

hospital tag

»”))

midwife

morning sickness

newborn

kL

pregnancy test
pregnant woman

38

Tag we

en) Je 7

sonographer

ultrasound

ALTERNATIVE THERAPIES

Alternative therapies are becoming popular
in the UK, but you may have to pay for
any treatments.

VOCABULARY

therapist
masseur
masseuse
chiropractor
acupuncturist
reflexologist
remedy
supplements pl
reiki

to massage

to meditate

YOU SHOULD KNOW...

Going to a spa or health resort is popular with many
British people who want to improve their health and
wellbeing.

essential oil

»”))

massage

hypnotherapy osteopathy
reflexology shiatsu massage

sauna

steam room
traditional Chinese medicine

THE VET

If you are going to travel to the UK with
your pet, they must be microchipped,
vaccinated against rabies, and have a pet
passport. Dogs must get a tapeworm
treatment from a vet 1-5 days before they
enter the UK.

YOU MIGHT SAY...

My dog is hurt.

My cat has been sick.

YOU MIGHT HEAR...

What is the problem?

Is your pet microchipped?

VOCABULARY

pet passport
quarantine
microchip
tapeworm treatment
tick

to worm

to microchip

to spay/neuter

to put down

Dy)

E-collar

flea

-

} fay
ie

flea collar

vaccination

PLANET EARTH

The UK has some beautiful places to visit. Choose from
the mountains in Scotland and Wales, the coast of
Northern Ireland, or the green hills of England. There
are lots of walking routes so you can discover the
country for yourself. Look out for the many nature
reserves and national parks around the country too.

Dy)
THE BASICS

VOCABULARY

animal
bird
fish
species

fur

wool
to bark
to purr

to growl

»”))

claw

y,

feather

mane
@ AQ

The UK is known for its love of animals. You can take
your dog to many pubs and cafés. You should keep your
dog on a lead on countryside walks, where there are
sheep or cows.

YOU MIGHT SAY...

Do you have any pets?

Is it OK to bring my pet?

YOU MIGHT HEAR...

I’m allergic to pet hair.

Animals are not allowed.

VOCABULARY

tail
farmer
farm
owner
barn
hay

straw

field

wing

guide dog

DOMESTIC ANIMALS AND BIRDS

»”))
BABY ANIMALS AND BIRDS

calf

chick

foal

puppy

»”))

PETS

budgerigar

ferret

goldfish

guinea pig

»”))

hamster

parrot

pony

tropical fish
FARM ANIMALS

chicken

donkey

duck

»”))

goose

pig

te

sheepdog

turkey

GENERAL

collar

=.)

cage

hamster wheel

catflap

»”))
hutch

lead

litter tray

stable

»”))

AMPHIBIANS AND REPTILES

chameleon

crocodile

lizard

MAMMALS

badger

bat

deer

fox

hedgehog

»”))

otter

weasel
chimpanzee

OTHER COMMON MAMMALS

gorilla

»”))
hippopotamus

monkey

kangaroo

rhinoceros

lion tiger
BIRDS

blackbird

crow

dove

eagle

falcon

finch

»”))

gannet

hawk

heron

kingfisher

»”))

ostrich

owl

peacock

pelican

H
Be

penguin

pigeon
robin

sparrow

starling

swan

thrush
MINIBEASTS

VOCABULARY

swarm
nest
cobweb
insect bite
to buzz

to sting

ant

bee

beetle

»”))

butterfly

caterpillar

cockroach

Se

daddy longlegs

dragonfly

earthworm
earwig

grasshopper

ladybird

midge

mosquito
snail

woodlouse
MARINE CREATURES

crab

dolphin

eel

jellyfish

killer whale

lobster

octopus

seal

sea urchin

shark

starfish

whale

»”))

FLOWERS, PLANTS, AND TREES

branch

bulb

trunk
FLOWERS

bluebell

buttercup

carnation

heather

»”))

hyacinth

orchid

iris

lily

poppy
sunflower

tulip

PLANTS AND TREES

birch

cherry

clover

»”))

pine

poplar

sycamore

thistle

willow
LAND, SEA, AND SKY

VOCABULARY

landscape
soil

water

air

rural

urban

LAND

desert

farmland
glacier

hill

vv.

lake/loch

marsh

~~
=

meadow
»”))

pond

moorland

stream
volcano

waterfall

SEA

island

»”))

rockpool

sand dunes p/

SKY

aurora

clouds p/

»”))

comet

moon

rainbow

stars pl

sunrise

»”))

sunset

SPECIAL DAYS

Everyone loves being with friends and family on special
days. In the UK, this usually means eating good food
and maybe having a glass of champagne. Look out for
all the local parties and activities you can take part in on
the various holidays in the UK.

Dy)

Happy birthday!
Happy anniversary!
Best wishes.

Thank you.

You’re very kind.

Cheers to you, too!

VOCABULARY

occasion
celebration
birthday
birthday party

surprise party

wedding anniversary

cake bank/public holiday
1. icing religious holiday

2. candle

3. cake stand good/bad news

to celebrate

THE BASICS to throw a party

to make a toast

YOU MIGHT SAY/HEAR... YOU SHOULD KNOW...

People in the UK love to buy greetings cards to give other people on a
special day. In fact, they buy more greetings cards per year than anyone
Well done! else in the world.

Congratulations!

Cheers!

»”))
box of chocolates

bunting

cake

champagne
fireworks p/

gift

gift bag

&

greetings card

PUBLIC HOLIDAYS

There are between 8 and 10 official public holidays
(also known as bank holidays) each year in the UK.

YOU MIGHT SAY/HEAR...

Happy Easter!

April Fool!

VOCABULARY

Mother’s Day
Father’s Day

May Day

YOU SHOULD KNOW...

On April Fool’s Day (1st April), many people play tricks on each other
and say ‘April Fool!’

»”))

BRITISH CELEBRATIONS

Guy Fawkes Night

Burns Night

ON eee

¥ OB ale ‘hanno
nk
b

Morris dancing

Eisteddfod

me

»”))
OTHER CELEBRATIONS

Diwali

Eid-al-Fitr

Halloween

»”))

Hanukkah

Holi

Passover

Ramadan

Shrove Tuesday

uAPPY

VALENTINE S

Valentine’s Day
CHRISTMAS AND NEW YEAR

Christmas is celebrated on December 25th in the UK
with gifts and a special Christmas dinner. This is often
roast turkey, with Christmas pudding for dessert.
Boxing Day (December 26th) is also a public holiday.

YOU MIGHT SAY/HEAR...

Merry Christmas!

Happy New Year!

VOCABULARY

Advent
Christmas Eve
Christmas Day
Boxing Day
Christmas carol

New Year’s Day

YOU SHOULD KNOW...

Many British people go to a pantomine around Christmas. Pantomimes
are plays based on fairy tales, and include singing, dancing, and comedy.
They are fun for all the family.

Advent calendar

bauble

carol singing

»”))

Christmas card

Christmas cracker

Christmas dinner

Christmas lights p/

Christmas pudding

Christmas tree

»”))

Father Christmas/Santa Claus

Nativity play

present

»”))

wrapping paper

wreath

LIFE EVENTS

@ AQ

People often give greetings cards on birthdays and other
life events, happy or sad, in the UK. It is usual to
celebrate someone’s 18th and 21st birthdays.

VOCABULARY

first day of school
new job

moving house

»”))

baptism/christening engagement

bar/bat mitzvah
funeral
graduation

retirement

wedding

ACKNOWLEDGEMENTS

We would like to thank those authors and publishers who kindly
gave permission for copyright material to be used in the Collins
Corpus. We would also like to thank Times Newspapers Ltd for
providing valuable data.

MANAGING EDITOR
Maree Airlie

FOR THE PUBLISHER
Gerry Breslin
Robin Scrimgeour

CONTRIBUTORS
Rebecca Adlard

»”))

PHOTO CREDITS

Shutterstock: timetable (Brendan Howard), exterior
[below] (JazzBoo), breakdown service (Piranhi), to
break down (Maciej Matlak), bus station (Axel
Bueckert), minibus (Iakov Filimonov), shuttle bus
(urbanbuzz), light railway (Bikeworldtravel), metro
station (Valerieka), ticket machine (Balakate), ticket
office (Michael715), toilets (dagma), train conductor
(cowardlion), tram (smereka), flight attendant (RUBEN
M RAMOS), passport control (Dizfoto), retail park
(jax10289), shopping centre (Radu Bercan),
supermarket (O6photo), car-boot sale (mubus7),
farmer’s market (Thierry Maffeis), indoor market (GTS
Productions), market (Del Boy), confectionery (Bitkiz),
kiosk (Hadrian), cosmetics (mandritoiu), food and drink
(1000 Words), footwear (Toshio Chan), kitchenware
(NikomMaelao Production), toys (Zety Akhzar),
discount store (David Alexander Photos), electrical
retailer (BestPhotoPlus), estate agent’s (Barry Barnes),
pet shop (BestPhotoPlus), beer garden (Pawel
Pietraszewski), burger/snack van (Lucian Milasan),
fast-food chain (Cassiohabib), bureau de change (Lloyd
Carr), stamp (Andy Lidstone), to post (Matthew
Ashmore), church (Ilya Images), conference centre (lou
armor), hotel (Osugi), guided tour (withGod),
sightseeing bus (Roman Sigaev), casino (Benny Marty),
comedy show (stock_photo_world), musical (Igor
Bulgarin), opera (criben), beach flag (antb), ice-cream

Ds)
A

Dy)

i

van (Jason Batterham), promenade (Oscar Johns), choir
(Marco Saroldi), orchestra (Ferenc Szelepcsenyi),
football pitch (Christian Bertrand), penalty kick (Albo),
tackle (Laszlo Szirtesi), to save (mooinblack), try
(Paolo Bona), wheelchair rugby (Travability Images),
line judge (Leonard Zhukovsky), umpire (Stuart
Slavicky), dry ski slope (Christophe Jossic), motor
racing (Cristiano barni), table tennis (Stefan Holm),
water polo (katacarix), fire brigade (abd), police (Pres
Panayotov), A&E (kay roxby), labour suite
(ChameleonsEye), Eisteddfod (Andreas Zernd1), Irish
dancing (Zvonimir Atletic), Morris dancing
(JaneHYork), carol singing (1000 Words). All other
images from Shutterstock.

& HarperCollinsPublishers

ABOUT THE PUBLISHER

Australia

HarperCollins Publishers Australia Pty. Ltd.

Level 13, 201 Elizabeth Street
Sydney, NSW 2000, Australia
www.harpercollins.com.au

Canada

HarperCollins Canada

Bay Adelaide Centre, East Tower
22 Adelaide Street West, 41st Floor
Toronto, Ontario, M5H 4E3
www.harpercollins.ca

India

HarperCollins India

A75, Sector 57

Noida, Uttar Pradesh 201 301, India
www.harpercollins.co.in

New Zealand

HarperCollins Publishers New Zealand
Unit D1, 63 Apollo Drive

Rosedale 0632

Auckland, New Zealand
www.harpercollins.co.nz

United Kingdom
HarperCollins Publishers Ltd.
@ AQ

i

Dy)

1 London Bridge Street
London SE1 9GF, UK
www.harpercollins.co.uk

United States

HarperCollins Publishers Inc.
195 Broadway

New York, NY 10007
www.harpercollins.com
